# -*- coding: utf-8 -*-
# N4: thuật ngữ tiếng Nhật cho từ vựng IT (dùng trong gen_data.py -> trường "ja": "日本語|romaji")
# Ưu tiên cách nói thực tế ở công ty IT Nhật (katakana khi ngành dùng katakana).
JA = {
 "task":("タスク","tasuku"),"standup":("朝会","chōkai"),"blocker":("ブロッカー","burokkā"),"in progress":("対応中","taiōchū"),
 "backlog":("バックログ","bakkurogu"),"priority":("優先度","yūsendo"),"deadline":("締め切り","shimekiri"),"update":("更新","kōshin"),
 "assign":("アサイン","asain"),"estimate":("見積もり","mitsumori"),"commit":("コミット","komitto"),"branch":("ブランチ","buranchi"),
 "merge":("マージ","māji"),"pull request":("プルリクエスト","puru rikuesuto"),"clone":("クローン","kurōn"),"push":("プッシュ","pusshu"),
 "pull":("プル","puru"),"merge conflict":("コンフリクト","konfurikuto"),"repository":("リポジトリ","ripojitori"),"revert":("差し戻し","sashimodoshi"),
 "code review":("コードレビュー","kōdo rebyū"),"approve":("承認","shōnin"),"comment":("コメント","komento"),"feedback":("フィードバック","fīdobakku"),
 "refactor":("リファクタリング","rifakutaringu"),"readable":("読みやすい","yomiyasui"),"naming":("命名","meimei"),"duplicate":("重複","chōfuku"),
 "suggestion":("提案","teian"),"minor":("軽微","keibi"),"unit test":("単体テスト","tantai tesuto"),"bug":("バグ","bagu"),
 "reproduce":("再現","saigen"),"edge case":("エッジケース","ejji kēsu"),"coverage":("カバレッジ","kabarejji"),"fail":("失敗","shippai"),
 "pass":("合格","gōkaku"),"regression":("デグレ","degure"),"stack trace":("スタックトレース","sutakku torēsu"),"root cause":("根本原因","konpon gen'in"),
 "deploy":("デプロイ","depuroi"),"rollback":("ロールバック","rōrubakku"),"staging":("ステージング","sutējingu"),"production":("本番環境","honban kankyō"),
 "environment":("環境","kankyō"),"downtime":("ダウンタイム","daun taimu"),"hotfix":("緊急修正","kinkyū shūsei"),"release":("リリース","rirīsu"),
 "build":("ビルド","birudo"),"config":("設定","settei"),"schema":("スキーマ","sukīma"),"migration":("マイグレーション","maigurēshon"),
 "query":("クエリ","kueri"),"table":("テーブル","tēburu"),"record":("レコード","rekōdo"),"backup":("バックアップ","bakkuappu"),
 "index":("インデックス","indekkusu"),"constraint":("制約","seiyaku"),"dataset":("データセット","dēta setto"),"endpoint":("エンドポイント","endopointo"),
 "request":("リクエスト","rikuesuto"),"response":("レスポンス","resuponsu"),"payload":("ペイロード","peirōdo"),"timeout":("タイムアウト","taimu auto"),
 "latency":("レイテンシ","reitenshi"),"token":("トークン","tōkun"),"status code":("ステータスコード","sutētasu kōdo"),"rate limit":("レート制限","rēto seigen"),
 "integration":("連携","renkei"),"agenda":("アジェンダ","ajenda"),"action item":("アクションアイテム","akushon aitemu"),"follow up":("フォローアップ","forō appu"),
 "clarify":("確認する","kakunin suru"),"align":("認識を合わせる","ninshiki o awaseru"),"recap":("振り返り","furikaeri"),"sync":("すり合わせ","suriawase"),
 "stakeholder":("関係者","kankeisha"),"minutes":("議事録","gijiroku"),"wrap up":("まとめ","matome"),"issue":("課題","kadai"),
 "workaround":("回避策","kaihisaku"),"escalate":("エスカレーション","esukarēshon"),"investigate":("調査","chōsa"),"impact":("影響","eikyō"),
 "urgent":("至急","shikyū"),"outage":("障害","shōgai"),"severity":("重要度","jūyōdo"),"mitigate":("緩和する","kanwa suru"),
 "resolve":("解決","kaiketsu"),"scope":("スコープ","sukōpu"),"milestone":("マイルストーン","mairusutōn"),"sprint":("スプリント","supurinto"),
 "requirement":("要件","yōken"),"dependency":("依存関係","izon kankei"),"deliverable":("成果物","seikabutsu"),"timeline":("スケジュール","sukejūru"),
 "trade-off":("トレードオフ","torēdo ofu"),"feasible":("実現可能","jitsugen kanō"),"password":("パスワード","pasuwādo"),"encryption":("暗号化","angōka"),
 "vulnerability":("脆弱性","zeijakusei"),"firewall":("ファイアウォール","faiauōru"),"authentication":("認証","ninshō"),"breach":("情報漏えい","jōhō rōei"),
 "patch":("パッチ","patchi"),"malware":("マルウェア","maruwea"),"permission":("権限","kengen"),"server":("サーバー","sābā"),
 "instance":("インスタンス","insutansu"),"region":("リージョン","rījon"),"scale":("スケール","sukēru"),"storage":("ストレージ","sutorēji"),
 "bandwidth":("帯域幅","taiikihaba"),"provision":("プロビジョニング","purobijoningu"),"cluster":("クラスター","kurasutā"),"button":("ボタン","botan"),
 "layout":("レイアウト","reiauto"),"responsive":("レスポンシブ","resuponshibu"),"component":("コンポーネント","konpōnento"),"render":("描画","byōga"),
 "style":("スタイル","sutairu"),"form":("フォーム","fōmu"),"dropdown":("プルダウン","purudaun"),"animation":("アニメーション","animēshon"),
 "breakpoint":("ブレークポイント","burēku pointo"),"performance":("パフォーマンス","pafōmansu"),"optimize":("最適化","saitekika"),"bottleneck":("ボトルネック","botoru nekku"),
 "cache":("キャッシュ","kyasshu"),"memory":("メモリ","memori"),"throughput":("スループット","surūputto"),"profiling":("プロファイリング","purofairingu"),
 "log":("ログ","rogu"),"alert":("アラート","arāto"),"monitor":("監視","kanshi"),"dashboard":("ダッシュボード","dasshubōdo"),
 "metric":("メトリクス","metorikusu"),"threshold":("しきい値","shikiichi"),"trace":("トレース","torēsu"),"error":("エラー","erā"),
 "warning":("警告","keikoku"),"uptime":("稼働時間","kadō jikan"),"container":("コンテナ","kontena"),"image":("イメージ","imēji"),
 "dockerfile":("Dockerfile","dokkā fairu"),"volume":("ボリューム","boryūmu"),"port":("ポート","pōto"),"registry":("レジストリ","rejisutori"),
 "tag":("タグ","tagu"),"compose":("Compose","konpōzu"),"pipeline":("パイプライン","paipurain"),"stage":("ステージ","sutēji"),
 "artifact":("成果物","seikabutsu"),"trigger":("トリガー","torigā"),"workflow":("ワークフロー","wāku furō"),"story":("ストーリー","sutōrī"),
 "retrospective":("振り返り","furikaeri"),"velocity":("ベロシティ","beroshiti"),"ticket":("チケット","chiketto"),"onboarding":("オンボーディング","onbōdingu"),
 "mentor":("メンター","mentā"),"setup":("環境構築","kankyō kōchiku"),"access":("アクセス権","akusesu ken"),"documentation":("ドキュメント","dokyumento"),
 "orientation":("オリエンテーション","orientēshon"),"checklist":("チェックリスト","chekku risuto"),"credential":("認証情報","ninshō jōhō"),"guideline":("ガイドライン","gaidorain"),
 "spec":("仕様書","shiyōsho"),"readme":("README","rīdomī"),"guide":("手順書","tejunsho"),"example":("例","rei"),
 "reference":("リファレンス","rifarensu"),"section":("セクション","sekushon"),"diagram":("図","zu"),"changelog":("変更履歴","henkō rireki"),
 "architecture":("アーキテクチャ","ākitekucha"),"design":("設計","sekkei"),"module":("モジュール","mojūru"),"layer":("レイヤー","reiyā"),
 "interface":("インターフェース","intāfēsu"),"pattern":("パターン","patān"),"scalability":("スケーラビリティ","sukērabiriti"),"coupling":("結合度","ketsugōdo"),
 "boundary":("境界","kyōkai"),"service":("サービス","sābisu"),"gateway":("ゲートウェイ","gētowei"),"contract":("契約","keiyaku"),
 "retry":("リトライ","ritorai"),"discovery":("ディスカバリ","disukabari"),"decouple":("疎結合にする","soketsugō ni suru"),"queue":("キュー","kyū"),
 "message":("メッセージ","messēji"),"event":("イベント","ibento"),"producer":("プロデューサー","purodyūsā"),"consumer":("コンシューマー","konshūmā"),
 "topic":("トピック","topikku"),"subscribe":("購読","kōdoku"),"publish":("発行","hakkō"),"broker":("ブローカー","burōkā"),
 "acknowledge":("確認応答","kakunin ōtō"),"hit":("ヒット","hitto"),"miss":("ミス","misu"),"expire":("期限切れ","kigengire"),
 "invalidate":("無効化","mukōka"),"key":("キー","kī"),"value":("値","atai"),"refresh":("更新","kōshin"),
 "stale":("古い","furui"),"eviction":("追い出し","oidashi"),"login":("ログイン","roguin"),"session":("セッション","sesshon"),
 "role":("ロール","rōru"),"authorize":("認可","ninka"),"grant":("付与","fuyo"),"logout":("ログアウト","roguauto"),
 "verify":("検証","kenshō"),"network":("ネットワーク","nettowāku"),"protocol":("プロトコル","purotokoru"),"packet":("パケット","paketto"),
 "address":("アドレス","adoresu"),"connection":("接続","setsuzoku"),"dns":("DNS","dī enu esu"),"ping":("ping","pingu"),
 "proxy":("プロキシ","purokishi"),"route":("ルート","rūto"),"host":("ホスト","hosuto"),"terminal":("ターミナル","tāminaru"),
 "command":("コマンド","komando"),"directory":("ディレクトリ","direkutori"),"script":("スクリプト","sukuriputo"),"path":("パス","pasu"),
 "process":("プロセス","purosesu"),"shell":("シェル","sheru"),"sudo":("sudo","sūdō"),"grep":("grep","gureppu"),
 "kill":("強制終了","kyōsei shūryō"),"exception":("例外","reigai"),"crash":("クラッシュ","kurasshu"),"inspect":("調べる","shiraberu"),
 "stacktrace":("スタックトレース","sutakku torēsu"),"debugger":("デバッガー","debaggā"),"variable":("変数","hensū"),"input":("入力","nyūryoku"),
 "maintainable":("保守しやすい","hoshu shiyasui"),"complexity":("複雑さ","fukuzatsusa"),"review":("レビュー","rebyū"),"cleanup":("整理","seiri"),
 "smell":("コードの臭い","kōdo no nioi"),"lint":("Lint","rinto"),"data":("データ","dēta"),"report":("レポート","repōto"),
 "chart":("グラフ","gurafu"),"filter":("フィルター","firutā"),"aggregate":("集計","shūkei"),"column":("列","retsu"),
 "row":("行","gyō"),"insight":("気づき","kizuki"),"trend":("傾向","keikō"),"model":("モデル","moderu"),
 "training":("学習","gakushū"),"feature":("特徴量","tokuchōryō"),"predict":("予測","yosoku"),"accuracy":("精度","seido"),
 "label":("ラベル","raberu"),"overfitting":("過学習","kagakushū"),"algorithm":("アルゴリズム","arugorizumu"),"inference":("推論","suiron"),
 "email":("メール","mēru"),"subject":("件名","kenmei"),"attachment":("添付ファイル","tenpu fairu"),"reply":("返信","henshin"),
 "forward":("転送","tensō"),"recipient":("宛先","atesaki"),"draft":("下書き","shitagaki"),"followup":("フォロー","forō"),
 "regards":("よろしくお願いします","yoroshiku onegaishimasu"),"channel":("チャンネル","channeru"),"mention":("メンション","menshon"),"thread":("スレッド","sureddo"),
 "emoji":("絵文字","emoji"),"status":("ステータス","sutētasu"),"notification":("通知","tsūchi"),"dm":("DM","dī emu"),
 "interview":("面接","mensetsu"),"resume":("履歴書","rirekisho"),"experience":("経験","keiken"),"skill":("スキル","sukiru"),
 "position":("ポジション","pojishon"),"candidate":("候補者","kōhosha"),"offer":("内定","naitei"),"salary":("給与","kyūyo"),
 "hire":("採用","saiyō"),"portfolio":("ポートフォリオ","pōtoforio"),"leave":("休暇","kyūka"),"vacation":("休暇","kyūka"),
 "sick":("病欠","byōketsu"),"holiday":("祝日","shukujitsu"),"timesheet":("勤怠表","kintaihyō"),"remote":("リモートワーク","rimōto wāku"),
 "absence":("欠勤","kekkin"),"cover":("代わりに対応する","kawari ni taiō suru"),"goal":("目標","mokuhyō"),"strength":("強み","tsuyomi"),
 "improvement":("改善点","kaizenten"),"rating":("評価","hyōka"),"progress":("進捗","shinchoku"),"expectation":("期待","kitai"),
 "promotion":("昇進","shōshin"),"achievement":("成果","seika"),"customer":("顧客","kokyaku"),"refund":("返金","henkin"),
 "complaint":("クレーム","kurēmu"),"satisfaction":("満足度","manzokudo"),"support":("サポート","sapōto"),"apologize":("謝罪する","shazai suru"),
}
