# -*- coding: utf-8 -*-
# v4.1 — 8 chặng IT làm giàu (nối cuối, xem gen_data.py)
# Mỗi chặng: vocab[10] (t,ipa,pos,vi,ex,exVi[,ja,romaji]), phrases[8] (en,vi,note),
# dialogues[5] (them,[(t,good,fb)x3]) — đáp án đúng đứng đầu, gen_data.py tự xáo,
# listen[6]: 4 câu ngắn + 2 đoạn 2–3 câu (3 ô trống).
EXTRA2 = [
 {
  "title": "Làm việc với khách Nhật & BrSE",
  "vocab": [
   ("offshore", "/ˌɔːfˈʃɔːr/", "adj", "(đội) gia công phần mềm ở nước ngoài cho khách", "We are the <b>offshore</b> team in Da Nang.", "Bọn mình là đội offshore ở Đà Nẵng.", "オフショア", "ofushoa"),
   ("counterpart", "/ˈkaʊntərpɑːrt/", "n", "người giữ vai trò tương ứng ở phía bên kia", "My <b>counterpart</b> in Tokyo is the project leader.", "Người phụ trách tương ứng với mình ở Tokyo là trưởng dự án."),
   ("contact person", "/ˈkɑːntækt ˌpɜːrsn/", "n", "người đầu mối liên lạc", "Who is the <b>contact person</b> on the client side?", "Ai là đầu mối liên lạc phía khách?", "窓口", "madoguchi"),
   ("status report", "/ˈsteɪtəs rɪˌpɔːrt/", "n", "báo cáo tiến độ", "I send a <b>status report</b> every Friday.", "Mình gửi báo cáo tiến độ mỗi thứ Sáu.", "進捗報告", "shinchoku hōkoku"),
   ("confirmation", "/ˌkɑːnfərˈmeɪʃn/", "n", "sự xác nhận", "We are waiting for the client's <b>confirmation</b>.", "Bọn mình đang chờ khách xác nhận.", "確認", "kakunin"),
   ("misunderstanding", "/ˌmɪsʌndərˈstændɪŋ/", "n", "sự hiểu lầm, hiểu khác nhau", "Let's write it down to avoid any <b>misunderstanding</b>.", "Ghi lại ra giấy để tránh hiểu lầm nhé.", "認識のずれ", "ninshiki no zure"),
   ("interpreter", "/ɪnˈtɜːrprɪtər/", "n", "phiên dịch viên", "The <b>interpreter</b> will join the meeting.", "Phiên dịch sẽ vào họp cùng.", "通訳", "tsūyaku"),
   ("nuance", "/ˈnuːɑːns/", "n", "sắc thái nghĩa", "The Japanese <b>nuance</b> is hard to translate.", "Sắc thái tiếng Nhật khó dịch.", "ニュアンス", "nyuansu"),
   ("time difference", "/ˈtaɪm ˌdɪfrəns/", "n", "chênh lệch múi giờ", "The <b>time difference</b> with Tokyo is two hours.", "Tokyo lệch múi giờ với mình hai tiếng.", "時差", "jisa"),
   ("polite", "/pəˈlaɪt/", "adj", "lịch sự", "Please keep the email short and <b>polite</b>.", "Viết email ngắn gọn và lịch sự nhé."),
  ],
  "phrases": [
   ("Let me confirm my understanding.", "Cho mình xác nhận lại cách hiểu của mình.", "câu mở đầu rất hay dùng khi làm BrSE"),
   ("I'll check with the team and get back to you tomorrow.", "Mình sẽ hỏi lại team và phản hồi anh/chị vào ngày mai.", ""),
   ("Sorry for the late reply.", "Xin lỗi vì trả lời muộn.", "gần với お返事が遅くなり申し訳ありません"),
   ("Could you share the documents in advance?", "Anh/chị gửi trước tài liệu giúp được không?", "in advance = trước (thời điểm họp)"),
   ("I'd like to report our progress this week.", "Mình xin báo cáo tiến độ tuần này.", ""),
   ("We found a small issue, but it won't affect the schedule.", "Bọn mình phát hiện một vấn đề nhỏ, nhưng không ảnh hưởng tiến độ.", "báo tin xấu kèm mức ảnh hưởng"),
   ("Please let me explain the background first.", "Cho mình giải thích bối cảnh trước nhé.", ""),
   ("Thank you for your patience.", "Cảm ơn anh/chị đã kiên nhẫn chờ.", "lịch sự hơn 'Sorry for waiting'"),
  ],
  "dialogues": [
   ("The client wants to change the deadline. Can you tell the team?", [
     ("Sure. I'll explain it to the team and share the new plan today.", True, "Nhận việc + nói rõ khi nào chia sẻ."),
     ("Yes, I will tell them yesterday.", False, "Sai thì: 'will' không đi với 'yesterday' — I'll tell them today."),
     ("OK, but the deadline change is the client's fault.", False, "Đổ lỗi cho khách, không chuyên nghiệp.")]),
   ("Did the client confirm the screen layout?", [
     ("Not yet. I sent a reminder this morning.", True, "Trung thực + đã làm gì để nhắc."),
     ("Yes, I think they confirm maybe.", False, "Đoán mò và sai thì: they confirmed."),
     ("Client no answer me.", False, "Nên nói: The client hasn't replied yet.")]),
   ("Can you join the call with the Tokyo team at 8 a.m.?", [
     ("Sure. That's 10 a.m. in Tokyo, right?", True, "Nhận lời + xác nhận múi giờ cẩn thận."),
     ("8 a.m. is too early, so no.", False, "Từ chối cộc, không đề xuất giờ khác."),
     ("Yes, I can joining.", False, "Sau 'can' dùng nguyên mẫu: I can join.")]),
   ("The client says our email was a bit rude.", [
     ("I'm sorry. I'll rewrite it more politely.", True, "Nhận lỗi + cách sửa."),
     ("It's not rude. They don't understand English.", False, "Phòng thủ, đổ lỗi cho khách."),
     ("Sorry, I rewrite it now more polite.", False, "Thiếu 'will' và 'polite' phải thành trạng từ: I'll rewrite it more politely.")]),
   ("Do you understand the client's comment?", [
     ("Mostly, but I'm not sure about the nuance. Let me ask.", True, "Thành thật chỗ chưa chắc + hỏi lại."),
     ("Yes, yes, no problem.", False, "Gật đại — lỗi hay gặp, dễ làm sai yêu cầu."),
     ("I understand all, not need ask.", False, "Sai ngữ pháp: I understand everything. I don't need to ask.")]),
  ],
  "listen": [
   ("Let me confirm my understanding of the new schedule", ["confirm", "schedule"], "xác nhận lại"),
   ("The interpreter will join the meeting tomorrow", ["interpreter"], "người phiên dịch"),
   ("I send a status report to the client every Friday", ["status", "report"], "báo cáo tiến độ"),
   ("The time difference with Tokyo is two hours", ["difference", "hours"], "múi giờ"),
   ("Good morning, Sato-san. Here is our status report for this week. We finished the login screen, and we will start testing on Monday.", ["status", "finished", "testing"], "báo cáo với khách Nhật"),
   ("We found a small issue in the search function. It will not affect the schedule. I will send the details by email.", ["issue", "affect", "details"], "báo tin xấu nhẹ nhàng"),
  ],
 },
 {
  "title": "Yêu cầu, spec & Q&A với khách",
  "vocab": [
   ("ambiguous", "/æmˈbɪɡjuəs/", "adj", "mơ hồ, hiểu được nhiều cách", "This sentence in the spec is <b>ambiguous</b>.", "Câu này trong spec mơ hồ quá.", "曖昧", "aimai"),
   ("assumption", "/əˈsʌmpʃn/", "n", "giả định", "Our <b>assumption</b> is that users log in first.", "Bọn mình giả định là người dùng đăng nhập trước.", "前提", "zentei"),
   ("use case", "/ˈjuːs keɪs/", "n", "tình huống sử dụng", "Can you describe the main <b>use case</b>?", "Anh/chị mô tả tình huống sử dụng chính được không?", "ユースケース", "yūsu kēsu"),
   ("acceptance criteria", "/əkˈseptəns kraɪˌtɪriə/", "n", "tiêu chí nghiệm thu", "Let's agree on the <b>acceptance criteria</b> first.", "Mình thống nhất tiêu chí nghiệm thu trước đã.", "受け入れ基準", "ukeire kijun"),
   ("change request", "/ˈtʃeɪndʒ rɪˌkwest/", "n", "yêu cầu thay đổi (sau khi đã chốt)", "This is a <b>change request</b>, so we need a new estimate.", "Đây là yêu cầu thay đổi, nên cần ước lượng lại.", "仕様変更", "shiyō henkō"),
   ("basic design", "/ˌbeɪsɪk dɪˈzaɪn/", "n", "thiết kế cơ bản", "The <b>basic design</b> document is almost done.", "Tài liệu thiết kế cơ bản sắp xong.", "基本設計", "kihon sekkei"),
   ("detailed design", "/ˌdiːteɪld dɪˈzaɪn/", "n", "thiết kế chi tiết", "We write the <b>detailed design</b> before coding.", "Bọn mình viết thiết kế chi tiết trước khi code.", "詳細設計", "shōsai sekkei"),
   ("out of scope", "/ˌaʊt əv ˈskoʊp/", "phr", "ngoài phạm vi", "Sorry, this feature is <b>out of scope</b>.", "Xin lỗi, tính năng này nằm ngoài phạm vi.", "対象外", "taishōgai"),
   ("Q&A sheet", "/ˌkjuː ən ˈeɪ ʃiːt/", "n", "bảng hỏi đáp với khách", "I added three questions to the <b>Q&A sheet</b>.", "Mình đã thêm ba câu hỏi vào bảng Q&A.", "QA表", "kyūē hyō"),
   ("business rule", "/ˈbɪznəs ruːl/", "n", "quy tắc nghiệp vụ", "This <b>business rule</b> is only for VIP customers.", "Quy tắc nghiệp vụ này chỉ áp dụng cho khách VIP."),
  ],
  "phrases": [
   ("I have a question about the spec on page 5.", "Mình có câu hỏi về spec ở trang 5.", "nói rõ vị trí giúp khách trả lời nhanh"),
   ("Just to confirm, is this field required?", "Xác nhận lại, trường này có bắt buộc không?", ""),
   ("Our understanding is that only admins can delete data.", "Bọn mình hiểu là chỉ admin mới được xoá dữ liệu.", "nêu cách hiểu để khách chỉ cần trả lời Yes/No"),
   ("Could you give us an example?", "Anh/chị cho bọn mình một ví dụ được không?", ""),
   ("This looks like a change request, not a bug.", "Cái này có vẻ là yêu cầu thay đổi, không phải lỗi.", ""),
   ("I've added this question to the Q&A sheet.", "Mình đã thêm câu hỏi này vào bảng Q&A.", ""),
   ("What should happen if the user enters a wrong date?", "Nếu người dùng nhập sai ngày thì hệ thống xử lý thế nào?", ""),
   ("Could you reply by Wednesday so we can keep the schedule?", "Anh/chị trả lời trước thứ Tư giúp để bọn mình giữ đúng tiến độ nhé.", "đưa hạn + lý do"),
  ],
  "dialogues": [
   ("The spec says 'show recent orders'. Is it clear?", [
     ("Not really. How many days does 'recent' mean?", True, "Chỉ đúng chỗ mơ hồ và hỏi cụ thể."),
     ("Yes, it's clear. We just show some orders.", False, "Tự đoán — dễ làm sai ý khách."),
     ("Recent is how much? I no understand.", False, "Sai ngữ pháp: I don't understand what 'recent' means.")]),
   ("The client wants to add CSV export. Can we do it this sprint?", [
     ("It's out of scope for now. Let's handle it as a change request.", True, "Giữ phạm vi, đưa đúng quy trình."),
     ("Yes, sure. We can do everything.", False, "Hứa đại, dễ trễ tiến độ."),
     ("Can not, scope is full already.", False, "Cụt và thiếu chủ ngữ: We can't. The scope is already full.")]),
   ("Did the client answer our questions?", [
     ("They answered four of them. Two are still open.", True, "Nêu số cụ thể, rõ trạng thái."),
     ("They answer some, some not.", False, "Sai thì và mơ hồ: They answered some of them."),
     ("I don't check yet.", False, "Sai thì: I haven't checked yet.")]),
   ("Why do you need an example from the client?", [
     ("Because the rule is ambiguous, and an example will help us avoid mistakes.", True, "Giải thích lý do rõ ràng."),
     ("Because I want.", False, "Không có lý do, nghe cộc."),
     ("Because rule is ambiguous so we need example.", False, "Thiếu mạo từ 'the', 'an' và thừa 'so' sau 'because'.")]),
   ("Can you start coding before the basic design is approved?", [
     ("I can start the parts that are already fixed, but not the rest.", True, "Đề xuất hợp lý, có giới hạn."),
     ("Yes, I start coding all now.", False, "Thiếu 'will'; code hết khi chưa duyệt là rủi ro."),
     ("No, I cannot do nothing.", False, "Phủ định kép: I can't do anything.")]),
  ],
  "listen": [
   ("This sentence in the spec is ambiguous", ["sentence", "ambiguous"], "chỗ mơ hồ"),
   ("I added three questions to the Q&A sheet", ["questions", "sheet"], "bảng hỏi đáp"),
   ("Is this field required or optional", ["required", "optional"], "xác nhận trường dữ liệu"),
   ("This feature is out of scope for now", ["feature", "scope"], "phạm vi"),
   ("Our understanding is that only admins can delete orders. Is that correct? If not, please give us an example.", ["understanding", "admins", "example"], "hỏi đáp spec"),
   ("The client sent a change request yesterday. We need a new estimate before we start.", ["change", "estimate", "start"], "yêu cầu thay đổi"),
  ],
 },
 {
  "title": "Ước lượng & báo giá dự án outsource",
  "vocab": [
   ("quotation", "/kwoʊˈteɪʃn/", "n", "bảng báo giá", "We will send the <b>quotation</b> on Monday.", "Thứ Hai bọn mình sẽ gửi báo giá.", "見積書", "mitsumorisho"),
   ("man-month", "/ˌmæn ˈmʌnθ/", "n", "người-tháng (công một người làm trong một tháng)", "This project needs about ten <b>man-months</b>.", "Dự án này cần khoảng mười người-tháng.", "人月", "ningetsu"),
   ("effort", "/ˈefərt/", "n", "khối lượng công (giờ công)", "The testing <b>effort</b> is bigger than we thought.", "Khối lượng công cho test lớn hơn bọn mình nghĩ.", "工数", "kōsū"),
   ("buffer", "/ˈbʌfər/", "n", "phần dự phòng (thời gian, công)", "Let's add a 15% <b>buffer</b> for risks.", "Thêm 15% dự phòng cho rủi ro nhé.", "バッファ", "baffa"),
   ("breakdown", "/ˈbreɪkdaʊn/", "n", "bảng chia nhỏ chi tiết", "The client wants a <b>breakdown</b> by feature.", "Khách muốn xem bảng chia nhỏ theo từng tính năng.", "内訳", "uchiwake"),
   ("rough estimate", "/ˌrʌf ˈestɪmət/", "n", "ước lượng sơ bộ", "This is only a <b>rough estimate</b>.", "Đây chỉ là ước lượng sơ bộ thôi.", "概算", "gaisan"),
   ("budget", "/ˈbʌdʒɪt/", "n", "ngân sách", "The client has a limited <b>budget</b>.", "Khách có ngân sách hạn chế.", "予算", "yosan"),
   ("risk", "/rɪsk/", "n", "rủi ro", "The biggest <b>risk</b> is the old Oracle database.", "Rủi ro lớn nhất là database Oracle cũ.", "リスク", "risuku"),
   ("fixed price", "/ˌfɪkst ˈpraɪs/", "n", "giá trọn gói, cố định", "The client wants a <b>fixed price</b> for the whole project.", "Khách muốn giá trọn gói cho cả dự án."),
   ("billable", "/ˈbɪləbl/", "adj", "được tính tiền cho khách", "Meeting time is also <b>billable</b>.", "Thời gian họp cũng được tính tiền."),
  ],
  "phrases": [
   ("This is a rough estimate. We'll update it after the Q&A.", "Đây là ước lượng sơ bộ. Bọn mình sẽ cập nhật sau khi hỏi đáp xong.", ""),
   ("The estimate includes design, coding, and testing.", "Ước lượng đã bao gồm thiết kế, code và test.", ""),
   ("We added a buffer for unclear requirements.", "Bọn mình thêm dự phòng cho các yêu cầu chưa rõ.", ""),
   ("If the scope changes, the price will change too.", "Nếu phạm vi thay đổi thì giá cũng thay đổi.", ""),
   ("Could you tell us your budget range?", "Anh/chị cho biết khoảng ngân sách được không?", ""),
   ("We can reduce the cost if we remove this feature.", "Nếu bỏ tính năng này thì bọn mình giảm được chi phí.", "đưa lựa chọn thay vì chỉ nói 'không'"),
   ("I'll send a breakdown by feature tomorrow.", "Mai mình gửi bảng chia nhỏ theo tính năng.", ""),
   ("This estimate is based on the current spec.", "Ước lượng này dựa trên spec hiện tại.", "nêu điều kiện để tránh tranh cãi sau này"),
  ],
  "dialogues": [
   ("The client says our quotation is too high.", [
     ("I see. We can remove some features or split the project into phases.", True, "Đưa lựa chọn thay vì chỉ giảm giá."),
     ("OK, we reduce 30% now.", False, "Giảm giá ngay không phân tích; thiếu 'can/will'."),
     ("Our price is not high. They are wrong.", False, "Cãi khách, không giải quyết được gì.")]),
   ("How did you get twelve man-months?", [
     ("I estimated each feature, then added a 15% buffer.", True, "Giải thích cách tính rõ ràng."),
     ("I think about it and feel twelve.", False, "Cảm tính, sai thì: I thought about it."),
     ("Twelve because big project.", False, "Không thành câu: Because it's a big project — và vẫn thiếu cách tính.")]),
   ("Can you give me a rough estimate today?", [
     ("Yes, but it may change after we see the full spec.", True, "Đưa được con số + nêu điều kiện."),
     ("Yes, and it will be 100% correct.", False, "Hứa ước lượng sơ bộ 'chính xác tuyệt đối' là rủi ro."),
     ("Today can, but not sure correct.", False, "Thiếu chủ ngữ: I can, but it may not be accurate.")]),
   ("Why is the testing effort so big?", [
     ("Because we also need to test with the old Oracle data.", True, "Nêu lý do kỹ thuật cụ thể."),
     ("Because testing is many work.", False, "'work' không đếm được: a lot of work."),
     ("I don't know, the team said so.", False, "Không nắm được ước lượng của chính mình.")]),
   ("Is meeting time billable in this contract?", [
     ("Yes, it's included in the monthly rate.", True, "Trả lời rõ, dựa vào hợp đồng."),
     ("Yes, it is include.", False, "Thiếu '-d': it's included."),
     ("Maybe yes, maybe no.", False, "Mơ hồ, khách sẽ mất tin tưởng.")]),
  ],
  "listen": [
   ("This is only a rough estimate", ["rough", "estimate"], "ước lượng sơ bộ"),
   ("We added a buffer for unclear requirements", ["buffer", "unclear"], "dự phòng"),
   ("We will send the quotation on Monday", ["quotation", "Monday"], "gửi báo giá"),
   ("The client has a limited budget this year", ["limited", "budget"], "ngân sách"),
   ("Our estimate is about ten man-months. It includes design, coding, and testing. We also added a small buffer for risks.", ["includes", "coding", "buffer"], "giải thích báo giá"),
   ("If you remove the report feature, we can reduce the cost. The team can then finish one month earlier.", ["remove", "reduce", "earlier"], "đề xuất giảm chi phí"),
  ],
 },
 {
  "title": "QA & kiểm thử thủ công",
  "vocab": [
   ("test case", "/ˈtest keɪs/", "n", "ca kiểm thử", "I wrote twenty <b>test cases</b> for the login screen.", "Mình viết hai mươi test case cho màn login.", "テストケース", "tesuto kēsu"),
   ("precondition", "/ˌpriːkənˈdɪʃn/", "n", "điều kiện cần có trước khi test", "The <b>precondition</b> is that the user is logged in.", "Điều kiện trước là người dùng đã đăng nhập.", "前提条件", "zentei jōken"),
   ("expected result", "/ɪkˌspektɪd rɪˈzʌlt/", "n", "kết quả mong đợi", "The <b>expected result</b> is an error message.", "Kết quả mong đợi là hiện thông báo lỗi.", "期待結果", "kitai kekka"),
   ("actual result", "/ˌæktʃuəl rɪˈzʌlt/", "n", "kết quả thực tế", "The <b>actual result</b> is a blank page.", "Kết quả thực tế là trang trắng."),
   ("test data", "/ˈtest ˌdeɪtə/", "n", "dữ liệu để test", "Please prepare <b>test data</b> for 100 users.", "Chuẩn bị dữ liệu test cho 100 người dùng nhé.", "テストデータ", "tesuto dēta"),
   ("defect", "/ˈdiːfekt/", "n", "lỗi, khiếm khuyết (trang trọng hơn 'bug')", "QA found five <b>defects</b> this week.", "Tuần này QA tìm ra năm lỗi.", "不具合", "fuguai"),
   ("bug report", "/ˈbʌɡ rɪˌpɔːrt/", "n", "báo cáo lỗi", "A good <b>bug report</b> has clear steps.", "Báo cáo lỗi tốt phải có các bước rõ ràng.", "バグ票", "bagu hyō"),
   ("retest", "/ˌriːˈtest/", "v", "kiểm thử lại", "Can you <b>retest</b> it after the fix?", "Sửa xong bạn test lại giúp nhé?", "再テスト", "sai tesuto"),
   ("screenshot", "/ˈskriːnʃɑːt/", "n", "ảnh chụp màn hình", "Please attach a <b>screenshot</b> to the ticket.", "Đính kèm ảnh chụp màn hình vào ticket nhé.", "スクリーンショット", "sukurīnshotto"),
   ("smoke test", "/ˈsmoʊk test/", "n", "test nhanh các chức năng chính", "We run a <b>smoke test</b> after every deploy.", "Sau mỗi lần deploy bọn mình chạy smoke test.", "スモークテスト", "sumōku tesuto"),
  ],
  "phrases": [
   ("Steps to reproduce: open the app, then tap Save.", "Các bước tái hiện: mở app, rồi bấm Save.", "mẫu mở đầu bug report"),
   ("The expected result is different from the actual result.", "Kết quả mong đợi khác với kết quả thực tế.", ""),
   ("It happens every time, not randomly.", "Lỗi xảy ra mọi lần, không phải ngẫu nhiên.", "nói rõ tần suất"),
   ("I've attached a screenshot and the log.", "Mình đã đính kèm ảnh chụp màn hình và log.", ""),
   ("The fix is on staging. Could you retest it?", "Bản sửa đã lên staging. Bạn test lại giúp được không?", ""),
   ("I retested it and it works now. I'll close the ticket.", "Mình test lại rồi, giờ chạy ổn. Mình đóng ticket nhé.", ""),
   ("Is this a defect or a spec change?", "Cái này là lỗi hay là thay đổi spec?", ""),
   ("Which browser and version did you use?", "Bạn dùng trình duyệt và phiên bản nào?", ""),
  ],
  "dialogues": [
   ("I found a bug. What should I write in the report?", [
     ("Write the steps, the expected result, and the actual result.", True, "Đủ ba phần chính của bug report."),
     ("Just write 'it doesn't work'.", False, "Quá chung chung, dev không sửa được."),
     ("Write all thing you see.", False, "'all thing' sai: everything you see — và vẫn thiếu cấu trúc.")]),
   ("Does the bug happen every time?", [
     ("No, about one in five times, only on slow networks.", True, "Nói rõ tần suất và điều kiện."),
     ("Sometimes yes, sometimes no.", False, "Mơ hồ, không giúp tái hiện lỗi."),
     ("It happen sometime.", False, "Thiếu 's': It happens sometimes.")]),
   ("The fix is on staging now.", [
     ("Thanks. I'll retest it this afternoon.", True, "Cảm ơn + hẹn thời gian test lại."),
     ("OK, I retested it tomorrow.", False, "Sai thì: quá khứ không đi với 'tomorrow' — I'll retest it tomorrow."),
     ("Fixed already? I don't believe it.", False, "Nghe thiếu tin tưởng, thiếu lịch sự.")]),
   ("Why did you mark this as high severity?", [
     ("Because users can't finish the payment.", True, "Lý do gắn với ảnh hưởng đến người dùng."),
     ("Because I feel it's important.", False, "Cảm tính, không có bằng chứng."),
     ("Because users cannot payment.", False, "'payment' là danh từ: users can't pay.")]),
   ("Can you add some test data for the report screen?", [
     ("Sure. How many records do you need?", True, "Nhận việc + hỏi chi tiết cần thiết."),
     ("Sure, I add many.", False, "Thiếu 'will' và quá mơ hồ."),
     ("Test data is not my job.", False, "Từ chối cứng, thiếu tinh thần hợp tác.")]),
  ],
  "listen": [
   ("I wrote twenty test cases for the login screen", ["test", "cases"], "ca kiểm thử"),
   ("Please attach a screenshot to the ticket", ["attach", "screenshot"], "đính kèm"),
   ("The fix is on staging, so please retest it", ["staging", "retest"], "test lại"),
   ("QA found five defects this week", ["defects"], "số lỗi"),
   ("The steps to reproduce are simple. Open the order page and tap Save twice. The expected result is one order, but the app creates two.", ["reproduce", "twice", "creates"], "đọc bug report"),
   ("I retested the payment bug on staging. It works now, so I will close the ticket.", ["retested", "works", "close"], "báo kết quả test lại"),
  ],
 },
 {
  "title": "On-call & sự cố production",
  "vocab": [
   ("on-call", "/ˌɑːn ˈkɔːl/", "adj", "đang trực xử lý sự cố (kể cả ngoài giờ)", "I'm <b>on-call</b> this weekend.", "Cuối tuần này mình trực.", "オンコール", "onkōru"),
   ("incident", "/ˈɪnsɪdənt/", "n", "sự cố", "We had an <b>incident</b> on production last night.", "Tối qua production có sự cố.", "インシデント", "inshidento"),
   ("postmortem", "/ˌpoʊstˈmɔːrtəm/", "n", "buổi/bản phân tích sau sự cố", "We'll write a <b>postmortem</b> tomorrow.", "Mai bọn mình viết bản phân tích sự cố."),
   ("runbook", "/ˈrʌnbʊk/", "n", "sổ tay các bước xử lý", "Follow the <b>runbook</b> to restart the service.", "Làm theo sổ tay để khởi động lại service.", "手順書", "tejunsho"),
   ("recover", "/rɪˈkʌvər/", "v", "khôi phục, chạy lại bình thường", "The system <b>recovered</b> after ten minutes.", "Hệ thống chạy lại bình thường sau mười phút.", "復旧", "fukkyū"),
   ("spike", "/spaɪk/", "n", "sự tăng vọt đột ngột", "We saw a <b>spike</b> in errors at 2 a.m.", "Lúc 2 giờ sáng số lỗi tăng vọt."),
   ("blameless", "/ˈbleɪmləs/", "adj", "không đổ lỗi cho cá nhân", "Our postmortems are <b>blameless</b>.", "Các buổi phân tích sự cố của bọn mình không đổ lỗi cá nhân."),
   ("handover", "/ˈhændoʊvər/", "n", "sự bàn giao", "I'll do the <b>handover</b> before my shift ends.", "Mình sẽ bàn giao trước khi hết ca.", "引き継ぎ", "hikitsugi"),
   ("preventive action", "/prɪˌventɪv ˈækʃn/", "n", "biện pháp phòng ngừa tái phát", "We agreed on two <b>preventive actions</b>.", "Bọn mình thống nhất hai biện pháp phòng ngừa tái phát.", "再発防止策", "saihatsu bōshisaku"),
   ("affected", "/əˈfektɪd/", "adj", "bị ảnh hưởng", "About 200 users were <b>affected</b>.", "Khoảng 200 người dùng bị ảnh hưởng."),
  ],
  "phrases": [
   ("I'm looking into it now. Next update in 15 minutes.", "Mình đang xem. 15 phút nữa cập nhật tiếp.", "báo trạng thái đều đặn khi có sự cố"),
   ("The service is back to normal.", "Dịch vụ đã hoạt động bình thường trở lại.", ""),
   ("About 5% of users were affected.", "Khoảng 5% người dùng bị ảnh hưởng.", ""),
   ("I followed the runbook and restarted the batch job.", "Mình làm theo sổ tay và chạy lại batch job.", ""),
   ("Let's focus on recovery first, then find the root cause.", "Ưu tiên khôi phục trước, rồi mới tìm nguyên nhân gốc.", ""),
   ("The error rate went back down at 3:10.", "Tỉ lệ lỗi giảm trở lại lúc 3 giờ 10.", ""),
   ("This postmortem is blameless. We focus on the process.", "Buổi phân tích này không đổ lỗi. Mình tập trung vào quy trình.", ""),
   ("What can we do to stop this from happening again?", "Mình làm gì để chuyện này không lặp lại?", "hỏi biện pháp phòng ngừa"),
  ],
  "dialogues": [
   ("You're on-call. The alert says the API is slow. What's your first step?", [
     ("I'll check the dashboard and post an update in the incident channel.", True, "Kiểm tra + báo cho mọi người cùng biết."),
     ("I'll wait until morning. Maybe it recovers.", False, "Đang trực mà chờ đến sáng là sai."),
     ("I fix the code on production directly.", False, "Sửa thẳng trên production rất rủi ro; và thiếu 'will'.")]),
   ("How many users were affected?", [
     ("About 300 users couldn't log in for 20 minutes.", True, "Có số người, hiện tượng và thời gian."),
     ("Many many users, very serious.", False, "Không có con số cụ thể."),
     ("About 300 users was affected.", False, "Chủ ngữ số nhiều: users were affected.")]),
   ("Is the system stable now?", [
     ("Yes, it recovered at 3:10, and the error rate is normal.", True, "Xác nhận + đưa bằng chứng."),
     ("Yes, it is recover.", False, "Sai: it has recovered / it recovered."),
     ("I think OK. I go to sleep now.", False, "Chưa xác minh đã bỏ đi; thiếu động từ: I think it's OK.")]),
   ("Who caused this incident?", [
     ("Let's not focus on a person. The deploy process had no check for this.", True, "Tinh thần blameless: tìm lỗ hổng quy trình."),
     ("It was Minh. He pushed the bad config.", False, "Đổ lỗi cá nhân — trái với postmortem blameless."),
     ("Not me. I don't know who.", False, "Phòng thủ, không giúp tìm nguyên nhân.")]),
   ("What preventive actions do you suggest?", [
     ("We should add a disk alert and update the runbook.", True, "Đề xuất cụ thể, làm được."),
     ("Be more careful next time.", False, "Chung chung, không phải hành động cụ thể."),
     ("We should to add more alerts.", False, "Sau 'should' không dùng 'to': We should add.")]),
  ],
  "listen": [
   ("I am on-call this weekend", ["on-call", "weekend"], "lịch trực"),
   ("We saw a spike in errors at two in the morning", ["spike", "errors"], "tăng vọt"),
   ("The system recovered after ten minutes", ["recovered", "minutes"], "khôi phục"),
   ("About two hundred users were affected", ["affected"], "ảnh hưởng"),
   ("The API went down at two in the morning. I followed the runbook and restarted the service. It recovered after ten minutes.", ["runbook", "restarted", "recovered"], "báo cáo sự cố"),
   ("This postmortem is blameless. We focus on the process, not on people. Our main preventive action is a new alert.", ["blameless", "process", "alert"], "buổi postmortem"),
  ],
 },
 {
  "title": "Mobile app",
  "vocab": [
   ("device", "/dɪˈvaɪs/", "n", "thiết bị (điện thoại, máy tính bảng)", "The bug only happens on old <b>devices</b>.", "Lỗi chỉ xảy ra trên máy cũ.", "端末", "tanmatsu"),
   ("emulator", "/ˈemjuleɪtər/", "n", "trình giả lập thiết bị", "It works on the <b>emulator</b> but not on my phone.", "Trên trình giả lập thì chạy, trên điện thoại mình thì không.", "エミュレーター", "emyurētā"),
   ("tap", "/tæp/", "v", "chạm (vào màn hình)", "<b>Tap</b> the button twice to see the bug.", "Chạm nút hai lần sẽ thấy lỗi.", "タップ", "tappu"),
   ("swipe", "/swaɪp/", "v", "vuốt", "<b>Swipe</b> left to delete the item.", "Vuốt sang trái để xoá mục.", "スワイプ", "suwaipu"),
   ("landscape", "/ˈlændskeɪp/", "n", "chế độ màn hình ngang", "Videos look better in <b>landscape</b> mode.", "Xem video ở chế độ màn hình ngang thì đẹp hơn.", "横向き", "yokomuki"),
   ("offline mode", "/ˌɔːfˈlaɪn moʊd/", "n", "chế độ không có mạng", "Users can read old messages in <b>offline mode</b>.", "Người dùng xem được tin nhắn cũ khi không có mạng.", "オフラインモード", "ofurain mōdo"),
   ("battery", "/ˈbætəri/", "n", "pin", "This feature uses too much <b>battery</b>.", "Tính năng này tốn pin quá.", "バッテリー", "batterī"),
   ("install", "/ɪnˈstɔːl/", "v", "cài đặt", "Please <b>install</b> the new test build.", "Cài bản build test mới nhé.", "インストール", "insutōru"),
   ("push notification", "/ˌpʊʃ noʊtɪfɪˈkeɪʃn/", "n", "thông báo đẩy", "Users get a <b>push notification</b> when the order ships.", "Người dùng nhận thông báo đẩy khi đơn hàng được gửi đi.", "プッシュ通知", "pusshu tsūchi"),
   ("app store", "/ˈæp stɔːr/", "n", "cửa hàng ứng dụng", "Our app passed the <b>app store</b> review.", "App của mình đã qua vòng duyệt của cửa hàng ứng dụng."),
  ],
  "phrases": [
   ("Which device and OS version are you using?", "Bạn đang dùng máy nào, hệ điều hành phiên bản mấy?", "câu hỏi đầu tiên khi có lỗi mobile"),
   ("It works on the emulator, but not on a real device.", "Trên máy giả lập thì chạy, trên máy thật thì không.", ""),
   ("The app crashes when I rotate the screen.", "App bị crash khi mình xoay màn hình.", ""),
   ("Please install the latest test build.", "Cài bản build test mới nhất nhé.", ""),
   ("The button is too small to tap.", "Nút nhỏ quá, khó chạm.", ""),
   ("We need to support offline mode.", "Mình cần hỗ trợ chế độ không có mạng.", ""),
   ("The app store review usually takes one or two days.", "Vòng duyệt của cửa hàng ứng dụng thường mất một, hai ngày.", ""),
   ("Users can turn off push notifications in settings.", "Người dùng tắt được thông báo đẩy trong phần cài đặt.", ""),
  ],
  "dialogues": [
   ("The app crashes on my phone.", [
     ("Which device and OS version do you have?", True, "Hỏi thông tin cần để tái hiện lỗi."),
     ("It works on my phone, so it's your phone's problem.", False, "Đổ lỗi, không điều tra."),
     ("What phone you use?", False, "Thiếu trợ động từ: What phone do you use?")]),
   ("Did you test it on a real device?", [
     ("Only on the emulator. I'll test it on a real phone today.", True, "Trung thực + kế hoạch tiếp theo."),
     ("Yes, the emulator is same same.", False, "Emulator không thay được máy thật; 'same same' là kiểu nói bồi."),
     ("No, I don't tested yet.", False, "Sai: I haven't tested it yet.")]),
   ("Users say the app uses too much battery.", [
     ("Let me check if the GPS keeps running in the background.", True, "Đưa hướng điều tra cụ thể."),
     ("Battery is the user's problem, not the app's.", False, "Đổ lỗi cho người dùng."),
     ("I will checking the battery.", False, "Sau 'will' dùng nguyên mẫu: I will check.")]),
   ("When can we release it on the app store?", [
     ("If the review goes well, next Tuesday.", True, "Có mốc + nêu điều kiện."),
     ("Tomorrow for sure, no problem.", False, "Hứa chắc chắn dù còn phụ thuộc vòng duyệt."),
     ("When review finish, we release.", False, "Thiếu mạo từ và 's': When the review finishes, we'll release it.")]),
   ("Should we send a push notification for every new message?", [
     ("Maybe not. Too many notifications can annoy users.", True, "Góp ý có lý do từ góc nhìn người dùng."),
     ("Yes, more notification is more good.", False, "Sai so sánh: 'more notifications are better'."),
     ("I don't care. You decide.", False, "Thờ ơ, không đóng góp ý kiến.")]),
  ],
  "listen": [
   ("The bug only happens on old devices", ["happens", "devices"], "lỗi theo thiết bị"),
   ("Swipe left to delete the item", ["swipe", "delete"], "thao tác vuốt"),
   ("Please install the latest test build", ["install", "build"], "cài bản test"),
   ("This feature uses too much battery", ["battery"], "tốn pin"),
   ("It works on the emulator, but it crashes on a real device. I think the problem is the camera permission.", ["emulator", "crashes", "camera"], "báo lỗi mobile"),
   ("The new version passed the app store review. We will release it on Tuesday, and users will get a push notification.", ["passed", "release", "notification"], "thông báo phát hành"),
  ],
 },
 {
  "title": "Sản phẩm, UX & làm việc với designer",
  "vocab": [
   ("wireframe", "/ˈwaɪərfreɪm/", "n", "bản phác khung giao diện", "The designer shared the <b>wireframes</b> for the new screen.", "Designer đã gửi wireframe cho màn hình mới.", "ワイヤーフレーム", "waiyāfurēmu"),
   ("mockup", "/ˈmɑːkʌp/", "n", "bản mẫu giao diện chi tiết", "The <b>mockup</b> shows the final colors.", "Bản mockup có màu sắc cuối cùng.", "モックアップ", "mokkuappu"),
   ("prototype", "/ˈproʊtətaɪp/", "n", "bản thử bấm được", "Let's test the <b>prototype</b> with five users.", "Mình thử prototype với năm người dùng nhé.", "プロトタイプ", "purototaipu"),
   ("user flow", "/ˈjuːzər floʊ/", "n", "luồng thao tác của người dùng", "The <b>user flow</b> for sign-up has too many steps.", "Luồng đăng ký có quá nhiều bước."),
   ("usability", "/ˌjuːzəˈbɪləti/", "n", "tính dễ sử dụng", "We found three <b>usability</b> problems.", "Bọn mình tìm ra ba vấn đề về tính dễ dùng.", "ユーザビリティ", "yūzabiriti"),
   ("persona", "/pərˈsoʊnə/", "n", "chân dung người dùng mẫu", "Our main <b>persona</b> is a busy office worker.", "Chân dung người dùng chính là nhân viên văn phòng bận rộn.", "ペルソナ", "perusona"),
   ("pain point", "/ˈpeɪn pɔɪnt/", "n", "điểm gây khó chịu cho người dùng", "Slow search is the biggest <b>pain point</b>.", "Tìm kiếm chậm là điểm khó chịu lớn nhất."),
   ("spacing", "/ˈspeɪsɪŋ/", "n", "khoảng cách giữa các phần tử", "The <b>spacing</b> here is different from the design.", "Khoảng cách ở đây khác với bản thiết kế.", "余白", "yohaku"),
   ("icon", "/ˈaɪkɑːn/", "n", "biểu tượng", "This <b>icon</b> is not clear to users.", "Người dùng khó hiểu biểu tượng này.", "アイコン", "aikon"),
   ("consistent", "/kənˈsɪstənt/", "adj", "nhất quán", "Let's keep the buttons <b>consistent</b> across all screens.", "Giữ các nút nhất quán trên mọi màn hình nhé."),
  ],
  "phrases": [
   ("The design looks great. I have one small question.", "Thiết kế đẹp lắm. Mình có một câu hỏi nhỏ.", "khen trước, hỏi sau"),
   ("What should this screen show when there's no data?", "Màn hình này hiện gì khi không có dữ liệu?", "trạng thái rỗng hay bị quên trong thiết kế"),
   ("This animation might be hard to build. Can we make it simpler?", "Hiệu ứng này có thể khó làm. Mình làm đơn giản hơn được không?", ""),
   ("Is this spacing 16 or 24 pixels?", "Khoảng cách này là 16 hay 24 pixel?", ""),
   ("Could you export the icons as SVG?", "Bạn xuất các icon ra SVG giúp được không?", ""),
   ("Users found the sign-up flow confusing.", "Người dùng thấy luồng đăng ký khó hiểu.", ""),
   ("Let's check the mockup together before I start coding.", "Mình cùng xem mockup trước khi mình bắt đầu code nhé.", ""),
   ("I'll build a quick prototype so we can test the idea.", "Mình sẽ làm nhanh một prototype để thử ý tưởng.", ""),
  ],
  "dialogues": [
   ("What do you think of the new design?", [
     ("It looks clean. One question: how does it look on small screens?", True, "Khen cụ thể rồi hỏi điểm cần làm rõ."),
     ("It's ugly. Change it.", False, "Chê cộc, không góp ý cụ thể."),
     ("Design is very beautiful but hard for code.", False, "Thiếu mạo từ 'The'; 'hard for code' nên là 'hard to build'.")]),
   ("Your screen doesn't match the mockup.", [
     ("Sorry, I'll fix the spacing and the font size today.", True, "Nhận lỗi + nêu rõ sẽ sửa gì."),
     ("It's almost same. Users won't see.", False, "Coi nhẹ thiết kế; thiếu 'the': almost the same."),
     ("I code follow my feeling.", False, "Sai ngữ pháp và không chuyên nghiệp.")]),
   ("Can you build this animation by Friday?", [
     ("It's hard to finish by Friday. Can we use a simpler version first?", True, "Nêu khó khăn + đề xuất phương án thay thế."),
     ("Yes, no problem.", False, "Hứa đại dù có thể không kịp."),
     ("Animation is difficult, I cannot.", False, "Từ chối ngay, không đề xuất cách khác; câu cụt: I can't do it.")]),
   ("Why do users leave the sign-up page?", [
     ("The user flow has too many steps. That's the main pain point.", True, "Chỉ ra nguyên nhân từ góc nhìn người dùng."),
     ("Because users are lazy.", False, "Đổ lỗi cho người dùng, không giúp cải thiện."),
     ("Because have many step.", False, "Thiếu chủ ngữ và số nhiều: there are too many steps.")]),
   ("Should we test the prototype with real users?", [
     ("Yes. Even five users can show us big problems.", True, "Đồng ý + lý do thực tế."),
     ("No need. I know what users want.", False, "Tự tin mù quáng, bỏ qua người dùng thật."),
     ("Yes, we should testing it.", False, "Sau 'should' dùng nguyên mẫu: we should test it.")]),
  ],
  "listen": [
   ("The designer shared the wireframes for the new screen", ["designer", "wireframes"], "thiết kế mới"),
   ("Slow search is the biggest pain point", ["search", "pain"], "điểm khó chịu"),
   ("Let's test the prototype with five users", ["prototype", "users"], "thử với người dùng"),
   ("The spacing here is different from the design", ["spacing", "different"], "lệch thiết kế"),
   ("I checked the mockup with the designer. The icons are fine, but the spacing on mobile is too small. She will send a new version tomorrow.", ["mockup", "icons", "version"], "trao đổi với designer"),
   ("We tested the prototype with five users. Three of them could not find the search button. We need to make it bigger.", ["tested", "find", "bigger"], "kết quả thử với người dùng"),
  ],
 },
 {
  "title": "Dùng AI & LLM trong công việc",
  "vocab": [
   ("prompt", "/prɑːmpt/", "n", "câu lệnh/yêu cầu gửi cho AI", "Write a clear <b>prompt</b> with examples.", "Viết prompt rõ ràng, có ví dụ.", "プロンプト", "puronputo"),
   ("hallucination", "/həˌluːsɪˈneɪʃn/", "n", "AI bịa ra thông tin sai", "That method doesn't exist. It's a <b>hallucination</b>.", "Hàm đó không có thật. AI bịa ra đấy.", "ハルシネーション", "harushinēshon"),
   ("generate", "/ˈdʒenəreɪt/", "v", "tạo ra, sinh ra", "The AI can <b>generate</b> unit tests for this class.", "AI có thể sinh unit test cho class này.", "生成", "seisei"),
   ("summarize", "/ˈsʌməraɪz/", "v", "tóm tắt", "Can you <b>summarize</b> this long email thread?", "Bạn tóm tắt giúp chuỗi email dài này được không?", "要約", "yōyaku"),
   ("context window", "/ˈkɑːntekst ˌwɪndoʊ/", "n", "giới hạn lượng chữ AI đọc được một lần", "The whole codebase doesn't fit in the <b>context window</b>.", "Cả codebase không vừa giới hạn ngữ cảnh của AI."),
   ("fine-tune", "/ˌfaɪn ˈtuːn/", "v", "tinh chỉnh mô hình bằng dữ liệu riêng", "We don't need to <b>fine-tune</b> the model for this.", "Việc này không cần tinh chỉnh mô hình.", "ファインチューニング", "fain chūningu"),
   ("output", "/ˈaʊtpʊt/", "n", "kết quả đầu ra", "Always review the AI <b>output</b> before you use it.", "Luôn xem lại kết quả AI trả ra trước khi dùng.", "出力", "shutsuryoku"),
   ("confidential", "/ˌkɑːnfɪˈdenʃl/", "adj", "mật, không được tiết lộ", "Don't paste <b>confidential</b> client code into public AI tools.", "Đừng dán code mật của khách vào công cụ AI công khai.", "機密", "kimitsu"),
   ("double-check", "/ˌdʌbl ˈtʃek/", "v", "kiểm tra lại cho chắc", "Please <b>double-check</b> the SQL before you run it on Oracle.", "Kiểm tra lại câu SQL trước khi chạy trên Oracle nhé."),
   ("assistant", "/əˈsɪstənt/", "n", "trợ lý", "I use an AI <b>assistant</b> to create test data.", "Mình dùng trợ lý AI để tạo dữ liệu test.", "アシスタント", "ashisutanto"),
  ],
  "phrases": [
   ("I used AI for the first draft, then I checked it myself.", "Mình dùng AI viết bản nháp đầu, rồi tự kiểm tra lại.", "nói rõ phần nào do AI làm"),
   ("Is it OK to use AI tools on this project?", "Dự án này có được dùng công cụ AI không?", "hỏi trước khi dùng — nhiều khách Nhật có quy định riêng"),
   ("Please don't paste client data into public AI tools.", "Đừng dán dữ liệu khách vào công cụ AI công khai.", ""),
   ("The AI output looks right, but let's test it.", "Kết quả AI trông đúng, nhưng mình cứ test đã.", ""),
   ("Could you add more context to the prompt?", "Bạn thêm ngữ cảnh vào prompt được không?", ""),
   ("It's a hallucination. That function doesn't exist.", "AI bịa đấy. Hàm đó không có thật.", ""),
   ("AI helped me summarize the Japanese spec.", "AI giúp mình tóm tắt spec tiếng Nhật.", ""),
   ("I always double-check generated code.", "Mình luôn kiểm tra lại code do AI sinh ra.", ""),
  ],
  "dialogues": [
   ("Did you write this code yourself?", [
     ("I used AI for the first draft, then I reviewed and tested it.", True, "Minh bạch + cho thấy đã tự kiểm tra."),
     ("No, AI write all, I just copy.", False, "Sai thì ('wrote', 'copied') và cho thấy không kiểm tra gì."),
     ("Yes, 100% me.", False, "Giấu việc dùng AI — mất lòng tin khi bị phát hiện.")]),
   ("Can I paste the client's database schema into a public chatbot?", [
     ("Better not. It's confidential. Let's check the security rules first.", True, "Bảo vệ dữ liệu khách, đúng quy trình."),
     ("Sure, AI doesn't remember anything.", False, "Giả định nguy hiểm, có thể vi phạm hợp đồng."),
     ("Yes, you can pasting it.", False, "Sau 'can' dùng nguyên mẫu; và sai về bảo mật.")]),
   ("The AI says we should use this library method.", [
     ("Let me double-check the docs. It might be a hallucination.", True, "Kiểm chứng trước khi tin."),
     ("AI is always right. Let's use it.", False, "Tin mù quáng kết quả AI."),
     ("OK, I believe AI more than docs.", False, "Bỏ qua tài liệu chính thức là sai.")]),
   ("How did you finish the test cases so fast?", [
     ("I generated a first list with AI, then fixed the wrong ones.", True, "Giải thích rõ cách dùng AI có kiểm soát."),
     ("AI make it for me.", False, "Sai thì: AI made them for me — và nên nói mình đã kiểm tra."),
     ("I am very fast, that's all.", False, "Né tránh, không chia sẻ cách làm.")]),
   ("The AI answer is not useful. What should I do?", [
     ("Try a clearer prompt with an example of the output you want.", True, "Gợi ý cụ thể để cải thiện prompt."),
     ("AI is useless. Don't use it.", False, "Bỏ cuộc quá sớm."),
     ("You should to ask again.", False, "Sau 'should' không có 'to': You should ask again.")]),
  ],
  "listen": [
   ("Always review the AI output before you use it", ["review", "output"], "kết quả AI"),
   ("That method does not exist, so it is a hallucination", ["method", "hallucination"], "AI bịa"),
   ("Write a clear prompt with a few examples", ["clear", "prompt"], "viết prompt"),
   ("Do not paste confidential client code", ["confidential"], "bảo mật"),
   ("I asked the AI to summarize the Japanese spec. The summary was helpful, but one rule was wrong. So I checked it with the client.", ["summarize", "helpful", "rule"], "dùng AI đọc spec"),
   ("We can use AI tools on this project. However, we must not share confidential data. Please double-check all generated code.", ["tools", "share", "generated"], "quy định dùng AI"),
  ],
 },
]
