# -*- coding: utf-8 -*-
EXTRA = [
 {
  "title":"Bảo mật cơ bản",
  "vocab":[
   ("password","/ˈpæswɜːrd/","n","mật khẩu","Please change your <b>password</b> every month.","Nhớ đổi password mỗi tháng nhé."),
   ("encryption","/ɪnˈkrɪpʃən/","n","mã hóa","We use <b>encryption</b> to protect user data.","Mình dùng encryption để bảo vệ dữ liệu người dùng."),
   ("vulnerability","/ˌvʌlnərəˈbɪləti/","n","lỗ hổng bảo mật","The scanner found a <b>vulnerability</b> in the library.","Scanner tìm thấy một lỗ hổng trong thư viện."),
   ("firewall","/ˈfaɪərwɔːl/","n","tường lửa","The <b>firewall</b> blocks unknown traffic.","Firewall chặn traffic lạ."),
   ("authentication","/ɔːˌθentɪˈkeɪʃən/","n","xác thực","Two-factor <b>authentication</b> is more secure.","Xác thực hai lớp thì an toàn hơn."),
   ("breach","/briːtʃ/","n","vụ rò rỉ dữ liệu","There was a data <b>breach</b> last week.","Tuần trước có một vụ rò rỉ dữ liệu."),
   ("patch","/pætʃ/","n/v","bản vá / vá lỗi","We need to <b>patch</b> the server today.","Mình cần vá server hôm nay."),
   ("malware","/ˈmælweər/","n","phần mềm độc hại","The email had <b>malware</b> in the attachment.","Email đó có malware trong file đính kèm."),
   ("permission","/pərˈmɪʃən/","n","quyền truy cập","You need admin <b>permission</b> for this.","Bạn cần quyền admin cho cái này."),
   ("token","/ˈtoʊkən/","n","mã thông báo","The API needs a valid <b>token</b>.","API cần một token hợp lệ."),
  ],
  "phrases":[
   ("Please don't share your password.","Đừng chia sẻ mật khẩu của bạn.",""),
   ("We should encrypt this data.","Mình nên mã hóa dữ liệu này.",""),
   ("This login page is not secure.","Trang login này không an toàn.",""),
   ("Can you review the security report?","Bạn xem giúp báo cáo bảo mật được không?",""),
   ("I found a vulnerability in the code.","Mình tìm thấy một lỗ hổng trong code.",""),
  ],
  "dialogues":[
   ("Did you update the password policy?",[
     ("Yes, I updated it this morning.",True,"Câu đúng, dùng quá khứ."),
     ("Yes, I update it this morning.",False,"Thiếu 'ed', phải là 'updated'."),
     ("Yes, morning update finish.",False,"Sai trật tự từ, khó hiểu."),
   ]),
   ("How do we protect the user data?",[
     ("We encrypt it before saving.",True,"Câu tự nhiên và rõ ràng."),
     ("We encrypting it before save.",False,"Sai thì, phải là 'encrypt'."),
     ("Data we protect encrypt.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("we should encrypt the data before we save it",["encrypt","save"],"hành động cần làm"),
   ("the firewall blocks all the unknown network traffic",["firewall","traffic"],"về mạng"),
   ("please change your password every single month for safety",["password","month"],"lời khuyên"),
   ("the scanner found a serious vulnerability in the old library",["vulnerability","library"],"kết quả quét"),
  ],
 },
 {
  "title":"Cloud & hạ tầng",
  "vocab":[
   ("server","/ˈsɜːrvər/","n","máy chủ","The <b>server</b> is running slowly.","Máy chủ đang chạy chậm."),
   ("instance","/ˈɪnstəns/","n","phiên bản máy ảo","We started a new <b>instance</b> today.","Mình khởi động một instance mới hôm nay."),
   ("region","/ˈriːdʒən/","n","vùng máy chủ","Choose a <b>region</b> close to users.","Chọn region gần người dùng."),
   ("scale","/skeɪl/","v","mở rộng quy mô","We can <b>scale</b> the app easily.","Mình có thể scale app dễ dàng."),
   ("storage","/ˈstɔːrɪdʒ/","n","bộ nhớ lưu trữ","We are running out of <b>storage</b>.","Mình sắp hết storage rồi."),
   ("bandwidth","/ˈbændwɪdθ/","n","băng thông","The video uses a lot of <b>bandwidth</b>.","Video dùng nhiều băng thông."),
   ("backup","/ˈbækʌp/","n","bản sao lưu","We run a <b>backup</b> every night.","Mình chạy backup mỗi đêm."),
   ("provision","/prəˈvɪʒən/","v","cấp phát tài nguyên","Please <b>provision</b> two more servers.","Cấp phát thêm hai máy chủ nhé."),
   ("cluster","/ˈklʌstər/","n","cụm máy chủ","The database runs on a <b>cluster</b>.","Database chạy trên một cluster."),
   ("downtime","/ˈdaʊntaɪm/","n","thời gian ngừng hoạt động","The <b>downtime</b> was only five minutes.","Downtime chỉ có năm phút."),
  ],
  "phrases":[
   ("The server is down again.","Máy chủ lại sập rồi.",""),
   ("We need to scale up soon.","Mình cần scale up sớm.",""),
   ("Please check the storage usage.","Kiểm tra dung lượng lưu trữ giúp nhé.",""),
   ("The backup finished last night.","Backup xong tối qua rồi.",""),
   ("Which region are we using?","Mình đang dùng region nào?",""),
  ],
  "dialogues":[
   ("Why is the app so slow today?",[
     ("The server is running out of memory.",True,"Câu rõ ràng, đúng thì."),
     ("The server run out memory.",False,"Thiếu 'is' và 'of'."),
     ("Slow because server memory no.",False,"Sai ngữ pháp, khó hiểu."),
   ]),
   ("Can we handle more users next month?",[
     ("Yes, we can scale the servers.",True,"Câu tự nhiên."),
     ("Yes, we scaling the servers.",False,"Sai dạng động từ."),
     ("Yes, more servers we adding can.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the server is running out of storage space again",["server","storage"],"vấn đề"),
   ("we can scale the app when traffic goes up",["scale","traffic"],"khả năng mở rộng"),
   ("the nightly backup finished without any errors last night",["backup","errors"],"kết quả"),
   ("please choose a region that is close to users",["region","close"],"lời khuyên"),
  ],
 },
 {
  "title":"Frontend & giao diện",
  "vocab":[
   ("button","/ˈbʌtən/","n","nút bấm","The <b>button</b> is too small on mobile.","Nút bấm hơi nhỏ trên mobile."),
   ("layout","/ˈleɪaʊt/","n","bố cục","The <b>layout</b> looks clean now.","Bố cục nhìn gọn rồi."),
   ("responsive","/rɪˈspɑːnsɪv/","adj","tương thích nhiều màn hình","The design is fully <b>responsive</b>.","Thiết kế responsive hoàn toàn."),
   ("component","/kəmˈpoʊnənt/","n","thành phần giao diện","I built a reusable <b>component</b>.","Mình làm một component tái sử dụng."),
   ("render","/ˈrendər/","v","hiển thị","The page takes long to <b>render</b>.","Trang mất lâu để render."),
   ("style","/staɪl/","n/v","định dạng giao diện","Please <b>style</b> this header.","Style giúp cái header này nhé."),
   ("form","/fɔːrm/","n","biểu mẫu","The <b>form</b> has a validation bug.","Cái form bị lỗi validation."),
   ("dropdown","/ˈdrɑːpdaʊn/","n","danh sách xổ xuống","Add a <b>dropdown</b> for the country.","Thêm dropdown cho phần quốc gia."),
   ("animation","/ˌænɪˈmeɪʃən/","n","hiệu ứng chuyển động","The <b>animation</b> feels too slow.","Animation cảm giác hơi chậm."),
   ("breakpoint","/ˈbreɪkpɔɪnt/","n","điểm ngắt màn hình","Add a <b>breakpoint</b> for tablets.","Thêm breakpoint cho tablet."),
  ],
  "phrases":[
   ("The button color looks wrong.","Màu nút nhìn sai sai.",""),
   ("This page is not responsive yet.","Trang này chưa responsive.",""),
   ("Can you center this element?","Bạn căn giữa cái này được không?",""),
   ("The layout breaks on mobile.","Bố cục vỡ trên mobile.",""),
   ("I fixed the dropdown bug.","Mình sửa xong lỗi dropdown rồi.",""),
  ],
  "dialogues":[
   ("Does the page look good on mobile?",[
     ("No, the layout breaks on small screens.",True,"Câu rõ ràng."),
     ("No, the layout break on small screen.",False,"Thiếu 's' ở 'breaks'."),
     ("No, mobile layout no good break.",False,"Sai ngữ pháp."),
   ]),
   ("Can you make this button bigger?",[
     ("Sure, I'll update the style now.",True,"Câu tự nhiên, có 'will'."),
     ("Sure, I update style now.",False,"Thiếu 'will' và mạo từ."),
     ("Sure, button bigger I make.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the layout breaks on small mobile screens right now",["layout","mobile"],"vấn đề giao diện"),
   ("please make this button bigger on the login form",["button","form"],"yêu cầu"),
   ("the page takes too long to render on mobile",["render","mobile"],"hiệu năng"),
   ("i added a dropdown for the country in settings",["dropdown","country"],"thay đổi"),
  ],
 },
 {
  "title":"Hiệu năng & tối ưu",
  "vocab":[
   ("performance","/pərˈfɔːrməns/","n","hiệu năng","The app <b>performance</b> got better.","Hiệu năng app tốt hơn rồi."),
   ("latency","/ˈleɪtənsi/","n","độ trễ","The API <b>latency</b> is too high.","Độ trễ API cao quá."),
   ("optimize","/ˈɑːptɪmaɪz/","v","tối ưu","We should <b>optimize</b> this function.","Mình nên tối ưu hàm này."),
   ("bottleneck","/ˈbɑːtlnek/","n","điểm nghẽn","The database is the <b>bottleneck</b>.","Database là điểm nghẽn."),
   ("cache","/kæʃ/","n/v","bộ nhớ đệm","We <b>cache</b> the results for speed.","Mình cache kết quả cho nhanh."),
   ("memory","/ˈmeməri/","n","bộ nhớ","The app uses too much <b>memory</b>.","App dùng quá nhiều memory."),
   ("query","/ˈkwɪri/","n","truy vấn","This <b>query</b> is very slow.","Query này chậm lắm."),
   ("index","/ˈɪndeks/","n","chỉ mục cơ sở dữ liệu","Add an <b>index</b> to this column.","Thêm index cho cột này."),
   ("throughput","/ˈθruːpʊt/","n","thông lượng xử lý","The <b>throughput</b> doubled after the fix.","Thông lượng tăng gấp đôi sau khi sửa."),
   ("profiling","/ˈproʊfaɪlɪŋ/","n","phân tích hiệu năng","I ran <b>profiling</b> on the service.","Mình chạy profiling cho service."),
  ],
  "phrases":[
   ("This page loads too slowly.","Trang này tải chậm quá.",""),
   ("We need to add a cache.","Mình cần thêm cache.",""),
   ("The query is the bottleneck.","Query là điểm nghẽn.",""),
   ("Can you optimize this loop?","Bạn tối ưu vòng lặp này được không?",""),
   ("Latency dropped after the fix.","Độ trễ giảm sau khi sửa.",""),
  ],
  "dialogues":[
   ("Why is this endpoint so slow?",[
     ("The database query is not optimized.",True,"Câu rõ ràng."),
     ("The database query no optimize.",False,"Thiếu 'is' và dạng đúng."),
     ("Slow endpoint because query bad.",False,"Sai ngữ pháp, thiếu chủ ngữ rõ."),
   ]),
   ("How can we make it faster?",[
     ("We can add a cache for the results.",True,"Câu tự nhiên."),
     ("We can adding cache for result.",False,"Sai dạng động từ, thiếu mạo từ."),
     ("Faster we make cache add.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the database query is too slow without an index",["query","index"],"vấn đề hiệu năng"),
   ("we should add a cache to reduce the latency",["cache","latency"],"giải pháp"),
   ("the app uses too much memory during heavy load",["memory","load"],"vấn đề tài nguyên"),
   ("i ran profiling and found the real bottleneck today",["profiling","bottleneck"],"hành động"),
  ],
 },
 {
  "title":"Logging & giám sát",
  "vocab":[
   ("log","/lɔːɡ/","n","bản ghi nhật ký","Check the <b>log</b> for the error.","Xem log để tìm lỗi."),
   ("alert","/əˈlɜːrt/","n","cảnh báo","We got an <b>alert</b> at midnight.","Mình nhận cảnh báo lúc nửa đêm."),
   ("monitor","/ˈmɑːnɪtər/","v","giám sát","We <b>monitor</b> the server all day.","Mình giám sát server cả ngày."),
   ("dashboard","/ˈdæʃbɔːrd/","n","bảng điều khiển","The <b>dashboard</b> shows live data.","Dashboard hiển thị dữ liệu trực tiếp."),
   ("metric","/ˈmetrɪk/","n","chỉ số đo lường","This <b>metric</b> looks abnormal.","Chỉ số này nhìn bất thường."),
   ("threshold","/ˈθreʃhoʊld/","n","ngưỡng giới hạn","The CPU passed the <b>threshold</b>.","CPU vượt ngưỡng rồi."),
   ("trace","/treɪs/","n","dấu vết truy vết","The <b>trace</b> shows the slow call.","Trace cho thấy lệnh gọi chậm."),
   ("error","/ˈerər/","n","lỗi","The <b>error</b> rate went up.","Tỉ lệ lỗi tăng lên."),
   ("warning","/ˈwɔːrnɪŋ/","n","cảnh báo nhẹ","I see a <b>warning</b> in the log.","Mình thấy một warning trong log."),
   ("uptime","/ˈʌptaɪm/","n","thời gian hoạt động","Our <b>uptime</b> is very good this month.","Uptime tháng này rất tốt."),
  ],
  "phrases":[
   ("Please check the error logs.","Kiểm tra log lỗi giúp nhé.",""),
   ("We got an alert last night.","Tối qua mình nhận cảnh báo.",""),
   ("The dashboard is not updating.","Dashboard không cập nhật.",""),
   ("The error rate is too high.","Tỉ lệ lỗi cao quá.",""),
   ("Can you set up an alert?","Bạn tạo cảnh báo được không?",""),
  ],
  "dialogues":[
   ("Did you see the alert last night?",[
     ("Yes, I checked the logs right away.",True,"Câu đúng thì quá khứ."),
     ("Yes, I check the log right away.",False,"Thiếu 'ed', phải là 'checked'."),
     ("Yes, last night log I see.",False,"Sai trật tự từ."),
   ]),
   ("How do we know if the server is healthy?",[
     ("We monitor it on the dashboard.",True,"Câu tự nhiên."),
     ("We monitoring it on dashboard.",False,"Sai dạng động từ, thiếu mạo từ."),
     ("Server healthy we watch metric.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("please check the error logs before you restart it",["error","restart"],"yêu cầu"),
   ("we got a critical alert from the server tonight",["alert","server"],"sự kiện"),
   ("the dashboard shows that the error rate is rising",["dashboard","rate"],"quan sát"),
   ("the cpu usage just passed the warning threshold again",["threshold","warning"],"cảnh báo"),
  ],
 },
 {
  "title":"Docker & container",
  "vocab":[
   ("container","/kənˈteɪnər/","n","container","The <b>container</b> keeps crashing.","Container cứ crash hoài."),
   ("image","/ˈɪmɪdʒ/","n","ảnh docker","We built a new Docker <b>image</b>.","Mình build một image mới."),
   ("dockerfile","/ˈdɑːkərfaɪl/","n","tệp cấu hình docker","Update the <b>dockerfile</b> please.","Cập nhật dockerfile giúp nhé."),
   ("volume","/ˈvɑːljuːm/","n","ổ đĩa gắn kèm","Mount a <b>volume</b> for the data.","Gắn một volume cho dữ liệu."),
   ("port","/pɔːrt/","n","cổng kết nối","Map the <b>port</b> to 8080.","Map port sang 8080."),
   ("build","/bɪld/","v","biên dịch đóng gói","The <b>build</b> failed again.","Build lại fail nữa rồi."),
   ("registry","/ˈredʒɪstri/","n","kho lưu ảnh","Push the image to the <b>registry</b>.","Push image lên registry."),
   ("tag","/tæɡ/","n","nhãn phiên bản","Use the latest <b>tag</b>.","Dùng tag mới nhất."),
   ("compose","/kəmˈpoʊz/","n","công cụ ghép container","Run it with Docker <b>compose</b>.","Chạy nó bằng Docker compose."),
   ("environment","/ɪnˈvaɪrənmənt/","n","môi trường","Set the right <b>environment</b> variables.","Đặt đúng biến môi trường."),
  ],
  "phrases":[
   ("The container won't start.","Container không khởi động.",""),
   ("Please rebuild the image.","Build lại image giúp nhé.",""),
   ("Which port are we using?","Mình dùng cổng nào?",""),
   ("The build failed on the server.","Build fail trên server.",""),
   ("Push the image to the registry.","Push image lên registry.",""),
  ],
  "dialogues":[
   ("Why won't the container start?",[
     ("The port is already in use.",True,"Câu rõ ràng."),
     ("The port already using.",False,"Thiếu 'is' và dạng đúng."),
     ("Start no because port busy.",False,"Sai ngữ pháp."),
   ]),
   ("Did you update the image?",[
     ("Yes, I rebuilt it this morning.",True,"Câu đúng thì."),
     ("Yes, I rebuild it this morning.",False,"Thiếu quá khứ 'rebuilt'."),
     ("Yes, image morning I build.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the container keeps crashing every time we deploy it",["container","deploy"],"vấn đề"),
   ("please rebuild the image and push it to registry",["image","registry"],"yêu cầu"),
   ("we need to map the port to eight zero",["port","map"],"cấu hình"),
   ("mount a volume so the data is not lost",["volume","data"],"lời khuyên"),
  ],
 },
 {
  "title":"CI/CD",
  "vocab":[
   ("pipeline","/ˈpaɪplaɪn/","n","chuỗi tự động hóa","The <b>pipeline</b> is green now.","Pipeline xanh rồi."),
   ("build","/bɪld/","n","quá trình đóng gói","The <b>build</b> takes ten minutes.","Build mất mười phút."),
   ("deploy","/dɪˈplɔɪ/","v","triển khai","We <b>deploy</b> every Friday.","Mình deploy mỗi thứ Sáu."),
   ("stage","/steɪdʒ/","n","giai đoạn","The test <b>stage</b> failed.","Giai đoạn test bị fail."),
   ("rollback","/ˈroʊlbæk/","n","khôi phục bản cũ","We did a quick <b>rollback</b>.","Mình rollback nhanh."),
   ("artifact","/ˈɑːrtɪfækt/","n","sản phẩm build","The <b>artifact</b> is ready to deploy.","Artifact sẵn sàng để deploy."),
   ("trigger","/ˈtrɪɡər/","v","kích hoạt","A push will <b>trigger</b> the build.","Một cú push sẽ kích hoạt build."),
   ("merge","/mɜːrdʒ/","v","gộp mã nguồn","Please <b>merge</b> the branch first.","Merge branch trước nhé."),
   ("release","/rɪˈliːs/","n","bản phát hành","The new <b>release</b> is live.","Bản release mới đã lên."),
   ("workflow","/ˈwɜːrkfloʊ/","n","quy trình tự động","The GitHub <b>workflow</b> runs on every push.","Workflow trên GitHub chạy mỗi lần push."),
  ],
  "phrases":[
   ("The pipeline is failing.","Pipeline đang fail.",""),
   ("Can you deploy to staging?","Bạn deploy lên staging được không?",""),
   ("We need to roll back now.","Mình cần rollback ngay.",""),
   ("The build passed all tests.","Build qua hết test rồi.",""),
   ("Please merge your branch first.","Merge branch của bạn trước nhé.",""),
  ],
  "dialogues":[
   ("Why is the pipeline red?",[
     ("The test stage failed on the last commit.",True,"Câu rõ ràng."),
     ("The test stage fail on last commit.",False,"Thiếu 'ed' và mạo từ."),
     ("Red because test no pass.",False,"Sai ngữ pháp."),
   ]),
   ("Can we ship this today?",[
     ("Yes, if the build passes we deploy.",True,"Câu tự nhiên."),
     ("Yes, if build passing we deploying.",False,"Sai dạng động từ."),
     ("Yes, today ship if build good.",False,"Sai trật tự và thiếu chủ ngữ."),
   ]),
  ],
  "listen":[
   ("the pipeline failed again during the final test stage",["pipeline","stage"],"sự cố"),
   ("we deploy the new release to staging every friday",["deploy","release"],"quy trình"),
   ("please merge your branch before you start the build",["merge","build"],"yêu cầu"),
   ("we did a quick rollback after the deploy broke",["rollback","deploy"],"hành động"),
  ],
 },
 {
  "title":"Agile & Scrum",
  "vocab":[
   ("sprint","/sprɪnt/","n","chu kỳ làm việc","This <b>sprint</b> ends on Friday.","Sprint này kết thúc thứ Sáu."),
   ("standup","/ˈstændʌp/","n","họp nhanh hằng ngày","The <b>standup</b> is at nine.","Standup lúc chín giờ."),
   ("backlog","/ˈbæklɔːɡ/","n","danh sách công việc chờ","Add this to the <b>backlog</b>.","Thêm cái này vào backlog."),
   ("story","/ˈstɔːri/","n","hạng mục công việc","This user <b>story</b> is too big.","User story này to quá."),
   ("retrospective","/ˌretrəˈspektɪv/","n","họp nhìn lại","The <b>retrospective</b> is tomorrow.","Retrospective ngày mai."),
   ("velocity","/vəˈlɑːsəti/","n","tốc độ hoàn thành","Our team <b>velocity</b> is stable.","Velocity của team ổn định."),
   ("estimate","/ˈestɪmət/","n","ước lượng công sức","What is your <b>estimate</b> for this?","Bạn ước lượng cái này bao lâu?"),
   ("blocker","/ˈblɑːkər/","n","vấn đề cản trở","I have a <b>blocker</b> today.","Hôm nay mình có một blocker."),
   ("ticket","/ˈtɪkɪt/","n","phiếu công việc","Please update the <b>ticket</b> status.","Cập nhật trạng thái ticket nhé."),
   ("scope","/skoʊp/","n","phạm vi công việc","This is out of <b>scope</b>.","Cái này ngoài phạm vi."),
  ],
  "phrases":[
   ("I have no blockers today.","Hôm nay mình không có blocker.",""),
   ("Let's move this to the backlog.","Chuyển cái này vào backlog đi.",""),
   ("The sprint ends this Friday.","Sprint kết thúc thứ Sáu này.",""),
   ("Can you update the ticket?","Bạn cập nhật ticket được không?",""),
   ("This story is too big.","Story này to quá.",""),
  ],
  "dialogues":[
   ("What did you do yesterday?",[
     ("I finished the login ticket.",True,"Câu đúng thì quá khứ."),
     ("I finish the login ticket.",False,"Thiếu 'ed', phải là 'finished'."),
     ("Yesterday login ticket I do.",False,"Sai trật tự từ."),
   ]),
   ("Do you have any blockers?",[
     ("Yes, I'm waiting for the API keys.",True,"Câu tự nhiên."),
     ("Yes, I waiting for API key.",False,"Thiếu 'am' và mạo từ."),
     ("Yes, blocker API key wait.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("this sprint ends on friday so please finish early",["sprint","friday"],"lịch"),
   ("i have one blocker and i need your help",["blocker","help"],"báo cáo standup"),
   ("please move this user story to the product backlog",["story","backlog"],"yêu cầu"),
   ("the retrospective meeting is tomorrow right after the standup",["retrospective","standup"],"lịch họp"),
  ],
 },
 {
  "title":"Onboarding & học việc",
  "vocab":[
   ("onboarding","/ˈɑːnbɔːrdɪŋ/","n","quá trình nhập môn","Your <b>onboarding</b> starts on Monday.","Onboarding của bạn bắt đầu thứ Hai."),
   ("mentor","/ˈmentɔːr/","n","người hướng dẫn","My <b>mentor</b> helps me every day.","Mentor của mình giúp mỗi ngày."),
   ("setup","/ˈsetʌp/","n","cài đặt ban đầu","The laptop <b>setup</b> took one hour.","Cài đặt laptop mất một tiếng."),
   ("access","/ˈækses/","n","quyền truy cập","I don't have <b>access</b> yet.","Mình chưa có quyền truy cập."),
   ("documentation","/ˌdɑːkjumenˈteɪʃən/","n","tài liệu","Please read the <b>documentation</b> first.","Đọc tài liệu trước nhé."),
   ("orientation","/ˌɔːriənˈteɪʃən/","n","buổi định hướng","The <b>orientation</b> is this afternoon.","Buổi định hướng chiều nay."),
   ("checklist","/ˈtʃeklɪst/","n","danh sách kiểm tra","Follow the setup <b>checklist</b>.","Làm theo checklist cài đặt."),
   ("credential","/krəˈdenʃəl/","n","thông tin đăng nhập","I got my login <b>credentials</b>.","Mình nhận được thông tin đăng nhập."),
   ("repository","/rɪˈpɑːzɪtɔːri/","n","kho mã nguồn","Clone the <b>repository</b> first.","Clone repository trước."),
   ("guideline","/ˈɡaɪdlaɪn/","n","hướng dẫn quy tắc","Follow the coding <b>guidelines</b>.","Theo guideline viết code."),
  ],
  "phrases":[
   ("I don't have access yet.","Mình chưa có quyền truy cập.",""),
   ("Who is my mentor?","Mentor của mình là ai?",""),
   ("Where is the documentation?","Tài liệu ở đâu vậy?",""),
   ("Can you help me set up?","Bạn giúp mình cài đặt được không?",""),
   ("I finished the onboarding checklist.","Mình xong checklist onboarding rồi.",""),
  ],
  "dialogues":[
   ("How is your first week going?",[
     ("It's going well, my mentor is very helpful.",True,"Câu tự nhiên."),
     ("It going well, my mentor very helpful.",False,"Thiếu 'is'."),
     ("First week good, mentor help me.",False,"Sai ngữ pháp."),
   ]),
   ("Do you have access to the repository?",[
     ("Not yet, I'm still waiting for the credentials.",True,"Câu tự nhiên."),
     ("No, I still wait the credential.",False,"Sai dạng động từ, thiếu 'for'."),
     ("No, credential I no have.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("i do not have access to the repository yet",["access","repository"],"vấn đề"),
   ("please read the documentation before you start any task",["documentation","task"],"lời khuyên"),
   ("my mentor helped me finish the setup this morning",["mentor","setup"],"hỗ trợ"),
   ("follow the onboarding checklist step by step today please",["onboarding","checklist"],"hướng dẫn"),
  ],
 },
 {
  "title":"Tài liệu kỹ thuật",
  "vocab":[
   ("spec","/spek/","n","bản đặc tả","The API <b>spec</b> is not clear.","Bản đặc tả API chưa rõ."),
   ("readme","/ˈriːdmiː/","n","tệp giới thiệu","Update the <b>readme</b> file please.","Cập nhật file readme nhé."),
   ("guide","/ɡaɪd/","n","hướng dẫn","This <b>guide</b> is very helpful.","Guide này rất hữu ích."),
   ("example","/ɪɡˈzæmpəl/","n","ví dụ","Add a code <b>example</b> here.","Thêm ví dụ code ở đây."),
   ("reference","/ˈrefərəns/","n","tài liệu tham khảo","Check the API <b>reference</b>.","Xem tài liệu tham khảo API."),
   ("section","/ˈsekʃən/","n","phần mục","This <b>section</b> is out of date.","Phần này lỗi thời rồi."),
   ("diagram","/ˈdaɪəɡræm/","n","sơ đồ","The <b>diagram</b> shows the flow.","Sơ đồ cho thấy luồng chạy."),
   ("update","/ˈʌpdeɪt/","v","cập nhật","Please <b>update</b> the docs.","Cập nhật docs nhé."),
   ("comment","/ˈkɑːment/","n","chú thích trong code","Add a <b>comment</b> to explain this.","Thêm chú thích để giải thích."),
   ("changelog","/ˈtʃeɪndʒlɔːɡ/","n","nhật ký thay đổi","Write it in the <b>changelog</b>.","Ghi vào changelog."),
  ],
  "phrases":[
   ("The docs are out of date.","Tài liệu lỗi thời rồi.",""),
   ("Can you add an example?","Bạn thêm ví dụ được không?",""),
   ("Please update the readme.","Cập nhật readme giúp nhé.",""),
   ("This section is not clear.","Phần này chưa rõ.",""),
   ("Where is the API reference?","Tài liệu tham khảo API ở đâu?",""),
  ],
  "dialogues":[
   ("Is the documentation up to date?",[
     ("No, this section is out of date.",True,"Câu rõ ràng."),
     ("No, this section out of date.",False,"Thiếu 'is'."),
     ("No, section old not update.",False,"Sai ngữ pháp."),
   ]),
   ("Can you explain how this works?",[
     ("Sure, I'll add a diagram to the docs.",True,"Câu tự nhiên có 'will'."),
     ("Sure, I add diagram to doc.",False,"Thiếu 'will' và mạo từ."),
     ("Sure, diagram I make explain.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("please update the readme file for the new release",["update","readme"],"yêu cầu"),
   ("this section of the guide is out of date",["section","guide"],"vấn đề"),
   ("add a short code example to the api reference",["example","reference"],"yêu cầu"),
   ("the diagram in the docs shows the whole flow",["diagram","flow"],"mô tả"),
  ],
 },
 {
  "title":"Kiến trúc hệ thống",
  "vocab":[
   ("architecture","/ˈɑːrkɪtektʃər/","n","kiến trúc","The system <b>architecture</b> is clean.","Kiến trúc hệ thống gọn gàng."),
   ("design","/dɪˈzaɪn/","n","thiết kế","Let's review the <b>design</b> first.","Review thiết kế trước đã."),
   ("module","/ˈmɑːdʒuːl/","n","khối chức năng","This <b>module</b> is too complex.","Module này phức tạp quá."),
   ("layer","/ˈleɪər/","n","tầng","The data <b>layer</b> handles storage.","Tầng dữ liệu lo phần lưu trữ."),
   ("dependency","/dɪˈpendənsi/","n","phụ thuộc","This service has too many <b>dependencies</b>.","Service này phụ thuộc nhiều quá."),
   ("interface","/ˈɪntərfeɪs/","n","giao diện lập trình","They share a common <b>interface</b>.","Chúng dùng chung một interface."),
   ("pattern","/ˈpætərn/","n","mẫu thiết kế","We use the observer <b>pattern</b> here.","Ở đây mình dùng observer pattern."),
   ("scalability","/ˌskeɪləˈbɪləti/","n","khả năng mở rộng","We must think about <b>scalability</b>.","Mình phải nghĩ tới scalability."),
   ("coupling","/ˈkʌplɪŋ/","n","sự ràng buộc giữa các phần","The <b>coupling</b> is too tight here.","Ở đây coupling chặt quá."),
   ("boundary","/ˈbaʊndəri/","n","ranh giới hệ thống","We need a clear service <b>boundary</b>.","Mình cần ranh giới service rõ ràng."),
  ],
  "phrases":[
   ("Let's review the design first.","Review thiết kế trước đã.",""),
   ("This module is too complex.","Module này phức tạp quá.",""),
   ("We have too many dependencies.","Mình phụ thuộc nhiều quá.",""),
   ("Think about scalability early.","Nghĩ tới scalability từ sớm.",""),
   ("The coupling is too tight.","Coupling chặt quá.",""),
  ],
  "dialogues":[
   ("What do you think of this design?",[
     ("It's clean, but the coupling is too tight.",True,"Câu tự nhiên."),
     ("It clean, but the coupling too tight.",False,"Thiếu 'is'."),
     ("Design good but coupling tight much.",False,"Sai ngữ pháp."),
   ]),
   ("Can this system handle more users?",[
     ("Not easily, we need better scalability.",True,"Câu rõ ràng."),
     ("Not easy, we need scalability more good.",False,"Sai trật tự và dạng từ."),
     ("More user handle need architecture.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("this module is too complex and hard to test",["module","test"],"vấn đề thiết kế"),
   ("the service has too many dependencies right now sadly",["service","dependencies"],"vấn đề"),
   ("we must think about scalability before we write code",["scalability","code"],"lời khuyên"),
   ("the data layer handles all of the storage logic",["layer","storage"],"kiến trúc"),
  ],
 },
 {
  "title":"Microservices",
  "vocab":[
   ("service","/ˈsɜːrvɪs/","n","dịch vụ nhỏ","Each <b>service</b> has one job.","Mỗi service làm một việc."),
   ("endpoint","/ˈendpɔɪnt/","n","điểm cuối API","This <b>endpoint</b> returns user data.","Endpoint này trả về dữ liệu người dùng."),
   ("gateway","/ˈɡeɪtweɪ/","n","cổng vào","All calls go through the <b>gateway</b>.","Mọi lời gọi đi qua gateway."),
   ("contract","/ˈkɑːntrækt/","n","giao ước giữa service","We must keep the API <b>contract</b>.","Mình phải giữ đúng contract API."),
   ("request","/rɪˈkwest/","n","yêu cầu","The <b>request</b> failed with a timeout.","Request fail vì timeout."),
   ("response","/rɪˈspɑːns/","n","phản hồi","The <b>response</b> was too slow.","Response chậm quá."),
   ("timeout","/ˈtaɪmaʊt/","n","hết thời gian chờ","We got a <b>timeout</b> error.","Mình gặp lỗi timeout."),
   ("retry","/ˈriːtraɪ/","n/v","thử lại","Add a <b>retry</b> for this call.","Thêm retry cho lời gọi này."),
   ("discovery","/dɪˈskʌvəri/","n","tìm dịch vụ","We use service <b>discovery</b> here.","Ở đây mình dùng service discovery."),
   ("decouple","/diːˈkʌpəl/","v","tách rời phụ thuộc","We should <b>decouple</b> these two services.","Mình nên tách rời hai service này."),
  ],
  "phrases":[
   ("This service is down.","Service này đang sập.",""),
   ("The request timed out.","Request bị timeout.",""),
   ("Add a retry for this call.","Thêm retry cho lời gọi này.",""),
   ("All calls go through the gateway.","Mọi lời gọi qua gateway.",""),
   ("We should decouple these services.","Mình nên tách rời các service này.",""),
  ],
  "dialogues":[
   ("Why did the request fail?",[
     ("The service timed out after ten seconds.",True,"Câu đúng thì."),
     ("The service timeout after ten second.",False,"Sai dạng động từ và số nhiều."),
     ("Fail because service slow no answer.",False,"Sai ngữ pháp."),
   ]),
   ("How do the services talk to each other?",[
     ("They call each other through the gateway.",True,"Câu tự nhiên."),
     ("They calling each other by gateway.",False,"Sai dạng động từ."),
     ("Service talk gateway through each.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the payment service timed out after ten long seconds",["service","timed"],"sự cố"),
   ("all the requests go through the api gateway first",["requests","gateway"],"luồng"),
   ("we should add a retry for this failing call",["retry","call"],"giải pháp"),
   ("we need to decouple these two services very soon",["decouple","services"],"kiến trúc"),
  ],
 },
 {
  "title":"Message queue & sự kiện",
  "vocab":[
   ("queue","/kjuː/","n","hàng đợi","The <b>queue</b> is full again.","Queue lại đầy rồi."),
   ("message","/ˈmesɪdʒ/","n","thông điệp","The <b>message</b> was not delivered.","Message không được gửi tới."),
   ("event","/ɪˈvent/","n","sự kiện","This <b>event</b> triggers an email.","Sự kiện này kích hoạt một email."),
   ("producer","/prəˈduːsər/","n","bên gửi","The <b>producer</b> sends the events.","Producer gửi các sự kiện."),
   ("consumer","/kənˈsuːmər/","n","bên nhận xử lý","The <b>consumer</b> reads the queue.","Consumer đọc từ queue."),
   ("topic","/ˈtɑːpɪk/","n","chủ đề tin nhắn","Publish this to the orders <b>topic</b>.","Publish cái này vào topic orders."),
   ("subscribe","/səbˈskraɪb/","v","đăng ký nhận","The service must <b>subscribe</b> to the topic.","Service phải subscribe vào topic."),
   ("publish","/ˈpʌblɪʃ/","v","phát tin","We <b>publish</b> an event on each order.","Mỗi đơn hàng mình publish một event."),
   ("broker","/ˈbroʊkər/","n","trung gian tin nhắn","The message <b>broker</b> is Kafka.","Message broker là Kafka."),
   ("acknowledge","/əkˈnɑːlɪdʒ/","v","xác nhận đã nhận","The consumer must <b>acknowledge</b> the message.","Consumer phải xác nhận đã nhận message."),
  ],
  "phrases":[
   ("The queue is full again.","Queue lại đầy rồi.",""),
   ("This event triggers an email.","Sự kiện này kích hoạt email.",""),
   ("The message was not delivered.","Message không được gửi tới.",""),
   ("We publish an event per order.","Mỗi đơn mình publish một event.",""),
   ("The consumer is too slow.","Consumer chậm quá.",""),
  ],
  "dialogues":[
   ("Why are messages piling up?",[
     ("The consumer is too slow right now.",True,"Câu rõ ràng."),
     ("The consumer too slow right now.",False,"Thiếu 'is'."),
     ("Message many because consumer slow.",False,"Sai ngữ pháp."),
   ]),
   ("How does the email get sent?",[
     ("An event triggers it after each order.",True,"Câu tự nhiên."),
     ("An event trigger it after each order.",False,"Thiếu 's' ở 'triggers'."),
     ("Email send when order event have.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("the message queue is full and messages are delayed",["queue","delayed"],"sự cố"),
   ("the consumer reads each message from the orders topic",["consumer","topic"],"luồng"),
   ("we publish a new event after every single order",["publish","event"],"quy trình"),
   ("the consumer must acknowledge the message when it finishes",["acknowledge","message"],"quy tắc"),
  ],
 },
 {
  "title":"Caching",
  "vocab":[
   ("cache","/kæʃ/","n","bộ nhớ đệm","The <b>cache</b> made it much faster.","Cache làm nó nhanh hơn hẳn."),
   ("hit","/hɪt/","n","lần trúng cache","The cache <b>hit</b> rate is high.","Tỉ lệ cache hit cao."),
   ("miss","/mɪs/","n","lần trượt cache","Too many cache <b>misses</b> today.","Hôm nay cache miss nhiều quá."),
   ("expire","/ɪkˈspaɪər/","v","hết hạn","The cache will <b>expire</b> in one hour.","Cache sẽ hết hạn sau một tiếng."),
   ("invalidate","/ɪnˈvælɪdeɪt/","v","làm mất hiệu lực","We must <b>invalidate</b> the old cache.","Mình phải invalidate cache cũ."),
   ("key","/kiː/","n","khóa","Each cache <b>key</b> must be unique.","Mỗi cache key phải là duy nhất."),
   ("value","/ˈvæljuː/","n","giá trị","The cached <b>value</b> is wrong.","Giá trị trong cache bị sai."),
   ("refresh","/rɪˈfreʃ/","v","làm mới","We <b>refresh</b> the cache every hour.","Mình refresh cache mỗi giờ."),
   ("stale","/steɪl/","adj","cũ, lỗi thời","The data is <b>stale</b> now.","Dữ liệu bây giờ cũ rồi."),
   ("eviction","/ɪˈvɪkʃən/","n","loại bỏ khỏi cache","The <b>eviction</b> policy is LRU.","Chính sách eviction là LRU."),
  ],
  "phrases":[
   ("The cache is stale.","Cache cũ rồi.",""),
   ("We need to refresh the cache.","Mình cần refresh cache.",""),
   ("The hit rate is low.","Tỉ lệ hit thấp.",""),
   ("Please invalidate the old data.","Invalidate dữ liệu cũ giúp nhé.",""),
   ("This value is out of date.","Giá trị này lỗi thời rồi.",""),
  ],
  "dialogues":[
   ("Why is the old data still showing?",[
     ("The cache is stale, we need to refresh it.",True,"Câu rõ ràng."),
     ("The cache stale, we need refresh it.",False,"Thiếu 'is' và 'to'."),
     ("Old data show because cache no new.",False,"Sai ngữ pháp."),
   ]),
   ("Is the cache helping performance?",[
     ("Yes, the hit rate is very high.",True,"Câu tự nhiên."),
     ("Yes, the hit rate very high.",False,"Thiếu 'is'."),
     ("Yes, cache fast hit many.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("the cache is stale so we must refresh it",["cache","refresh"],"vấn đề"),
   ("the cache hit rate is very high this week",["hit","high"],"chỉ số"),
   ("please invalidate the old value after every single update",["invalidate","value"],"quy tắc"),
   ("each cache key must be unique across the system",["key","unique"],"quy tắc"),
  ],
 },
 {
  "title":"Xác thực & phân quyền",
  "vocab":[
   ("login","/ˈlɔːɡɪn/","n","đăng nhập","The <b>login</b> page is broken.","Trang login bị lỗi."),
   ("session","/ˈseʃən/","n","phiên làm việc","The <b>session</b> expired too soon.","Session hết hạn sớm quá."),
   ("token","/ˈtoʊkən/","n","mã truy cập","The access <b>token</b> is invalid.","Access token không hợp lệ."),
   ("role","/roʊl/","n","vai trò","This user has the admin <b>role</b>.","User này có role admin."),
   ("authorize","/ˈɔːθəraɪz/","v","phân quyền","We must <b>authorize</b> the request.","Mình phải phân quyền cho request."),
   ("grant","/ɡrænt/","v","cấp quyền","Please <b>grant</b> her write access.","Cấp cho cô ấy quyền ghi nhé."),
   ("logout","/ˈlɔːɡaʊt/","n/v","đăng xuất","The <b>logout</b> button does nothing.","Nút logout không làm gì cả."),
   ("refresh","/rɪˈfreʃ/","v","làm mới token","We <b>refresh</b> the token silently.","Mình refresh token âm thầm."),
   ("verify","/ˈverɪfaɪ/","v","xác minh","We <b>verify</b> the email at signup.","Mình xác minh email khi đăng ký."),
   ("scope","/skoʊp/","n","phạm vi quyền","This token has read <b>scope</b> only.","Token này chỉ có scope đọc."),
  ],
  "phrases":[
   ("My session expired again.","Phiên của mình lại hết hạn.",""),
   ("The login is not working.","Login không hoạt động.",""),
   ("Please grant me write access.","Cấp cho mình quyền ghi nhé.",""),
   ("The token is invalid.","Token không hợp lệ.",""),
   ("We verify the email first.","Mình xác minh email trước.",""),
  ],
  "dialogues":[
   ("Why can't I save my changes?",[
     ("You don't have write permission yet.",True,"Câu rõ ràng."),
     ("You not have write permission yet.",False,"Thiếu 'do'."),
     ("Save no because permission you.",False,"Sai ngữ pháp."),
   ]),
   ("Why did it log me out?",[
     ("Your session expired after thirty minutes.",True,"Câu đúng thì."),
     ("Your session expire after thirty minute.",False,"Sai dạng động từ và số nhiều."),
     ("Log out because session time end.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("my session expired again after only thirty short minutes",["session","expired"],"vấn đề"),
   ("please grant her write access to the shared folder",["grant","access"],"yêu cầu"),
   ("the access token is invalid so login keeps failing",["token","login"],"sự cố"),
   ("we verify each user email during the signup flow",["verify","email"],"quy trình"),
  ],
 },
 {
  "title":"Mạng cơ bản",
  "vocab":[
   ("network","/ˈnetwɜːrk/","n","mạng","The <b>network</b> is very slow today.","Mạng hôm nay chậm lắm."),
   ("protocol","/ˈproʊtəkɔːl/","n","giao thức","We use the HTTPS <b>protocol</b>.","Mình dùng giao thức HTTPS."),
   ("packet","/ˈpækɪt/","n","gói tin","Some <b>packets</b> were lost.","Một số gói tin bị mất."),
   ("address","/ˈædres/","n","địa chỉ","What is the IP <b>address</b>?","Địa chỉ IP là gì?"),
   ("connection","/kəˈnekʃən/","n","kết nối","The <b>connection</b> keeps dropping.","Kết nối cứ rớt hoài."),
   ("dns","/ˌdiːenˈes/","n","hệ thống tên miền","The <b>dns</b> lookup failed.","Tra cứu DNS thất bại."),
   ("ping","/pɪŋ/","n/v","kiểm tra kết nối","Can you <b>ping</b> the server?","Bạn ping thử server được không?"),
   ("proxy","/ˈprɑːksi/","n","máy chủ trung gian","All traffic goes through a <b>proxy</b>.","Mọi traffic đi qua proxy."),
   ("route","/ruːt/","n/v","định tuyến","This <b>route</b> is blocked.","Đường route này bị chặn."),
   ("host","/hoʊst/","n","máy chủ đích","The <b>host</b> is not reachable.","Không kết nối được tới host."),
  ],
  "phrases":[
   ("The network is down.","Mạng đang sập.",""),
   ("Can you ping the server?","Bạn ping thử server được không?",""),
   ("The connection keeps dropping.","Kết nối cứ rớt hoài.",""),
   ("What is the IP address?","Địa chỉ IP là gì?",""),
   ("The DNS lookup failed.","Tra cứu DNS thất bại.",""),
  ],
  "dialogues":[
   ("Why can't I reach the server?",[
     ("The connection keeps dropping today.",True,"Câu rõ ràng."),
     ("The connection keep dropping today.",False,"Thiếu 's' ở 'keeps'."),
     ("Reach no because network bad.",False,"Sai ngữ pháp."),
   ]),
   ("Is the server up?",[
     ("I'm not sure, let me ping it.",True,"Câu tự nhiên."),
     ("I not sure, let me ping it.",False,"Thiếu 'am'."),
     ("Not know, ping I try can.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the network is very slow and keeps dropping today",["network","dropping"],"vấn đề"),
   ("can you ping the server to check the connection",["ping","connection"],"yêu cầu"),
   ("the dns lookup failed so the host is unreachable",["dns","host"],"sự cố"),
   ("all of our traffic goes through the company proxy",["traffic","proxy"],"cấu hình"),
  ],
 },
 {
  "title":"Linux & terminal",
  "vocab":[
   ("terminal","/ˈtɜːrmɪnəl/","n","cửa sổ dòng lệnh","Open the <b>terminal</b> and type this.","Mở terminal rồi gõ cái này."),
   ("command","/kəˈmænd/","n","câu lệnh","This <b>command</b> deletes the folder.","Câu lệnh này xóa thư mục."),
   ("directory","/dəˈrektəri/","n","thư mục","Change to the right <b>directory</b> first.","Chuyển vào đúng thư mục trước."),
   ("script","/skrɪpt/","n","tập lệnh","Run the deploy <b>script</b>.","Chạy script deploy."),
   ("path","/pæθ/","n","đường dẫn","The file <b>path</b> is wrong.","Đường dẫn file bị sai."),
   ("process","/ˈprɑːses/","n","tiến trình","This <b>process</b> uses all the CPU.","Tiến trình này dùng hết CPU."),
   ("shell","/ʃel/","n","trình dòng lệnh","I use the bash <b>shell</b>.","Mình dùng bash shell."),
   ("sudo","/ˈsuːduː/","n","quyền quản trị","You need <b>sudo</b> to install this.","Bạn cần sudo để cài cái này."),
   ("grep","/ɡrep/","v","tìm trong văn bản","Use <b>grep</b> to find the error.","Dùng grep để tìm lỗi."),
   ("kill","/kɪl/","v","kết thúc tiến trình","Please <b>kill</b> the stuck process.","Kill tiến trình bị treo giúp nhé."),
  ],
  "phrases":[
   ("Open the terminal please.","Mở terminal giúp nhé.",""),
   ("This command failed.","Câu lệnh này lỗi.",""),
   ("The file path is wrong.","Đường dẫn file bị sai.",""),
   ("You need sudo for this.","Bạn cần sudo cho cái này.",""),
   ("Please kill the stuck process.","Kill tiến trình bị treo giúp nhé.",""),
  ],
  "dialogues":[
   ("Why does the command fail?",[
     ("You don't have permission for that folder.",True,"Câu rõ ràng."),
     ("You not have permission that folder.",False,"Thiếu 'do' và 'for'."),
     ("Fail because folder permission no.",False,"Sai ngữ pháp."),
   ]),
   ("The app is using all the CPU.",[
     ("Let me kill the stuck process.",True,"Câu tự nhiên."),
     ("Let me killing the stuck process.",False,"Sai dạng động từ."),
     ("CPU high, process kill I.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("open the terminal and run the deploy script now",["terminal","script"],"hướng dẫn"),
   ("the file path is wrong so the command fails",["path","command"],"vấn đề"),
   ("you need sudo to install this package on linux",["sudo","install"],"yêu cầu"),
   ("please kill the stuck process that eats all cpu",["kill","process"],"hành động"),
  ],
 },
 {
  "title":"Debug nâng cao",
  "vocab":[
   ("bug","/bʌɡ/","n","lỗi phần mềm","I found the <b>bug</b> in the parser.","Mình tìm ra bug trong parser."),
   ("breakpoint","/ˈbreɪkpɔɪnt/","n","điểm dừng gỡ lỗi","Set a <b>breakpoint</b> on this line.","Đặt breakpoint ở dòng này."),
   ("reproduce","/ˌriːprəˈduːs/","v","tái hiện lỗi","I can't <b>reproduce</b> the bug.","Mình không tái hiện được bug."),
   ("exception","/ɪkˈsepʃən/","n","ngoại lệ","The code throws an <b>exception</b>.","Code ném ra một exception."),
   ("crash","/kræʃ/","v","sập chương trình","The app <b>crashes</b> on startup.","App crash khi khởi động."),
   ("inspect","/ɪnˈspekt/","v","xem xét kỹ","Let me <b>inspect</b> the variables.","Để mình inspect các biến."),
   ("stacktrace","/ˈstæktreɪs/","n","vết ngăn xếp lỗi","Send me the full <b>stacktrace</b>.","Gửi mình full stacktrace."),
   ("debugger","/diːˈbʌɡər/","n","công cụ gỡ lỗi","Open the <b>debugger</b> and step through.","Mở debugger và chạy từng bước."),
   ("variable","/ˈveriəbəl/","n","biến","This <b>variable</b> is null here.","Biến này bị null ở đây."),
   ("input","/ˈɪnpʊt/","n","dữ liệu đầu vào","The bug happens with empty <b>input</b>.","Bug xảy ra khi input rỗng."),
  ],
  "phrases":[
   ("I can't reproduce the bug.","Mình không tái hiện được bug.",""),
   ("Send me the stack trace.","Gửi mình stack trace.",""),
   ("The app crashes on startup.","App crash khi khởi động.",""),
   ("Let me set a breakpoint.","Để mình đặt breakpoint.",""),
   ("This variable is null.","Biến này bị null.",""),
  ],
  "dialogues":[
   ("Can you fix this crash?",[
     ("First I need to reproduce the bug.",True,"Câu rõ ràng."),
     ("First I need reproduce the bug.",False,"Thiếu 'to'."),
     ("Fix crash but bug I no see.",False,"Sai ngữ pháp."),
   ]),
   ("What causes the error?",[
     ("The variable is null when the input is empty.",True,"Câu tự nhiên."),
     ("The variable null when input empty.",False,"Thiếu động từ 'is'."),
     ("Error because variable no value.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("i cannot reproduce this bug on my own machine",["reproduce","bug"],"vấn đề"),
   ("please send me the full stacktrace from the crash",["stacktrace","crash"],"yêu cầu"),
   ("set a breakpoint here and inspect all the variables",["breakpoint","inspect"],"hướng dẫn"),
   ("the bug happens only when the input is empty",["bug","input"],"điều kiện"),
  ],
 },
 {
  "title":"Refactoring & chất lượng code",
  "vocab":[
   ("refactor","/riːˈfæktər/","v","tái cấu trúc code","We should <b>refactor</b> this class.","Mình nên refactor class này."),
   ("duplicate","/ˈduːplɪkət/","adj","trùng lặp","There is a lot of <b>duplicate</b> code.","Có nhiều code trùng lặp."),
   ("readable","/ˈriːdəbəl/","adj","dễ đọc","This code is not <b>readable</b>.","Code này khó đọc."),
   ("maintainable","/meɪnˈteɪnəbəl/","adj","dễ bảo trì","Clean code is more <b>maintainable</b>.","Code sạch thì dễ bảo trì hơn."),
   ("naming","/ˈneɪmɪŋ/","n","cách đặt tên","The <b>naming</b> here is confusing.","Cách đặt tên ở đây khó hiểu."),
   ("complexity","/kəmˈpleksəti/","n","độ phức tạp","This function has high <b>complexity</b>.","Hàm này có độ phức tạp cao."),
   ("review","/rɪˈvjuː/","n","rà soát code","Please request a code <b>review</b>.","Nhờ review code giúp nhé."),
   ("cleanup","/ˈkliːnʌp/","n","dọn dẹp code","This needs a small <b>cleanup</b>.","Cái này cần dọn dẹp một chút."),
   ("smell","/smel/","n","dấu hiệu code xấu","This is a classic code <b>smell</b>.","Đây là một code smell điển hình."),
   ("lint","/lɪnt/","v","kiểm tra chuẩn code","Please <b>lint</b> the file before you push.","Lint file trước khi push nhé."),
  ],
  "phrases":[
   ("This code is hard to read.","Code này khó đọc.",""),
   ("We should refactor this.","Mình nên refactor cái này.",""),
   ("There is too much duplicate code.","Code trùng lặp nhiều quá.",""),
   ("Please request a review.","Nhờ review giúp nhé.",""),
   ("The naming is confusing.","Cách đặt tên khó hiểu.",""),
  ],
  "dialogues":[
   ("This function is hard to understand.",[
     ("Yes, we should refactor it soon.",True,"Câu tự nhiên."),
     ("Yes, we should refactoring it soon.",False,"Sai dạng động từ."),
     ("Yes, function bad refactor need.",False,"Sai ngữ pháp."),
   ]),
   ("Why is the code so messy?",[
     ("There is a lot of duplicate code.",True,"Câu rõ ràng."),
     ("There is a lot of duplicate codes.",False,"'code' không đếm được, không thêm 's'."),
     ("Messy because code copy many.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("this class is too big so we should refactor",["class","refactor"],"vấn đề"),
   ("there is too much duplicate code in this file",["duplicate","file"],"vấn đề"),
   ("please request a code review before you merge it",["review","merge"],"quy trình"),
   ("the naming in this function is really confusing today",["naming","function"],"nhận xét"),
  ],
 },
 {
  "title":"Dữ liệu & phân tích",
  "vocab":[
   ("data","/ˈdeɪtə/","n","dữ liệu","The <b>data</b> looks wrong here.","Dữ liệu ở đây nhìn sai."),
   ("dataset","/ˈdeɪtəset/","n","bộ dữ liệu","This <b>dataset</b> is too big.","Bộ dữ liệu này lớn quá."),
   ("report","/rɪˈpɔːrt/","n","báo cáo","I sent the sales <b>report</b>.","Mình gửi báo cáo doanh số rồi."),
   ("chart","/tʃɑːrt/","n","biểu đồ","Add a <b>chart</b> for the trend.","Thêm biểu đồ cho xu hướng."),
   ("filter","/ˈfɪltər/","v","lọc","Please <b>filter</b> by last month.","Lọc theo tháng trước giúp nhé."),
   ("aggregate","/ˈæɡrɪɡeɪt/","v","gom nhóm tổng hợp","We <b>aggregate</b> the data by day.","Mình tổng hợp dữ liệu theo ngày."),
   ("column","/ˈkɑːləm/","n","cột","This <b>column</b> has empty values.","Cột này có giá trị rỗng."),
   ("row","/roʊ/","n","hàng","Each <b>row</b> is one order.","Mỗi hàng là một đơn hàng."),
   ("insight","/ˈɪnsaɪt/","n","thông tin hữu ích","The report gives good <b>insights</b>.","Báo cáo cho nhiều insight hay."),
   ("trend","/trend/","n","xu hướng","Sales show an upward <b>trend</b>.","Doanh số cho thấy xu hướng tăng."),
  ],
  "phrases":[
   ("The data looks wrong.","Dữ liệu nhìn sai.",""),
   ("Can you filter by last month?","Bạn lọc theo tháng trước được không?",""),
   ("Please add a chart here.","Thêm biểu đồ ở đây nhé.",""),
   ("This column is empty.","Cột này rỗng.",""),
   ("The report shows a good trend.","Báo cáo cho thấy xu hướng tốt.",""),
  ],
  "dialogues":[
   ("Can you show sales by month?",[
     ("Sure, I'll add a chart to the report.",True,"Câu tự nhiên có 'will'."),
     ("Sure, I add chart to report.",False,"Thiếu 'will' và mạo từ."),
     ("Sure, chart month sales I make.",False,"Sai trật tự từ."),
   ]),
   ("Why does the total look wrong?",[
     ("This column has some empty values.",True,"Câu rõ ràng."),
     ("This column have some empty value.",False,"Sai chia động từ và số nhiều."),
     ("Total wrong because data bad.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("please filter the data by only last month sales",["filter","data"],"yêu cầu"),
   ("this column has many empty values in the dataset",["column","dataset"],"vấn đề dữ liệu"),
   ("the report shows a strong upward trend this quarter",["report","trend"],"phân tích"),
   ("we aggregate all of the orders by day here",["aggregate","day"],"cách xử lý"),
  ],
 },
 {
  "title":"Machine learning cơ bản",
  "vocab":[
   ("model","/ˈmɑːdəl/","n","mô hình","The <b>model</b> is not accurate yet.","Mô hình chưa chính xác."),
   ("training","/ˈtreɪnɪŋ/","n","huấn luyện","The <b>training</b> took two hours.","Huấn luyện mất hai tiếng."),
   ("feature","/ˈfiːtʃər/","n","đặc trưng đầu vào","Add more <b>features</b> to the model.","Thêm feature cho mô hình."),
   ("predict","/prɪˈdɪkt/","v","dự đoán","The model can <b>predict</b> the price.","Mô hình có thể dự đoán giá."),
   ("accuracy","/ˈækjərəsi/","n","độ chính xác","The <b>accuracy</b> is around ninety percent.","Độ chính xác khoảng chín mươi phần trăm."),
   ("label","/ˈleɪbəl/","n","nhãn dữ liệu","Each row needs a <b>label</b>.","Mỗi hàng cần một nhãn."),
   ("overfitting","/ˌoʊvərˈfɪtɪŋ/","n","quá khớp","The model shows <b>overfitting</b>.","Mô hình bị overfitting."),
   ("algorithm","/ˈælɡərɪðəm/","n","thuật toán","We changed the <b>algorithm</b>.","Mình đổi thuật toán."),
   ("inference","/ˈɪnfərəns/","n","suy luận dự đoán","The <b>inference</b> is very fast now.","Inference bây giờ rất nhanh."),
   ("dataset","/ˈdeɪtəset/","n","bộ dữ liệu","We need a bigger <b>dataset</b>.","Mình cần bộ dữ liệu lớn hơn."),
  ],
  "phrases":[
   ("The model is not accurate.","Mô hình chưa chính xác.",""),
   ("We need more training data.","Mình cần thêm dữ liệu huấn luyện.",""),
   ("The accuracy went up.","Độ chính xác tăng rồi.",""),
   ("The model can predict the price.","Mô hình dự đoán được giá.",""),
   ("This looks like overfitting.","Cái này giống overfitting.",""),
  ],
  "dialogues":[
   ("Why is the model so bad on new data?",[
     ("It looks like overfitting to me.",True,"Câu tự nhiên."),
     ("It look like overfitting to me.",False,"Thiếu 's' ở 'looks'."),
     ("Bad because model learn too much.",False,"Sai ngữ pháp."),
   ]),
   ("How can we improve accuracy?",[
     ("We need a bigger training dataset.",True,"Câu rõ ràng."),
     ("We need bigger training dataset.",False,"Thiếu mạo từ 'a'."),
     ("Accuracy up need data more.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the model is not accurate on the new data",["model","accurate"],"vấn đề"),
   ("we need a much bigger dataset for better training",["dataset","training"],"giải pháp"),
   ("the model can predict the price with high accuracy",["predict","accuracy"],"khả năng"),
   ("each row in the dataset needs a clear label",["row","label"],"yêu cầu dữ liệu"),
  ],
 },
 {
  "title":"Email công việc",
  "vocab":[
   ("email","/ˈiːmeɪl/","n","thư điện tử","I sent you an <b>email</b> this morning.","Sáng nay mình gửi bạn một email."),
   ("subject","/ˈsʌbdʒɪkt/","n","tiêu đề thư","The <b>subject</b> line is empty.","Tiêu đề thư đang trống."),
   ("attachment","/əˈtætʃmənt/","n","tệp đính kèm","You forgot the <b>attachment</b>.","Bạn quên file đính kèm rồi."),
   ("reply","/rɪˈplaɪ/","v","trả lời","Please <b>reply</b> by end of day.","Trả lời trước cuối ngày nhé."),
   ("forward","/ˈfɔːrwərd/","v","chuyển tiếp","Can you <b>forward</b> me that email?","Bạn chuyển tiếp email đó cho mình được không?"),
   ("recipient","/rɪˈsɪpiənt/","n","người nhận","Add her as a <b>recipient</b>.","Thêm cô ấy vào người nhận."),
   ("draft","/dræft/","n","bản nháp","The email is still a <b>draft</b>.","Email vẫn còn là bản nháp."),
   ("followup","/ˈfɑːloʊʌp/","n","thư nhắc lại","I sent a <b>followup</b> yesterday.","Hôm qua mình gửi thư nhắc lại."),
   ("deadline","/ˈdedlaɪn/","n","hạn chót","Please note the <b>deadline</b> in the email.","Nhớ hạn chót trong email nhé."),
   ("regards","/rɪˈɡɑːrdz/","n","lời chào cuối thư","End the email with best <b>regards</b>.","Kết email bằng best regards."),
  ],
  "phrases":[
   ("I sent you an email.","Mình gửi bạn email rồi.",""),
   ("You forgot the attachment.","Bạn quên file đính kèm.",""),
   ("Please reply by end of day.","Trả lời trước cuối ngày nhé.",""),
   ("Can you forward me that email?","Bạn chuyển tiếp email đó cho mình được không?",""),
   ("I will follow up tomorrow.","Mai mình sẽ nhắc lại.",""),
  ],
  "dialogues":[
   ("Did you get my email?",[
     ("Yes, but you forgot the attachment.",True,"Câu tự nhiên."),
     ("Yes, but you forget the attachment.",False,"Sai thì, phải là 'forgot'."),
     ("Yes, but attachment no have.",False,"Sai ngữ pháp."),
   ]),
   ("When do you need my reply?",[
     ("Please reply by the end of the day.",True,"Câu rõ ràng."),
     ("Please reply by end the day.",False,"Sai trật tự và thiếu mạo từ."),
     ("Reply you fast today need.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("i sent you an email but forgot the attachment",["email","attachment"],"sự cố"),
   ("please reply to this email by end of day",["reply","email"],"yêu cầu"),
   ("can you forward that message to the whole team",["forward","team"],"yêu cầu"),
   ("i will send a followup before the friday deadline",["followup","deadline"],"kế hoạch"),
  ],
 },
 {
  "title":"Chat & Slack công việc",
  "vocab":[
   ("channel","/ˈtʃænəl/","n","kênh trò chuyện","Post it in the dev <b>channel</b>.","Đăng vào channel dev nhé."),
   ("mention","/ˈmenʃən/","v","nhắc tên","Please <b>mention</b> me in the thread.","Nhắc tên mình trong thread nhé."),
   ("thread","/θred/","n","luồng trả lời","Let's keep it in this <b>thread</b>.","Mình giữ trong thread này nhé."),
   ("ping","/pɪŋ/","v","nhắn nhắc","Just <b>ping</b> me if you need help.","Cần giúp cứ ping mình."),
   ("reply","/rɪˈplaɪ/","v","trả lời","I'll <b>reply</b> in a minute.","Mình trả lời trong một phút nữa."),
   ("emoji","/ɪˈmoʊdʒi/","n","biểu tượng cảm xúc","React with a thumbs up <b>emoji</b>.","React bằng emoji thumbs up nhé."),
   ("status","/ˈsteɪtəs/","n","trạng thái","Set your <b>status</b> to away.","Đặt status của bạn thành away."),
   ("notification","/ˌnoʊtɪfɪˈkeɪʃən/","n","thông báo","I missed your <b>notification</b>.","Mình bỏ lỡ thông báo của bạn."),
   ("dm","/ˌdiːˈem/","n","tin nhắn riêng","Send me a <b>dm</b> about it.","Nhắn dm cho mình về việc đó."),
   ("message","/ˈmesɪdʒ/","n","tin nhắn","I saw your <b>message</b> now.","Mình vừa thấy tin nhắn của bạn."),
  ],
  "phrases":[
   ("Ping me if you need help.","Cần giúp cứ ping mình.",""),
   ("Let's keep it in this thread.","Mình giữ trong thread này nhé.",""),
   ("I'll reply in a minute.","Mình trả lời trong một phút nữa.",""),
   ("Please post it in the channel.","Đăng vào channel giúp nhé.",""),
   ("Sorry, I missed your message.","Xin lỗi, mình bỏ lỡ tin nhắn của bạn.",""),
  ],
  "dialogues":[
   ("Can you help me with this?",[
     ("Sure, just ping me in the channel.",True,"Câu tự nhiên."),
     ("Sure, just ping me in channel.",False,"Thiếu mạo từ 'the'."),
     ("Sure, channel me ping you.",False,"Sai trật tự từ."),
   ]),
   ("Did you see my message?",[
     ("Sorry, I missed it, I'll reply now.",True,"Câu tự nhiên."),
     ("Sorry, I miss it, I reply now.",False,"Sai thì và thiếu 'will'."),
     ("Sorry, message I no see.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("please post this update in the dev team channel",["post","channel"],"yêu cầu"),
   ("just ping me in the thread if you need",["ping","thread"],"lời mời giúp"),
   ("sorry i missed your message during the long meeting",["missed","message"],"xin lỗi"),
   ("please mention me next time in that busy thread",["mention","thread"],"yêu cầu"),
  ],
 },
 {
  "title":"Phỏng vấn & CV",
  "vocab":[
   ("interview","/ˈɪntərvjuː/","n","phỏng vấn","The <b>interview</b> is tomorrow at ten.","Buổi phỏng vấn ngày mai lúc mười giờ."),
   ("resume","/ˈrezʊmeɪ/","n","sơ yếu lý lịch","Please send your <b>resume</b>.","Gửi CV của bạn nhé."),
   ("experience","/ɪkˈspɪriəns/","n","kinh nghiệm","I have three years of <b>experience</b>.","Mình có ba năm kinh nghiệm."),
   ("skill","/skɪl/","n","kỹ năng","Python is my strongest <b>skill</b>.","Python là kỹ năng mạnh nhất của mình."),
   ("position","/pəˈzɪʃən/","n","vị trí công việc","I applied for the backend <b>position</b>.","Mình ứng tuyển vị trí backend."),
   ("candidate","/ˈkændɪdeɪt/","n","ứng viên","She is a strong <b>candidate</b>.","Cô ấy là một ứng viên mạnh."),
   ("offer","/ˈɔːfər/","n","lời mời làm việc","I got a job <b>offer</b> today.","Hôm nay mình nhận được offer."),
   ("salary","/ˈsæləri/","n","lương","What is the <b>salary</b> range?","Mức lương khoảng bao nhiêu?"),
   ("hire","/ˈhaɪər/","v","tuyển dụng","We want to <b>hire</b> two developers.","Mình muốn tuyển hai developer."),
   ("portfolio","/pɔːrtˈfoʊlioʊ/","n","hồ sơ dự án","Show me your <b>portfolio</b>.","Cho mình xem portfolio của bạn."),
  ],
  "phrases":[
   ("The interview is tomorrow.","Phỏng vấn ngày mai.",""),
   ("Please send your resume.","Gửi CV của bạn nhé.",""),
   ("I have three years of experience.","Mình có ba năm kinh nghiệm.",""),
   ("What is the salary range?","Mức lương khoảng bao nhiêu?",""),
   ("I got a job offer.","Mình nhận được offer rồi.",""),
  ],
  "dialogues":[
   ("Tell me about your experience.",[
     ("I have three years of backend experience.",True,"Câu rõ ràng."),
     ("I have three year backend experience.",False,"Thiếu 's' ở 'years'."),
     ("Experience I backend three year.",False,"Sai trật tự từ."),
   ]),
   ("Why do you want this position?",[
     ("I want to grow my backend skills.",True,"Câu tự nhiên."),
     ("I want grow my backend skill.",False,"Thiếu 'to' và số nhiều."),
     ("Position I like grow skill.",False,"Sai ngữ pháp."),
   ]),
  ],
  "listen":[
   ("the interview is tomorrow morning at exactly ten oclock",["interview","tomorrow"],"lịch"),
   ("please send me your resume before the friday deadline",["resume","deadline"],"yêu cầu"),
   ("i have three years of solid backend developer experience",["years","experience"],"giới thiệu"),
   ("we want to hire two more backend developers soon",["hire","developers"],"kế hoạch"),
  ],
 },
 {
  "title":"Nghỉ phép & hành chính",
  "vocab":[
   ("leave","/liːv/","n","nghỉ phép","I want to take a day of <b>leave</b>.","Mình muốn xin nghỉ một ngày."),
   ("vacation","/veɪˈkeɪʃən/","n","kỳ nghỉ","I'm on <b>vacation</b> next week.","Tuần sau mình đi nghỉ."),
   ("request","/rɪˈkwest/","v","xin, đề nghị","Please <b>request</b> leave in the system.","Xin nghỉ trên hệ thống nhé."),
   ("approve","/əˈpruːv/","v","phê duyệt","My manager will <b>approve</b> it.","Sếp mình sẽ duyệt."),
   ("sick","/sɪk/","adj","ốm, bệnh","I'm <b>sick</b> today and staying home.","Hôm nay mình ốm nên ở nhà."),
   ("holiday","/ˈhɑːlədeɪ/","n","ngày lễ","Monday is a public <b>holiday</b>.","Thứ Hai là ngày lễ."),
   ("timesheet","/ˈtaɪmʃiːt/","n","bảng chấm công","Please fill in your <b>timesheet</b>.","Điền bảng chấm công nhé."),
   ("remote","/rɪˈmoʊt/","adj","làm từ xa","I work <b>remote</b> on Fridays.","Thứ Sáu mình làm từ xa."),
   ("absence","/ˈæbsəns/","n","sự vắng mặt","Report your <b>absence</b> early.","Báo vắng mặt sớm nhé."),
   ("cover","/ˈkʌvər/","v","làm thay","Can you <b>cover</b> my work tomorrow?","Mai bạn làm thay mình được không?"),
  ],
  "phrases":[
   ("I want to take a day off.","Mình muốn xin nghỉ một ngày.",""),
   ("I'm sick today.","Hôm nay mình ốm.",""),
   ("Please approve my leave.","Duyệt phép giúp mình nhé.",""),
   ("I work remote on Fridays.","Thứ Sáu mình làm từ xa.",""),
   ("Can you cover for me tomorrow?","Mai bạn làm thay mình được không?",""),
  ],
  "dialogues":[
   ("Are you coming to the office tomorrow?",[
     ("No, I'll work remote tomorrow.",True,"Câu tự nhiên."),
     ("No, I work remote tomorrow.",False,"Thiếu 'will'."),
     ("No, tomorrow remote I work can.",False,"Sai trật tự từ."),
   ]),
   ("Can I take Friday off?",[
     ("Sure, just request it in the system.",True,"Câu rõ ràng."),
     ("Sure, just request it in system.",False,"Thiếu mạo từ 'the'."),
     ("Sure, Friday off you request must.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("i want to take one day of leave tomorrow",["leave","tomorrow"],"yêu cầu"),
   ("please approve my vacation request in the hr system",["approve","vacation"],"yêu cầu"),
   ("i am sick today so i will stay home",["sick","home"],"thông báo"),
   ("can you cover my work while i am away",["cover","away"],"nhờ vả"),
  ],
 },
 {
  "title":"Đánh giá & phản hồi (performance review)",
  "vocab":[
   ("feedback","/ˈfiːdbæk/","n","phản hồi","Thanks for the honest <b>feedback</b>.","Cảm ơn phản hồi thẳng thắn."),
   ("review","/rɪˈvjuː/","n","buổi đánh giá","My performance <b>review</b> is next week.","Buổi đánh giá của mình tuần sau."),
   ("goal","/ɡoʊl/","n","mục tiêu","What is your <b>goal</b> this quarter?","Mục tiêu quý này của bạn là gì?"),
   ("strength","/streŋθ/","n","điểm mạnh","Teamwork is a real <b>strength</b>.","Làm việc nhóm là một điểm mạnh."),
   ("improvement","/ɪmˈpruːvmənt/","n","điểm cần cải thiện","There is room for <b>improvement</b>.","Vẫn còn chỗ để cải thiện."),
   ("rating","/ˈreɪtɪŋ/","n","mức đánh giá","I got a good <b>rating</b> this year.","Năm nay mình được đánh giá tốt."),
   ("progress","/ˈprɑːɡres/","n","tiến bộ","You made great <b>progress</b>.","Bạn tiến bộ nhiều."),
   ("expectation","/ˌekspekˈteɪʃən/","n","kỳ vọng","You met all the <b>expectations</b>.","Bạn đạt hết kỳ vọng."),
   ("promotion","/prəˈmoʊʃən/","n","thăng chức","She got a <b>promotion</b> last month.","Tháng trước cô ấy được thăng chức."),
   ("achievement","/əˈtʃiːvmənt/","n","thành tựu","List your main <b>achievements</b>.","Liệt kê các thành tựu chính."),
  ],
  "phrases":[
   ("Thanks for the feedback.","Cảm ơn phản hồi nhé.",""),
   ("My review is next week.","Buổi đánh giá của mình tuần sau.",""),
   ("You made great progress.","Bạn tiến bộ nhiều.",""),
   ("There is room for improvement.","Vẫn còn chỗ để cải thiện.",""),
   ("What is your goal this quarter?","Mục tiêu quý này của bạn là gì?",""),
  ],
  "dialogues":[
   ("How was your performance review?",[
     ("It went well, I got a good rating.",True,"Câu đúng thì."),
     ("It go well, I get good rating.",False,"Sai thì và thiếu mạo từ."),
     ("Review good, rating I get nice.",False,"Sai ngữ pháp."),
   ]),
   ("What should I work on next?",[
     ("You made progress, but keep improving your tests.",True,"Câu tự nhiên."),
     ("You made progress, but keep improve your test.",False,"Sai dạng động từ và số nhiều."),
     ("Next you tests better must do.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("thanks for the honest feedback about my recent work",["feedback","work"],"lời cảm ơn"),
   ("my performance review is scheduled for early next week",["review","week"],"lịch"),
   ("you made great progress but there is more improvement",["progress","improvement"],"nhận xét"),
   ("she got a well deserved promotion just last month",["promotion","month"],"tin vui"),
  ],
 },
 {
  "title":"Khách hàng & hỗ trợ",
  "vocab":[
   ("customer","/ˈkʌstəmər/","n","khách hàng","The <b>customer</b> is not happy.","Khách hàng không hài lòng."),
   ("issue","/ˈɪʃuː/","n","vấn đề","The <b>issue</b> is now fixed.","Vấn đề đã được sửa."),
   ("resolve","/rɪˈzɑːlv/","v","giải quyết","We will <b>resolve</b> it today.","Mình sẽ giải quyết trong hôm nay."),
   ("refund","/ˈriːfʌnd/","n","hoàn tiền","The customer wants a <b>refund</b>.","Khách hàng muốn hoàn tiền."),
   ("complaint","/kəmˈpleɪnt/","n","khiếu nại","We got a <b>complaint</b> about the app.","Mình nhận một khiếu nại về app."),
   ("escalate","/ˈeskəleɪt/","v","chuyển lên cấp cao","Let's <b>escalate</b> this to the manager.","Mình chuyển việc này lên sếp."),
   ("satisfaction","/ˌsætɪsˈfækʃən/","n","sự hài lòng","Customer <b>satisfaction</b> is our goal.","Sự hài lòng của khách là mục tiêu."),
   ("support","/səˈpɔːrt/","n","hỗ trợ","Please contact the <b>support</b> team.","Liên hệ đội support nhé."),
   ("urgent","/ˈɜːrdʒənt/","adj","khẩn cấp","This ticket is very <b>urgent</b>.","Ticket này rất khẩn."),
   ("apologize","/əˈpɑːlədʒaɪz/","v","xin lỗi","We should <b>apologize</b> for the delay.","Mình nên xin lỗi vì sự chậm trễ."),
  ],
  "phrases":[
   ("The customer is not happy.","Khách hàng không hài lòng.",""),
   ("We will resolve it today.","Mình sẽ giải quyết hôm nay.",""),
   ("This ticket is urgent.","Ticket này khẩn.",""),
   ("Please contact the support team.","Liên hệ đội support nhé.",""),
   ("We should apologize for the delay.","Mình nên xin lỗi vì sự chậm trễ.",""),
  ],
  "dialogues":[
   ("The customer is very angry.",[
     ("Let's escalate this to the manager.",True,"Câu tự nhiên."),
     ("Let's escalate this to manager.",False,"Thiếu mạo từ 'the'."),
     ("Angry customer, manager we tell.",False,"Sai ngữ pháp."),
   ]),
   ("When will the issue be fixed?",[
     ("We will resolve it by today.",True,"Câu rõ ràng."),
     ("We will resolving it by today.",False,"Sai dạng động từ."),
     ("Issue fix today we can.",False,"Sai trật tự từ."),
   ]),
  ],
  "listen":[
   ("the customer is not happy about the slow refund",["customer","refund"],"vấn đề"),
   ("we will resolve this urgent issue by end today",["resolve","issue"],"cam kết"),
   ("please escalate this complaint to the support team lead",["escalate","complaint"],"hành động"),
   ("we should apologize to the customer for the delay",["apologize","delay"],"lời khuyên"),
  ],
 },
]
