# -*- coding: utf-8 -*-
# ~1000 câu tiếng Anh IT/công sở thường dùng, chia nhóm. Mức cơ bản, đủ dùng hằng ngày.
# Mỗi câu: (english, vietnamese)
GROUPS = []
def G(name, pairs): GROUPS.append((name, pairs))

G("Chào hỏi & mở đầu ngày", [
 ("Good morning, everyone.","Chào buổi sáng cả nhà."),
 ("Morning! How's it going?","Chào buổi sáng! Mọi việc ổn chứ?"),
 ("Hi team, hope you had a good weekend.","Chào team, chúc mọi người cuối tuần vui."),
 ("How are you doing today?","Hôm nay bạn thế nào?"),
 ("Are you free to talk now?","Bạn rảnh nói chuyện bây giờ không?"),
 ("Do you have a minute?","Bạn có một phút không?"),
 ("Can I ask you something quick?","Mình hỏi nhanh một chút được không?"),
 ("Sorry to bother you.","Xin lỗi làm phiền bạn."),
 ("Is now a good time?","Giờ có tiện không?"),
 ("Let me know when you're free.","Khi nào rảnh báo mình nhé."),
 ("Thanks for joining.","Cảm ơn đã tham gia."),
 ("Let's get started.","Bắt đầu thôi."),
 ("Shall we begin?","Mình bắt đầu nhé?"),
 ("Can everyone hear me?","Mọi người nghe mình rõ không?"),
 ("Can you see my screen?","Bạn thấy màn hình mình không?"),
 ("Give me a second to share my screen.","Đợi mình một chút để chia sẻ màn hình."),
 ("Sorry, I was on mute.","Xin lỗi, mình quên bật mic."),
 ("You're on mute.","Bạn đang tắt mic đấy."),
 ("Can you speak up a little?","Bạn nói to hơn một chút được không?"),
 ("Sorry, you're breaking up.","Xin lỗi, tiếng bạn bị đứt quãng."),
 ("Let me turn on my camera.","Để mình bật camera."),
 ("Nice to meet you.","Rất vui được gặp bạn."),
 ("Nice to e-meet you.","Rất vui được làm quen (qua mạng)."),
 ("How was your weekend?","Cuối tuần của bạn thế nào?"),
 ("Long time no see.","Lâu rồi không gặp."),
 ("Welcome to the team!","Chào mừng bạn vào team!"),
 ("Let me introduce myself.","Để mình tự giới thiệu."),
 ("I'm a backend developer.","Mình là lập trình viên backend."),
 ("I've been here for two years.","Mình làm ở đây hai năm rồi."),
 ("I work on the payment team.","Mình làm ở team thanh toán."),
 ("Feel free to ask me anything.","Cứ hỏi mình bất cứ điều gì nhé."),
 ("Let's have a quick sync.","Mình sync nhanh một chút nhé."),
 ("Ready when you are.","Bạn sẵn sàng là mình bắt đầu."),
 ("Can we start in five minutes?","Năm phút nữa mình bắt đầu được không?"),
 ("I'll be right back.","Mình quay lại ngay."),
 ("Sorry I'm late.","Xin lỗi mình đến muộn."),
 ("Thanks for waiting.","Cảm ơn đã đợi."),
 ("Let's wait a minute for the others.","Đợi một phút cho mọi người vào đã."),
 ("Good to see you all.","Vui khi gặp mọi người."),
 ("Let's dive in.","Vào việc thôi."),
])

G("Standup — báo tiến độ", [
 ("Yesterday I finished the login API.","Hôm qua mình xong API login."),
 ("Today I'll work on the payment module.","Hôm nay mình làm module thanh toán."),
 ("No blockers from my side.","Phía mình không có gì vướng."),
 ("I have one blocker.","Mình có một chỗ đang bị vướng."),
 ("I'm still working on the same task.","Mình vẫn đang làm task hôm qua."),
 ("I'm about halfway done.","Mình làm được khoảng một nửa."),
 ("It's almost done.","Sắp xong rồi."),
 ("I'll finish it by end of day.","Cuối ngày mình sẽ xong."),
 ("I need one more day for this.","Mình cần thêm một ngày cho cái này."),
 ("I picked up a new task this morning.","Sáng nay mình nhận thêm một task mới."),
 ("I'm blocked by the staging environment.","Mình bị chặn vì môi trường staging."),
 ("I'm waiting for the API to be ready.","Mình đang chờ API sẵn sàng."),
 ("I'm waiting for a code review.","Mình đang chờ review code."),
 ("Nothing much to report today.","Hôm nay không có gì nhiều để báo."),
 ("Same as yesterday, still in progress.","Vẫn như hôm qua, đang làm tiếp."),
 ("I fixed the bug from yesterday.","Mình đã sửa lỗi hôm qua."),
 ("I'll pick up the next ticket after this.","Xong cái này mình lấy ticket tiếp."),
 ("I'm testing it now.","Mình đang test."),
 ("It's ready for review.","Đã sẵn sàng để review."),
 ("I'll deploy it this afternoon.","Chiều nay mình sẽ deploy."),
 ("Can someone review my pull request?","Có ai review PR của mình không?"),
 ("I might need some help with this.","Mình có thể cần giúp một chút."),
 ("I'll sync with the frontend team today.","Hôm nay mình sẽ trao đổi với team frontend."),
 ("The task took longer than expected.","Task này lâu hơn dự kiến."),
 ("I'm on track to finish this week.","Mình đúng tiến độ, tuần này xong."),
 ("I'm a bit behind on this task.","Task này mình hơi chậm tiến độ."),
 ("Let me quickly update you.","Để mình cập nhật nhanh."),
 ("Here's a quick update.","Đây là cập nhật nhanh."),
 ("That's all from me.","Phần mình vậy thôi."),
 ("Over to you.","Đến lượt bạn."),
 ("I'll hand over to Minh.","Mình chuyển cho Minh."),
 ("I finished the testing.","Mình đã test xong."),
 ("I started on the new feature.","Mình đã bắt đầu tính năng mới."),
 ("I reviewed two pull requests.","Mình đã review hai PR."),
 ("I updated the documentation.","Mình đã cập nhật tài liệu."),
 ("I'll continue with this today.","Hôm nay mình làm tiếp cái này."),
 ("My plan for today is to finish the API.","Kế hoạch hôm nay của mình là xong API."),
 ("I'll focus on bug fixes today.","Hôm nay mình tập trung sửa lỗi."),
 ("I don't have any updates today.","Hôm nay mình không có gì cập nhật."),
 ("Let's move on to the next person.","Chuyển sang người tiếp theo nhé."),
])

G("Hỏi xin giúp đỡ", [
 ("Can you help me with this?","Bạn giúp mình cái này được không?"),
 ("Could you give me a hand?","Bạn giúp mình một tay được không?"),
 ("I'm stuck on this bug.","Mình đang bí ở lỗi này."),
 ("I can't figure this out.","Mình không hiểu ra được."),
 ("Do you have time to look at this?","Bạn có thời gian xem cái này không?"),
 ("Can you take a look when you're free?","Khi nào rảnh bạn xem giúp nhé?"),
 ("I have a quick question.","Mình có một câu hỏi nhanh."),
 ("Sorry, I'm a bit lost here.","Xin lỗi, chỗ này mình hơi rối."),
 ("Could you explain this part?","Bạn giải thích chỗ này được không?"),
 ("How does this function work?","Hàm này hoạt động thế nào?"),
 ("Where should I start?","Mình nên bắt đầu từ đâu?"),
 ("Am I doing this right?","Mình làm vậy đúng chưa?"),
 ("Could you point me in the right direction?","Bạn chỉ mình hướng đi được không?"),
 ("I'm not sure how to fix this.","Mình không chắc cách sửa cái này."),
 ("Can you walk me through it?","Bạn hướng dẫn mình từng bước được không?"),
 ("What am I missing here?","Mình đang thiếu gì ở đây?"),
 ("Could you double-check this for me?","Bạn kiểm tra lại giúp mình được không?"),
 ("Do you know who owns this code?","Bạn biết ai phụ trách code này không?"),
 ("Who should I ask about this?","Cái này mình nên hỏi ai?"),
 ("I've been stuck for an hour.","Mình bí cả tiếng rồi."),
 ("Could you share an example?","Bạn cho mình một ví dụ được không?"),
 ("Is there any documentation for this?","Cái này có tài liệu không?"),
 ("Can you send me the link?","Gửi mình cái link được không?"),
 ("Where can I find the config?","Mình tìm file config ở đâu?"),
 ("How do I set up the project locally?","Mình cài project ở máy local thế nào?"),
 ("Could you review my approach?","Bạn xem cách làm của mình được không?"),
 ("Is this the right way to do it?","Làm thế này đúng cách chưa?"),
 ("I need a second opinion.","Mình cần thêm ý kiến."),
 ("Can we pair on this?","Mình pair với nhau cái này nhé?"),
 ("Could we do a quick call?","Mình gọi nhanh một chút được không?"),
 ("Sorry to keep asking.","Xin lỗi hỏi hoài."),
 ("I don't want to waste your time.","Mình không muốn làm mất thời gian bạn."),
 ("Just to be safe, can you confirm?","Cho chắc, bạn xác nhận giúp nhé?"),
 ("What would you do in my place?","Nếu là bạn thì bạn làm sao?"),
 ("Any idea why this is happening?","Bạn có biết vì sao thế này không?"),
 ("Have you seen this error before?","Bạn gặp lỗi này bao giờ chưa?"),
 ("Could you help me debug this?","Bạn giúp mình debug cái này không?"),
 ("I'll owe you one.","Mình nợ bạn một lần nhé."),
 ("Thanks, that really helps.","Cảm ơn, giúp mình nhiều lắm."),
 ("No rush, whenever you can.","Không gấp đâu, khi nào tiện thôi."),
])

G("Đề nghị giúp & phản hồi", [
 ("Do you need any help?","Bạn cần giúp gì không?"),
 ("Let me help you with that.","Để mình giúp bạn cái đó."),
 ("I can take a look.","Mình xem thử cho."),
 ("Sure, no problem.","Được, không sao."),
 ("Of course, happy to help.","Tất nhiên, sẵn lòng giúp."),
 ("Give me a moment.","Cho mình một chút."),
 ("Let me check and get back to you.","Để mình kiểm tra rồi báo lại."),
 ("I'll look into it.","Mình sẽ xem qua."),
 ("Leave it with me.","Cứ để đó cho mình."),
 ("I'll take care of it.","Mình lo cái này."),
 ("Send it over and I'll check.","Gửi qua mình xem cho."),
 ("Can you share your screen?","Bạn chia sẻ màn hình được không?"),
 ("Let's hop on a call.","Mình gọi nhau nhé."),
 ("Show me the error.","Cho mình xem lỗi nào."),
 ("What have you tried so far?","Bạn đã thử những gì rồi?"),
 ("Have you checked the logs?","Bạn xem log chưa?"),
 ("Try restarting it first.","Thử khởi động lại trước xem."),
 ("It might be a config issue.","Có thể do cấu hình đấy."),
 ("Let me push a fix.","Để mình đẩy một bản sửa."),
 ("I think I know the problem.","Mình nghĩ mình biết vấn đề rồi."),
 ("Here's what you can do.","Bạn có thể làm thế này."),
 ("Try this and let me know.","Thử cái này rồi báo mình."),
 ("Does that make sense?","Vậy có hợp lý không?"),
 ("Let me know if it works.","Nếu chạy được thì báo mình nhé."),
 ("Feel free to ping me anytime.","Cứ nhắn mình bất cứ lúc nào."),
 ("Happy to pair if you want.","Nếu muốn thì mình pair cùng."),
 ("I'll send you an example.","Mình gửi bạn một ví dụ."),
 ("Check this link, it should help.","Xem link này, chắc sẽ giúp được."),
 ("You're on the right track.","Bạn đang đi đúng hướng."),
 ("You almost had it.","Bạn gần đúng rồi."),
 ("Good question, let me think.","Câu hỏi hay, để mình nghĩ."),
 ("I'm not sure either, let's find out.","Mình cũng không chắc, cùng tìm hiểu nhé."),
 ("Let me ask someone who knows.","Để mình hỏi người biết rõ hơn."),
 ("I'll get back to you shortly.","Mình sẽ báo lại bạn sớm."),
 ("Give me ten minutes.","Cho mình mười phút."),
 ("I'm a bit busy now, can it wait?","Giờ mình hơi bận, để lát được không?"),
 ("Let's look at it after lunch.","Ăn trưa xong mình xem nhé."),
 ("Anytime, glad it worked.","Không có gì, mừng là chạy được."),
 ("Let me know if you get stuck again.","Nếu lại bí thì báo mình."),
 ("You can figure it out, you're close.","Bạn làm được mà, gần rồi đấy."),
])

G("Hỏi lại cho rõ (clarify)", [
 ("Sorry, could you say that again?","Xin lỗi, bạn nói lại được không?"),
 ("Could you clarify what you mean?","Bạn nói rõ hơn ý bạn được không?"),
 ("I'm not sure I understand.","Mình chưa chắc đã hiểu."),
 ("What do you mean exactly?","Ý bạn chính xác là gì?"),
 ("Just to confirm, you want A or B?","Xác nhận lại, bạn muốn A hay B?"),
 ("So if I understand correctly...","Vậy nếu mình hiểu đúng thì..."),
 ("Let me make sure I got that.","Để mình chắc là hiểu đúng."),
 ("Can you give me an example?","Cho mình một ví dụ được không?"),
 ("Which one do you mean?","Bạn nói cái nào?"),
 ("Do you mean this or that?","Ý bạn là cái này hay cái kia?"),
 ("Could you be more specific?","Bạn nói cụ thể hơn được không?"),
 ("Sorry, I didn't catch that.","Xin lỗi, mình chưa nghe rõ."),
 ("Could you repeat the last part?","Bạn nhắc lại phần cuối được không?"),
 ("What's the priority here?","Cái nào ưu tiên vậy?"),
 ("Is this urgent?","Cái này gấp không?"),
 ("When do you need this by?","Bạn cần cái này khi nào?"),
 ("Who is responsible for this?","Ai phụ trách cái này?"),
 ("What's the expected result?","Kết quả mong đợi là gì?"),
 ("Am I understanding this right?","Mình hiểu vậy đúng không?"),
 ("Could you explain it differently?","Bạn giải thích cách khác được không?"),
 ("I want to make sure we're aligned.","Mình muốn chắc là mình thống nhất."),
 ("Let me repeat it back to you.","Để mình nhắc lại cho bạn nghe."),
 ("Is that what you meant?","Đó có phải ý bạn không?"),
 ("Correct me if I'm wrong.","Sai thì bạn sửa mình nhé."),
 ("What should the output look like?","Kết quả trông thế nào là đúng?"),
 ("Do you have a screenshot?","Bạn có ảnh chụp màn hình không?"),
 ("Can you show me an example input?","Cho mình xem một ví dụ đầu vào được không?"),
 ("What's the exact requirement?","Yêu cầu chính xác là gì?"),
 ("Sorry, this part is unclear to me.","Xin lỗi, chỗ này mình chưa rõ."),
 ("Could you break it down for me?","Bạn chia nhỏ ra giúp mình được không?"),
 ("Just so we're on the same page...","Để mình chắc là cùng quan điểm..."),
 ("Let me summarize to check.","Để mình tóm lại xem đúng không."),
 ("Does 'done' mean deployed or merged?","'Xong' là đã deploy hay đã merge?"),
 ("Which environment are we talking about?","Mình đang nói môi trường nào?"),
 ("Is this for staging or production?","Cái này cho staging hay production?"),
 ("Can you confirm the deadline?","Bạn xác nhận hạn chót giúp nhé?"),
 ("I might have misunderstood.","Có thể mình hiểu nhầm."),
 ("Let's clarify this before we start.","Làm rõ cái này trước khi bắt đầu nhé."),
 ("What exactly is failing?","Chính xác là chỗ nào lỗi?"),
 ("Could you send it in writing?","Bạn gửi bằng văn bản được không?"),
])

G("Đồng ý & không đồng ý", [
 ("I agree.","Mình đồng ý."),
 ("That makes sense.","Nghe hợp lý đấy."),
 ("Sounds good to me.","Với mình vậy ổn."),
 ("Good idea.","Ý hay đấy."),
 ("I'm fine with that.","Mình ổn với cái đó."),
 ("Let's do it.","Làm thôi."),
 ("I think you're right.","Mình nghĩ bạn đúng."),
 ("Fair enough.","Cũng hợp lý."),
 ("That works for me.","Với mình được đấy."),
 ("I'm on board.","Mình ủng hộ."),
 ("Absolutely.","Chắc chắn rồi."),
 ("No objections from me.","Mình không phản đối gì."),
 ("Let's go with that.","Chốt phương án đó nhé."),
 ("I see your point.","Mình hiểu ý bạn."),
 ("You have a point there.","Bạn nói cũng có lý."),
 ("I'm not sure about that.","Cái đó mình không chắc lắm."),
 ("I have a different opinion.","Mình có ý kiến khác."),
 ("I'm not convinced.","Mình chưa thấy thuyết phục."),
 ("I see it differently.","Mình nhìn khác một chút."),
 ("I don't think that's a good idea.","Mình không nghĩ đó là ý hay."),
 ("Can we consider another option?","Mình xem phương án khác được không?"),
 ("I'd suggest a different approach.","Mình đề xuất cách khác."),
 ("That might cause problems.","Cái đó có thể gây vấn đề."),
 ("Let's think about the risks.","Mình nghĩ về rủi ro đã."),
 ("I understand, but...","Mình hiểu, nhưng mà..."),
 ("I hear you, however...","Mình nghe rồi, tuy nhiên..."),
 ("That's true, but there's a catch.","Đúng vậy, nhưng có một điểm cần lưu ý."),
 ("Let's agree to disagree.","Mình cứ giữ quan điểm riêng nhé."),
 ("Can we find a middle ground?","Mình tìm điểm chung được không?"),
 ("Let's discuss the trade-offs.","Mình bàn về mặt được mất nhé."),
 ("I'd rather not do it that way.","Mình không muốn làm theo cách đó."),
 ("It depends on the situation.","Còn tùy tình huống."),
 ("Maybe, but let's double-check.","Có thể, nhưng kiểm tra lại đã."),
 ("I'm open to other ideas.","Mình sẵn sàng nghe ý khác."),
 ("Let's hear other opinions.","Nghe thêm ý kiến khác nào."),
 ("I'll go with the team's decision.","Mình theo quyết định của team."),
 ("Let's put it to a vote.","Mình biểu quyết đi."),
 ("I partly agree.","Mình đồng ý một phần."),
 ("That's a valid concern.","Đó là lo ngại hợp lý."),
 ("Let's revisit this later.","Mình bàn lại cái này sau nhé."),
])

G("Code review — góp ý", [
 ("This looks good to me.","Cái này mình thấy ổn."),
 ("Nice work!","Làm tốt lắm!"),
 ("Clean and readable.","Code sạch, dễ đọc."),
 ("Just a few small comments.","Chỉ vài góp ý nhỏ thôi."),
 ("Could you add a test for this?","Bạn thêm test cho cái này nhé?"),
 ("Can we rename this variable?","Đổi tên biến này được không?"),
 ("This might break on an empty list.","Cái này có thể lỗi khi list rỗng."),
 ("What happens if the input is null?","Nếu đầu vào là null thì sao?"),
 ("Consider handling this edge case.","Cân nhắc xử lý trường hợp hiếm này."),
 ("This code is a bit hard to read.","Đoạn code này hơi khó đọc."),
 ("Could you add a comment here?","Bạn thêm chú thích ở đây nhé?"),
 ("This looks duplicated.","Chỗ này có vẻ bị lặp."),
 ("Can we extract this into a function?","Tách cái này thành hàm được không?"),
 ("Is this still needed?","Cái này còn cần không?"),
 ("You can simplify this part.","Chỗ này có thể làm gọn hơn."),
 ("Small thing, not a blocker.","Chuyện nhỏ, không cản trở đâu."),
 ("Just a suggestion, feel free to ignore.","Chỉ là gợi ý, bỏ qua cũng được."),
 ("Overall looks great.","Nhìn chung ổn lắm."),
 ("Nitpick: extra space here.","Bắt bẻ tí: dư một dấu cách ở đây."),
 ("Let's fix the naming later.","Đổi tên để sau cũng được."),
 ("This variable name is confusing.","Tên biến này khó hiểu."),
 ("Could you split this into smaller commits?","Bạn tách thành các commit nhỏ hơn được không?"),
 ("The logic here is unclear.","Logic ở đây chưa rõ."),
 ("Add error handling here, please.","Thêm xử lý lỗi ở đây nhé."),
 ("Missing a null check.","Thiếu kiểm tra null."),
 ("This could be a performance issue.","Chỗ này có thể ảnh hưởng hiệu năng."),
 ("Nice refactor!","Refactor hay đấy!"),
 ("Thanks for cleaning this up.","Cảm ơn đã dọn dẹp chỗ này."),
 ("I'll approve after this change.","Sửa chỗ này là mình duyệt."),
 ("Approved! Ship it.","Duyệt rồi! Đẩy đi."),
 ("Let's discuss this one offline.","Cái này mình bàn riêng nhé."),
 ("Can you explain why you did this?","Bạn giải thích vì sao làm vậy được không?"),
 ("Is there a reason for this approach?","Có lý do gì cho cách này không?"),
 ("This test doesn't cover the edge case.","Test này chưa phủ trường hợp hiếm."),
 ("Please update the documentation too.","Cập nhật tài liệu nữa nhé."),
 ("Left a few comments, take a look.","Mình để lại vài góp ý, xem nhé."),
 ("Looks solid, just one question.","Nhìn chắc chắn, chỉ một câu hỏi thôi."),
 ("Can we add logging here?","Thêm log ở đây được không?"),
 ("Great, no comments from me.","Tuyệt, mình không có góp ý gì."),
 ("Let's merge it.","Merge thôi."),
])

G("Code review — nhận góp ý", [
 ("Thanks for the review.","Cảm ơn đã review."),
 ("Good catch!","Bạn phát hiện hay đấy!"),
 ("You're right, I'll fix it.","Bạn đúng, mình sẽ sửa."),
 ("I'll update it now.","Mình sửa ngay."),
 ("Makes sense, thanks.","Hợp lý, cảm ơn nhé."),
 ("I missed that, thanks.","Mình sót chỗ đó, cảm ơn."),
 ("Good point, let me change it.","Ý hay, để mình đổi."),
 ("I'll add a test for that.","Mình sẽ thêm test cho cái đó."),
 ("Fixed, please take another look.","Sửa rồi, bạn xem lại nhé."),
 ("I addressed all the comments.","Mình đã xử lý hết góp ý."),
 ("Could you explain this comment?","Bạn giải thích góp ý này được không?"),
 ("I'm not sure I agree here.","Chỗ này mình chưa chắc đồng ý."),
 ("Can we keep it as is for now?","Tạm giữ nguyên được không?"),
 ("I did it this way because...","Mình làm vậy vì..."),
 ("Let me explain my reasoning.","Để mình giải thích lý do."),
 ("That's a fair point.","Góp ý hợp lý đấy."),
 ("I'll refactor this part.","Mình sẽ refactor phần này."),
 ("Will do, thanks for pointing it out.","Sẽ làm, cảm ơn đã chỉ ra."),
 ("Sorry, that was my mistake.","Xin lỗi, đó là lỗi của mình."),
 ("I'll be more careful next time.","Lần sau mình cẩn thận hơn."),
 ("Updated, ready for another review.","Cập nhật rồi, sẵn sàng review lại."),
 ("Can we discuss this on a call?","Mình gọi bàn cái này được không?"),
 ("I'd prefer to keep this approach.","Mình muốn giữ cách làm này."),
 ("Let's compromise here.","Mình dung hòa ở đây nhé."),
 ("I'll split it into smaller commits.","Mình sẽ tách thành commit nhỏ hơn."),
 ("Thanks, that's clearer now.","Cảm ơn, giờ rõ hơn rồi."),
 ("I'll add comments to explain.","Mình sẽ thêm chú thích để giải thích."),
 ("Good idea, I'll do that.","Ý hay, mình sẽ làm vậy."),
 ("I'll handle the edge case.","Mình sẽ xử lý trường hợp hiếm."),
 ("Let me test it again.","Để mình test lại."),
 ("All comments resolved.","Đã xử lý hết góp ý."),
 ("Thanks for the detailed feedback.","Cảm ơn góp ý chi tiết."),
 ("I really appreciate the review.","Mình cảm ơn buổi review nhiều."),
 ("I'll fix the naming.","Mình sẽ sửa cách đặt tên."),
 ("Pushed the changes.","Đã đẩy thay đổi lên."),
 ("Can you re-review when free?","Rảnh bạn review lại giúp nhé?"),
 ("I removed the duplicate code.","Mình đã bỏ code trùng."),
 ("You were right about the bug.","Bạn nói đúng về lỗi đó."),
 ("Thanks, learned something new.","Cảm ơn, mình học được điều mới."),
 ("Let me know if there's anything else.","Còn gì nữa thì báo mình nhé."),
])

G("Báo lỗi & bug", [
 ("I found a bug.","Mình tìm thấy một lỗi."),
 ("There's a bug in the login page.","Có lỗi ở trang login."),
 ("The button doesn't work.","Nút bấm không hoạt động."),
 ("The page won't load.","Trang không tải được."),
 ("It throws an error.","Nó báo lỗi."),
 ("I got an error message.","Mình nhận được thông báo lỗi."),
 ("Here's the error message.","Đây là thông báo lỗi."),
 ("Let me send you the screenshot.","Để mình gửi ảnh chụp màn hình."),
 ("Can you reproduce it?","Bạn tái hiện được không?"),
 ("I can't reproduce it.","Mình không tái hiện được."),
 ("It only happens sometimes.","Nó chỉ thỉnh thoảng xảy ra."),
 ("It happens every time.","Lần nào cũng bị."),
 ("It works on my machine.","Máy mình thì chạy được."),
 ("It fails on staging.","Nó lỗi trên staging."),
 ("The bug is in production.","Lỗi đang ở production."),
 ("This is a high priority bug.","Đây là lỗi ưu tiên cao."),
 ("This is blocking the release.","Cái này đang chặn bản phát hành."),
 ("What are the steps to reproduce?","Các bước tái hiện là gì?"),
 ("Which browser are you using?","Bạn dùng trình duyệt nào?"),
 ("What did you expect to happen?","Bạn mong nó chạy thế nào?"),
 ("What actually happened?","Thực tế thì nó thế nào?"),
 ("Let me check the logs.","Để mình xem log."),
 ("Please send me the stack trace.","Gửi mình stack trace nhé."),
 ("I think I found the root cause.","Mình nghĩ tìm ra nguyên nhân gốc rồi."),
 ("It's a null pointer error.","Đây là lỗi con trỏ null."),
 ("The data is missing.","Dữ liệu bị thiếu."),
 ("The API returns a 500.","API trả về mã 500."),
 ("The request times out.","Yêu cầu bị quá giờ chờ."),
 ("It's a timing issue.","Đây là vấn đề về thời điểm."),
 ("This is a regression.","Đây là lỗi tái phát."),
 ("It broke after the last deploy.","Nó hỏng sau lần deploy trước."),
 ("Let me open a ticket.","Để mình tạo một ticket."),
 ("I'll assign it to you.","Mình sẽ giao cho bạn."),
 ("Can you take this bug?","Bạn nhận lỗi này được không?"),
 ("I'm on it.","Mình đang xử lý."),
 ("I'll investigate now.","Mình điều tra ngay."),
 ("I fixed the bug.","Mình đã sửa lỗi."),
 ("Please verify the fix.","Bạn kiểm tra bản sửa nhé."),
 ("It's working now.","Giờ chạy được rồi."),
 ("Thanks for reporting it.","Cảm ơn đã báo lỗi."),
])

G("Deploy & release", [
 ("We're deploying now.","Bọn mình đang deploy."),
 ("The deploy is starting.","Bắt đầu deploy đây."),
 ("The deploy is done.","Deploy xong rồi."),
 ("Please test again after the deploy.","Deploy xong test lại nhé."),
 ("We deploy every Friday.","Bọn mình deploy mỗi thứ Sáu."),
 ("Let's test on staging first.","Thử trên staging trước đã."),
 ("Don't deploy on Friday afternoon.","Đừng deploy chiều thứ Sáu."),
 ("Expect a short downtime.","Sẽ có downtime ngắn."),
 ("The site will be down for five minutes.","Trang sẽ ngừng năm phút."),
 ("If anything breaks, we'll roll back.","Nếu có gì hỏng mình sẽ rollback."),
 ("Let's roll back to the previous version.","Rollback về bản trước đi."),
 ("The build failed.","Bản build bị lỗi."),
 ("The build passed.","Bản build đã qua."),
 ("Let me trigger the pipeline.","Để mình chạy pipeline."),
 ("The pipeline is running.","Pipeline đang chạy."),
 ("Please run the migration first.","Chạy migration trước nhé."),
 ("Did you run the migration?","Bạn chạy migration chưa?"),
 ("The release is scheduled for Monday.","Bản phát hành đặt vào thứ Hai."),
 ("Let's freeze the code before release.","Khóa code trước khi phát hành nhé."),
 ("We're in a code freeze now.","Giờ đang khóa code."),
 ("Who is on release duty today?","Hôm nay ai trực release?"),
 ("I'll push the hotfix.","Mình sẽ đẩy bản hotfix."),
 ("We need a hotfix for this.","Cái này cần một hotfix."),
 ("Let's deploy after the review.","Review xong mình deploy."),
 ("Is it safe to deploy now?","Deploy bây giờ an toàn không?"),
 ("Let me double-check the config.","Để mình kiểm tra lại cấu hình."),
 ("The environment is not ready.","Môi trường chưa sẵn sàng."),
 ("Everything looks good on staging.","Trên staging mọi thứ đều ổn."),
 ("Let's go live.","Đưa lên chạy thật đi."),
 ("It's live now.","Đã lên rồi."),
 ("Please monitor after the deploy.","Deploy xong theo dõi nhé."),
 ("Keep an eye on the logs.","Để mắt tới log nhé."),
 ("No errors so far.","Chưa thấy lỗi gì."),
 ("Looks stable.","Có vẻ ổn định."),
 ("Let's announce it to the team.","Thông báo cho team nhé."),
 ("The deploy is delayed.","Việc deploy bị hoãn."),
 ("We'll deploy tomorrow instead.","Mình dời sang mai deploy."),
 ("I'll send the release notes.","Mình sẽ gửi ghi chú phát hành."),
 ("Deployment successful.","Deploy thành công."),
 ("Great, thanks everyone.","Tuyệt, cảm ơn mọi người."),
])

G("Git & quản lý mã", [
 ("Did you pull the latest code?","Bạn pull code mới nhất chưa?"),
 ("Let me pull first.","Để mình pull trước đã."),
 ("I'll push my changes.","Mình đẩy code lên đây."),
 ("Don't forget to push.","Nhớ push nhé."),
 ("Create a new branch for this.","Tạo branch mới cho cái này."),
 ("Which branch are you on?","Bạn đang ở branch nào?"),
 ("I'm on the feature branch.","Mình đang ở branch feature."),
 ("Let's merge it into main.","Merge vào main nhé."),
 ("Can I merge now?","Mình merge được chưa?"),
 ("I got a merge conflict.","Mình bị merge conflict."),
 ("Let me resolve the conflict.","Để mình xử lý xung đột."),
 ("Please rebase on main.","Rebase lên main nhé."),
 ("Squash the commits, please.","Gộp các commit lại nhé."),
 ("Write a clear commit message.","Viết message commit rõ ràng nhé."),
 ("I'll open a pull request.","Mình sẽ mở một PR."),
 ("Can you review my PR?","Bạn review PR của mình không?"),
 ("Please approve the PR.","Duyệt PR giúp mình nhé."),
 ("The PR is ready.","PR sẵn sàng rồi."),
 ("I'll revert that commit.","Mình sẽ revert commit đó."),
 ("Let's revert to the last working version.","Quay về bản chạy được gần nhất đi."),
 ("Did you commit your changes?","Bạn commit thay đổi chưa?"),
 ("I forgot to commit.","Mình quên commit."),
 ("Let me stash my changes.","Để mình stash thay đổi lại."),
 ("Clone the repo first.","Clone repo về trước đã."),
 ("What's the repo URL?","Link repo là gì?"),
 ("Give me access to the repo.","Cho mình quyền vào repo nhé."),
 ("The main branch is protected.","Branch main được bảo vệ."),
 ("You can't push directly to main.","Không push thẳng vào main được."),
 ("Please delete the old branch.","Xóa branch cũ giúp nhé."),
 ("Your branch is behind main.","Branch của bạn cũ hơn main."),
 ("Update your branch first.","Cập nhật branch của bạn trước."),
 ("There's a conflict in this file.","File này có xung đột."),
 ("I'll take care of the merge.","Mình lo phần merge."),
 ("Let's tag this release.","Gắn tag cho bản này nhé."),
 ("Check the commit history.","Xem lịch sử commit đi."),
 ("Who wrote this line?","Ai viết dòng này vậy?"),
 ("Let me check the blame.","Để mình xem git blame."),
 ("Your commit broke the build.","Commit của bạn làm hỏng build."),
 ("Let me fix it and push again.","Để mình sửa rồi push lại."),
 ("The PR is merged.","PR đã được merge."),
])

G("Hỏi & báo trạng thái", [
 ("What's the status?","Tình hình thế nào rồi?"),
 ("Any updates on this?","Cái này có cập nhật gì không?"),
 ("How's it going with the task?","Task đó tới đâu rồi?"),
 ("Is it done yet?","Xong chưa?"),
 ("Are you almost done?","Sắp xong chưa?"),
 ("When will it be ready?","Khi nào xong?"),
 ("What's the ETA?","Dự kiến khi nào xong?"),
 ("Any progress?","Có tiến triển gì không?"),
 ("It's in progress.","Đang làm."),
 ("It's almost done.","Sắp xong rồi."),
 ("It's done.","Xong rồi."),
 ("I haven't started yet.","Mình chưa bắt đầu."),
 ("I'll start after this.","Xong cái này mình bắt đầu."),
 ("It's on hold.","Đang tạm dừng."),
 ("It's blocked.","Đang bị chặn."),
 ("It's ready for review.","Sẵn sàng để review."),
 ("It's in testing.","Đang test."),
 ("It's waiting for approval.","Đang chờ duyệt."),
 ("It's deployed.","Đã deploy."),
 ("I'm about 80% done.","Mình làm được khoảng 80%."),
 ("Give me until the end of the day.","Cho mình đến cuối ngày."),
 ("I'll have it ready by tomorrow.","Mai mình sẽ xong."),
 ("I need more time.","Mình cần thêm thời gian."),
 ("It's taking longer than expected.","Nó lâu hơn dự kiến."),
 ("I'm ahead of schedule.","Mình sớm hơn tiến độ."),
 ("I'm a bit behind.","Mình hơi chậm."),
 ("We're on track.","Mình đúng tiến độ."),
 ("Everything is on schedule.","Mọi thứ đúng lịch."),
 ("Let me check and let you know.","Để mình kiểm tra rồi báo."),
 ("I'll update you by noon.","Trưa mình sẽ cập nhật."),
 ("Can you give me a status update?","Bạn cập nhật tình hình giúp nhé?"),
 ("Where do we stand?","Mình đang ở đâu rồi?"),
 ("Is everything on track?","Mọi thứ đúng tiến độ chứ?"),
 ("Nothing to report yet.","Chưa có gì để báo."),
 ("I'll keep you posted.","Mình sẽ cập nhật tiếp cho bạn."),
 ("Let me follow up on that.","Để mình theo dõi tiếp cái đó."),
 ("I'm still waiting on the API.","Mình vẫn đang chờ API."),
 ("It's ready whenever you are.","Xong rồi, bạn sẵn sàng lúc nào cũng được."),
 ("Let's check in tomorrow.","Mai mình kiểm tra lại nhé."),
 ("Thanks for the update.","Cảm ơn đã cập nhật."),
])

G("Báo blocker & trễ hạn", [
 ("I have a blocker.","Mình có một chỗ đang bị vướng."),
 ("I'm blocked on this.","Mình đang bị chặn ở cái này."),
 ("I can't continue until this is fixed.","Mình không làm tiếp được cho tới khi sửa xong."),
 ("I'm waiting on another team.","Mình đang chờ team khác."),
 ("This depends on the API being ready.","Cái này phụ thuộc API đã sẵn sàng."),
 ("The staging server is down.","Server staging đang sập."),
 ("I don't have access yet.","Mình chưa có quyền truy cập."),
 ("I need someone to unblock me.","Mình cần ai đó gỡ vướng cho."),
 ("Can you help me get unblocked?","Bạn giúp mình gỡ vướng được không?"),
 ("This is slowing me down.","Cái này làm mình chậm lại."),
 ("I might miss the deadline.","Mình có thể trễ hạn."),
 ("We won't make it by Friday.","Không kịp trước thứ Sáu đâu."),
 ("I need one more day.","Mình cần thêm một ngày."),
 ("Can we push the deadline?","Dời hạn chót được không?"),
 ("Is there any flexibility on the date?","Ngày có linh động được không?"),
 ("The task is bigger than expected.","Task lớn hơn dự kiến."),
 ("There's a hidden dependency.","Có một phụ thuộc ẩn."),
 ("I underestimated this task.","Mình ước lượng thiếu task này."),
 ("Sorry, I need to delay this.","Xin lỗi, mình phải hoãn cái này."),
 ("Let me flag a risk.","Để mình nêu một rủi ro."),
 ("This could delay the release.","Cái này có thể làm trễ bản phát hành."),
 ("We should escalate this.","Mình nên báo lên cấp trên."),
 ("Who can I talk to about this?","Cái này mình nói với ai được?"),
 ("I need a decision on this.","Mình cần một quyết định cho cái này."),
 ("Please prioritize this for me.","Ưu tiên cái này giúp mình nhé."),
 ("Can someone review this urgently?","Có ai review gấp cái này không?"),
 ("I'm waiting for approval.","Mình đang chờ duyệt."),
 ("The requirement is still unclear.","Yêu cầu vẫn chưa rõ."),
 ("I can't test without the data.","Không có dữ liệu thì mình không test được."),
 ("The environment keeps crashing.","Môi trường cứ sập liên tục."),
 ("Let me know if you're blocked.","Nếu bạn bị vướng thì báo mình."),
 ("What's blocking you?","Cái gì đang chặn bạn?"),
 ("Let's remove this blocker first.","Gỡ vướng này trước đã."),
 ("I'll take this to the manager.","Mình sẽ báo với quản lý."),
 ("It's out of my control.","Cái này ngoài tầm mình."),
 ("I did what I could on my end.","Phần mình thì mình làm hết rồi."),
 ("We need more people on this.","Cái này cần thêm người."),
 ("Let's find a workaround.","Tìm cách khắc phục tạm đi."),
 ("For now, there's a workaround.","Trước mắt có cách tạm."),
 ("I'll update you once it's unblocked.","Gỡ được mình sẽ báo bạn."),
])

G("Ước lượng & kế hoạch", [
 ("How long will this take?","Cái này mất bao lâu?"),
 ("What's your estimate?","Bạn ước lượng bao lâu?"),
 ("My estimate is two days.","Mình ước lượng hai ngày."),
 ("It's hard to estimate.","Khó ước lượng lắm."),
 ("Give me a rough estimate.","Cho mình con số ước chừng thôi."),
 ("Roughly one week.","Đại khái một tuần."),
 ("It could take a day or two.","Có thể một, hai ngày."),
 ("Let me break it down first.","Để mình chia nhỏ ra đã."),
 ("Let's define the scope.","Xác định phạm vi đã."),
 ("What's in scope for this?","Cái này gồm những gì?"),
 ("That's out of scope.","Cái đó ngoài phạm vi."),
 ("Let's keep the scope small.","Giữ phạm vi nhỏ thôi."),
 ("We can do that in the next sprint.","Cái đó để sprint sau."),
 ("Let's prioritize the must-haves.","Ưu tiên cái bắt buộc trước."),
 ("This is a nice-to-have.","Cái này có thì tốt, không bắt buộc."),
 ("What's the deadline?","Hạn chót là khi nào?"),
 ("Is this feasible by Friday?","Trước thứ Sáu có khả thi không?"),
 ("It's tight but doable.","Hơi gấp nhưng làm được."),
 ("That's not realistic.","Cái đó không thực tế."),
 ("We need more time for testing.","Mình cần thêm thời gian để test."),
 ("Let's add some buffer.","Thêm một khoảng dự phòng đi."),
 ("This task has a dependency.","Task này có một phụ thuộc."),
 ("This depends on the design being ready.","Cái này phụ thuộc thiết kế đã xong."),
 ("Let's agree on a timeline.","Thống nhất mốc thời gian nhé."),
 ("What's the next milestone?","Cột mốc tiếp theo là gì?"),
 ("Let's split this into smaller tasks.","Chia cái này thành task nhỏ hơn đi."),
 ("Who will take this task?","Ai nhận task này?"),
 ("I'll take that one.","Mình nhận cái đó."),
 ("Let's assign owners.","Phân người phụ trách đi."),
 ("There's a trade-off here.","Ở đây có sự đánh đổi."),
 ("If we do this, we can't do that.","Làm cái này thì không làm cái kia được."),
 ("Let's focus on the priorities.","Tập trung vào cái ưu tiên thôi."),
 ("Can we cut some features?","Bớt vài tính năng được không?"),
 ("Let's plan for next week.","Lên kế hoạch cho tuần sau đi."),
 ("What are the risks?","Có những rủi ro gì?"),
 ("The main risk is time.","Rủi ro chính là thời gian."),
 ("Let's have a plan B.","Có phương án dự phòng đi."),
 ("We're overcommitted this sprint.","Sprint này mình nhận quá nhiều."),
 ("Let's move this to the backlog.","Đưa cái này vào backlog."),
 ("That sounds like a solid plan.","Nghe như một kế hoạch chắc chắn."),
])

G("Họp — sắp xếp & điều phối", [
 ("Can we set up a meeting?","Mình đặt một cuộc họp nhé?"),
 ("Are you free tomorrow?","Mai bạn rảnh không?"),
 ("What time works for you?","Bạn tiện mấy giờ?"),
 ("How about 2 PM?","2 giờ chiều được không?"),
 ("Does Monday work?","Thứ Hai được không?"),
 ("Let's find a time that works for everyone.","Tìm giờ hợp với mọi người đi."),
 ("I'll send a calendar invite.","Mình sẽ gửi lời mời lịch."),
 ("Please accept the invite.","Nhận lời mời giúp nhé."),
 ("Can we move the meeting?","Dời cuộc họp được không?"),
 ("Let's reschedule.","Sắp xếp lại lịch nhé."),
 ("Sorry, I have a conflict.","Xin lỗi, mình trùng lịch."),
 ("Can we make it shorter?","Rút ngắn lại được không?"),
 ("Fifteen minutes should be enough.","Mười lăm phút chắc đủ."),
 ("Do we really need a meeting?","Có thật sự cần họp không?"),
 ("Let's just discuss it on chat.","Trao đổi qua chat cho nhanh."),
 ("Who should join this meeting?","Ai nên tham gia cuộc họp này?"),
 ("Let's keep it small.","Giữ nhóm nhỏ thôi."),
 ("Can you send the agenda?","Bạn gửi nội dung họp được không?"),
 ("What's the meeting about?","Cuộc họp về gì vậy?"),
 ("Let's set an agenda first.","Đặt nội dung họp trước đã."),
 ("I might be a few minutes late.","Mình có thể trễ vài phút."),
 ("Can we start on time?","Mình bắt đầu đúng giờ nhé?"),
 ("Let's wait two minutes for others.","Đợi hai phút cho mọi người."),
 ("I'll record the meeting.","Mình sẽ ghi lại cuộc họp."),
 ("Can someone take notes?","Có ai ghi chú được không?"),
 ("I'll share the notes after.","Xong mình gửi ghi chú."),
 ("Let's book a room.","Đặt phòng đi."),
 ("Is this room free?","Phòng này trống không?"),
 ("Let's do it online.","Họp online đi."),
 ("I'll send the meeting link.","Mình gửi link họp."),
 ("Can we push it to the afternoon?","Dời sang chiều được không?"),
 ("Let's keep it to 30 minutes.","Giữ trong 30 phút thôi."),
 ("I can't make it, sorry.","Mình không tham gia được, xin lỗi."),
 ("Can you join on my behalf?","Bạn dự thay mình được không?"),
 ("Let's cancel if it's not needed.","Không cần thì hủy đi."),
 ("Recurring every Monday?","Lặp lại mỗi thứ Hai nhé?"),
 ("Let's meet weekly.","Họp hằng tuần nhé."),
 ("Send me a reminder, please.","Nhắc mình một cái nhé."),
 ("Talk to you then.","Hẹn gặp lúc đó."),
 ("Looking forward to it.","Mong tới lúc đó."),
])

G("Họp — trong cuộc họp", [
 ("Let's get started.","Bắt đầu thôi."),
 ("Let's go over the agenda.","Điểm qua nội dung họp nào."),
 ("First on the list is...","Đầu tiên trong danh sách là..."),
 ("Let's move on to the next item.","Chuyển sang mục tiếp theo."),
 ("Can I add something?","Mình bổ sung một chút được không?"),
 ("Can I jump in here?","Mình chen vào một chút nhé?"),
 ("Sorry to interrupt.","Xin lỗi cắt ngang."),
 ("Let me finish my point.","Để mình nói hết ý đã."),
 ("Go ahead.","Bạn nói đi."),
 ("What do you think?","Bạn nghĩ sao?"),
 ("Any thoughts on this?","Ai có ý kiến gì không?"),
 ("Let's hear from everyone.","Nghe ý kiến mọi người nào."),
 ("Can we park this for now?","Tạm gác cái này lại nhé?"),
 ("Let's take that offline.","Cái đó mình bàn riêng sau."),
 ("Let's stay on topic.","Mình bám chủ đề nhé."),
 ("We're running out of time.","Mình sắp hết giờ."),
 ("Let's wrap up.","Kết thúc thôi."),
 ("To summarize...","Tóm lại..."),
 ("Let me recap the decisions.","Để mình tóm tắt các quyết định."),
 ("So the action items are...","Vậy các việc cần làm là..."),
 ("Who will take this action?","Ai nhận việc này?"),
 ("I'll follow up on that.","Mình sẽ theo dõi cái đó."),
 ("Let's set a deadline for this.","Đặt hạn cho cái này đi."),
 ("Does everyone agree?","Mọi người đồng ý chứ?"),
 ("Any objections?","Ai phản đối không?"),
 ("Let's make a decision.","Ra quyết định đi."),
 ("Can we vote on this?","Mình biểu quyết được không?"),
 ("Let's table this discussion.","Gác cuộc thảo luận này lại."),
 ("I'll share my screen.","Mình chia sẻ màn hình."),
 ("Can you see this?","Bạn thấy cái này không?"),
 ("Let's look at the numbers.","Xem các con số nào."),
 ("Any questions so far?","Đến đây có câu hỏi gì không?"),
 ("That's a good question.","Câu hỏi hay đấy."),
 ("Let me get back to you on that.","Cái đó để mình trả lời sau."),
 ("We're aligned then.","Vậy là mình thống nhất."),
 ("Thanks everyone for joining.","Cảm ơn mọi người đã tham gia."),
 ("I'll send the notes after.","Xong mình gửi ghi chú."),
 ("Let's end here.","Kết thúc ở đây nhé."),
 ("Have a good day, everyone.","Chúc mọi người một ngày tốt."),
 ("Let's meet again next week.","Tuần sau mình họp tiếp."),
])

G("Đề xuất ý tưởng", [
 ("I have an idea.","Mình có một ý tưởng."),
 ("What if we try this?","Hay là mình thử cái này?"),
 ("How about we do it this way?","Hay mình làm theo cách này?"),
 ("Maybe we could...","Có lẽ mình có thể..."),
 ("Here's a suggestion.","Đây là một gợi ý."),
 ("Just an idea, but...","Chỉ là ý tưởng thôi, nhưng..."),
 ("Why don't we...?","Sao mình không...?"),
 ("Let's consider another option.","Xem xét phương án khác đi."),
 ("I think there's a simpler way.","Mình nghĩ có cách đơn giản hơn."),
 ("We could automate this.","Mình có thể tự động hóa cái này."),
 ("What if we cache the result?","Hay là mình cache kết quả lại?"),
 ("Let's reuse the existing code.","Dùng lại code có sẵn đi."),
 ("Maybe we don't need this at all.","Có khi mình không cần cái này luôn."),
 ("Let's start small.","Bắt đầu nhỏ thôi."),
 ("We can improve it later.","Cải thiện sau cũng được."),
 ("Let's do a quick prototype.","Làm bản thử nhanh đi."),
 ("It's worth a try.","Đáng để thử."),
 ("Let me think out loud.","Để mình nghĩ thành tiếng."),
 ("Correct me if this is wrong.","Sai thì bạn sửa mình nhé."),
 ("This might not work, but...","Cái này có thể không được, nhưng..."),
 ("Let's brainstorm a bit.","Mình động não một chút đi."),
 ("Any better ideas?","Có ý nào hay hơn không?"),
 ("Let's build on that.","Phát triển thêm từ ý đó đi."),
 ("I like where this is going.","Mình thích hướng này."),
 ("Let's keep it simple.","Giữ đơn giản thôi."),
 ("We could split it into two steps.","Mình có thể chia thành hai bước."),
 ("What about performance?","Còn hiệu năng thì sao?"),
 ("Have we considered the cost?","Mình đã tính đến chi phí chưa?"),
 ("Let's test the idea first.","Thử ý tưởng trước đã."),
 ("I'll write up a proposal.","Mình sẽ viết một đề xuất."),
 ("Let me sketch it out.","Để mình phác ra."),
 ("Let's get feedback early.","Xin phản hồi sớm đi."),
 ("This could save us time.","Cái này có thể giúp tiết kiệm thời gian."),
 ("It's a trade-off, but worth it.","Có đánh đổi, nhưng đáng."),
 ("Let's not over-engineer this.","Đừng làm phức tạp quá."),
 ("Simple is better here.","Ở đây đơn giản là tốt hơn."),
 ("Let's pick the easy win first.","Chọn cái dễ ăn trước đi."),
 ("What's the simplest thing that works?","Cách đơn giản nhất mà chạy được là gì?"),
 ("Let's validate this with users.","Kiểm chứng với người dùng đi."),
 ("I'll share my idea in the doc.","Mình sẽ ghi ý tưởng vào tài liệu."),
])

G("Giải thích vấn đề kỹ thuật", [
 ("Let me explain the problem.","Để mình giải thích vấn đề."),
 ("Here's what's happening.","Chuyện là thế này."),
 ("The issue is in the database.","Vấn đề nằm ở database."),
 ("It's a performance problem.","Đây là vấn đề hiệu năng."),
 ("The query is too slow.","Câu query quá chậm."),
 ("It needs an index.","Nó cần một index."),
 ("The data is too big.","Dữ liệu quá lớn."),
 ("The server ran out of memory.","Server hết bộ nhớ."),
 ("It's a race condition.","Đây là lỗi tranh chấp thời điểm."),
 ("Two requests conflict with each other.","Hai request xung đột với nhau."),
 ("The cache is out of date.","Cache đã cũ."),
 ("The config is wrong.","Cấu hình bị sai."),
 ("It's an authentication issue.","Đây là vấn đề xác thực."),
 ("The token expired.","Token đã hết hạn."),
 ("The API changed.","API đã thay đổi."),
 ("There's a breaking change.","Có một thay đổi gây lỗi."),
 ("The versions don't match.","Các phiên bản không khớp."),
 ("It fails silently.","Nó lỗi mà không báo."),
 ("The error is hard to catch.","Lỗi này khó bắt."),
 ("Let me draw a diagram.","Để mình vẽ sơ đồ."),
 ("Think of it like this.","Hình dung thế này."),
 ("In simple terms...","Nói đơn giản là..."),
 ("The root cause is...","Nguyên nhân gốc là..."),
 ("The symptom is a timeout.","Triệu chứng là bị timeout."),
 ("It only affects some users.","Chỉ ảnh hưởng một số người dùng."),
 ("The impact is low.","Mức ảnh hưởng thấp."),
 ("This is critical.","Cái này rất nghiêm trọng."),
 ("Let me trace the flow.","Để mình lần theo luồng xử lý."),
 ("The data flows like this.","Dữ liệu chạy như thế này."),
 ("It breaks at this step.","Nó hỏng ở bước này."),
 ("Here's the tricky part.","Đây là chỗ rắc rối."),
 ("The logic is a bit complex.","Logic hơi phức tạp."),
 ("Let me give you an example.","Để mình cho một ví dụ."),
 ("For instance...","Ví dụ..."),
 ("Basically, it does two things.","Về cơ bản, nó làm hai việc."),
 ("The tricky bit is the timing.","Chỗ khó là thời điểm."),
 ("Once you see it, it's obvious.","Nhìn ra rồi thì thấy rõ ngay."),
 ("Does that make sense so far?","Đến đây có hợp lý không?"),
 ("Let me know if that's unclear.","Chỗ nào chưa rõ thì báo mình."),
 ("I'll write it up in the ticket.","Mình sẽ ghi rõ trong ticket."),
])

G("Xin lỗi & nhận trách nhiệm", [
 ("Sorry about that.","Xin lỗi về việc đó."),
 ("That was my mistake.","Đó là lỗi của mình."),
 ("My bad.","Lỗi của mình."),
 ("I take responsibility for this.","Mình nhận trách nhiệm về việc này."),
 ("I should have tested it.","Lẽ ra mình nên test."),
 ("I missed that, sorry.","Mình sót chỗ đó, xin lỗi."),
 ("I'll fix it right away.","Mình sẽ sửa ngay."),
 ("It won't happen again.","Sẽ không tái diễn."),
 ("Thanks for your patience.","Cảm ơn bạn đã kiên nhẫn."),
 ("Sorry for the delay.","Xin lỗi vì đã trễ."),
 ("Sorry for the confusion.","Xin lỗi vì gây nhầm lẫn."),
 ("I misunderstood the requirement.","Mình hiểu nhầm yêu cầu."),
 ("Let me make it right.","Để mình sửa lại cho đúng."),
 ("I'll be more careful next time.","Lần sau mình cẩn thận hơn."),
 ("I dropped the ball on this.","Mình để lỡ việc này."),
 ("I owe you an apology.","Mình nợ bạn một lời xin lỗi."),
 ("Sorry to let you down.","Xin lỗi đã làm bạn thất vọng."),
 ("I'll double-check from now on.","Từ giờ mình sẽ kiểm tra kỹ."),
 ("I understand the impact.","Mình hiểu mức ảnh hưởng."),
 ("Let me clean up the mess.","Để mình dọn lại chỗ này."),
 ("Sorry for the late reply.","Xin lỗi trả lời muộn."),
 ("Apologies for missing the meeting.","Xin lỗi đã lỡ cuộc họp."),
 ("I forgot, sorry.","Mình quên mất, xin lỗi."),
 ("That's on me.","Đó là do mình."),
 ("I'll own this and fix it.","Mình nhận và sẽ sửa."),
 ("Thanks for understanding.","Cảm ơn đã thông cảm."),
 ("I appreciate your patience.","Cảm ơn bạn đã kiên nhẫn."),
 ("Let me know how I can make up for it.","Cho mình biết cách bù đắp nhé."),
 ("I learned my lesson.","Mình rút kinh nghiệm rồi."),
 ("Sorry, I was not clear.","Xin lỗi, mình nói chưa rõ."),
 ("Let me clarify what I meant.","Để mình nói rõ lại ý."),
 ("I take your point.","Mình tiếp thu ý bạn."),
 ("You're right, I was wrong.","Bạn đúng, mình sai."),
 ("I'll correct it now.","Mình sửa lại ngay."),
 ("Sorry for the inconvenience.","Xin lỗi vì sự bất tiện."),
 ("I'll make sure it's fixed.","Mình sẽ đảm bảo sửa xong."),
 ("Thanks for pointing it out.","Cảm ơn đã chỉ ra."),
 ("I'll update everyone.","Mình sẽ báo lại mọi người."),
 ("Let me take another look.","Để mình xem lại."),
 ("I'll do better next time.","Lần sau mình sẽ làm tốt hơn."),
])

G("Cảm ơn & ghi nhận", [
 ("Thank you so much.","Cảm ơn bạn nhiều."),
 ("Thanks a lot.","Cảm ơn nhiều nhé."),
 ("I really appreciate it.","Mình cảm kích lắm."),
 ("Thanks for your help.","Cảm ơn đã giúp."),
 ("That was really helpful.","Cái đó giúp mình nhiều lắm."),
 ("Thanks for the quick reply.","Cảm ơn đã trả lời nhanh."),
 ("Thanks for the heads-up.","Cảm ơn đã báo trước."),
 ("Thanks for letting me know.","Cảm ơn đã cho mình biết."),
 ("Great job, everyone.","Cả nhà làm tốt lắm."),
 ("Nice work on this.","Làm tốt vụ này lắm."),
 ("You did a great job.","Bạn làm rất tốt."),
 ("Couldn't have done it without you.","Không có bạn mình không làm được."),
 ("Thanks for stepping in.","Cảm ơn đã hỗ trợ."),
 ("Thanks for covering for me.","Cảm ơn đã làm thay mình."),
 ("I owe you one.","Mình nợ bạn một lần."),
 ("You saved me a lot of time.","Bạn giúp mình tiết kiệm nhiều thời gian."),
 ("Thanks for the feedback.","Cảm ơn góp ý."),
 ("Thanks for being patient.","Cảm ơn đã kiên nhẫn."),
 ("Much appreciated.","Cảm ơn nhiều."),
 ("Thanks for the reminder.","Cảm ơn đã nhắc."),
 ("Thanks for the review.","Cảm ơn đã review."),
 ("I appreciate your support.","Cảm ơn sự hỗ trợ của bạn."),
 ("Thanks for jumping on this.","Cảm ơn đã bắt tay vào ngay."),
 ("Thanks for the fast fix.","Cảm ơn đã sửa nhanh."),
 ("You're a lifesaver.","Bạn cứu mình một bàn thua."),
 ("Thanks, that clears it up.","Cảm ơn, giờ rõ rồi."),
 ("Thanks for explaining.","Cảm ơn đã giải thích."),
 ("Well done!","Làm tốt lắm!"),
 ("Kudos to the team.","Khen cả team."),
 ("Thanks for your hard work.","Cảm ơn đã nỗ lực."),
 ("I learned a lot from you.","Mình học được nhiều từ bạn."),
 ("Thanks for sharing.","Cảm ơn đã chia sẻ."),
 ("Thanks for the info.","Cảm ơn thông tin."),
 ("Glad to help.","Vui vì giúp được."),
 ("Anytime.","Không có gì đâu."),
 ("No problem at all.","Không sao đâu."),
 ("Happy to help anytime.","Sẵn lòng giúp bất cứ lúc nào."),
 ("You're welcome.","Không có gì."),
 ("Thanks again.","Cảm ơn lần nữa nhé."),
 ("Really grateful for your help.","Rất biết ơn sự giúp đỡ của bạn."),
])

G("Email & chat — mở & kết", [
 ("Hi team,","Chào cả team,"),
 ("Hope you're doing well.","Hy vọng bạn vẫn khỏe."),
 ("I'm writing to ask about...","Mình viết để hỏi về..."),
 ("Just a quick note.","Chỉ là một tin nhắn nhanh."),
 ("Following up on my last message.","Theo dõi tiếp tin nhắn trước của mình."),
 ("As discussed,","Như đã trao đổi,"),
 ("Per our conversation,","Theo cuộc trao đổi của mình,"),
 ("Just checking in.","Ghé hỏi thăm chút."),
 ("Any update on this?","Có cập nhật gì không?"),
 ("Could you help with the following?","Bạn giúp mình mấy việc sau nhé?"),
 ("Please find the details below.","Chi tiết ở bên dưới nhé."),
 ("Let me know your thoughts.","Cho mình biết ý bạn nhé."),
 ("Please let me know if you have questions.","Có câu hỏi gì thì báo mình."),
 ("Looking forward to your reply.","Mong hồi âm của bạn."),
 ("Thanks in advance.","Cảm ơn trước nhé."),
 ("Best regards,","Trân trọng,"),
 ("Thanks,","Cảm ơn,"),
 ("Cheers,","Thân,"),
 ("Talk soon.","Nói chuyện sau nhé."),
 ("Have a great day.","Chúc một ngày tốt lành."),
 ("Sorry for the late reply.","Xin lỗi trả lời muộn."),
 ("Quick question:","Hỏi nhanh:"),
 ("FYI,","Để bạn biết,"),
 ("Heads-up:","Báo trước:"),
 ("Just to confirm,","Xác nhận lại,"),
 ("Can you confirm by end of day?","Bạn xác nhận trước cuối ngày nhé?"),
 ("No rush.","Không gấp đâu."),
 ("Whenever you get a chance.","Khi nào tiện thôi."),
 ("Let's take this to a call.","Cái này mình gọi trao đổi nhé."),
 ("Adding Minh to the thread.","Thêm Minh vào cuộc trao đổi."),
 ("Looping in the team.","Kéo cả team vào."),
 ("Moving this to email.","Chuyển sang email nhé."),
 ("Circling back on this.","Quay lại vụ này chút."),
 ("Bumping this up.","Đẩy tin này lên trên."),
 ("Gentle reminder.","Nhắc nhẹ một cái."),
 ("Sorry to chase.","Xin lỗi phải nhắc."),
 ("Appreciate your quick response.","Cảm ơn phản hồi nhanh."),
 ("I'll follow up tomorrow.","Mai mình theo dõi tiếp."),
 ("Let me know if this works.","Nếu ổn thì báo mình."),
 ("Thanks and talk soon.","Cảm ơn, nói chuyện sau nhé."),
])

G("Bàn giao & tài liệu", [
 ("Let me hand this over.","Để mình bàn giao cái này."),
 ("I'll write up the documentation.","Mình sẽ viết tài liệu."),
 ("Here's how it works.","Đây là cách nó hoạt động."),
 ("Let me walk you through it.","Để mình hướng dẫn bạn."),
 ("The setup steps are in the README.","Các bước cài đặt ở trong README."),
 ("Check the wiki for details.","Xem wiki để biết chi tiết."),
 ("I documented the API here.","Mình đã ghi tài liệu API ở đây."),
 ("Everything you need is in this doc.","Mọi thứ bạn cần ở trong tài liệu này."),
 ("Ping me if anything is unclear.","Chỗ nào chưa rõ thì nhắn mình."),
 ("I'll be around if you have questions.","Có câu hỏi thì mình vẫn ở đây."),
 ("Let me know before you change this.","Trước khi đổi cái này báo mình nhé."),
 ("This part is a bit tricky.","Phần này hơi rắc rối."),
 ("Be careful with this config.","Cẩn thận với cấu hình này."),
 ("Don't touch this file.","Đừng động vào file này."),
 ("The credentials are in the vault.","Thông tin đăng nhập ở trong vault."),
 ("You'll need access first.","Bạn cần có quyền trước đã."),
 ("I'll request access for you.","Mình sẽ xin quyền cho bạn."),
 ("Here's the list of tasks left.","Đây là danh sách việc còn lại."),
 ("These are the known issues.","Đây là các lỗi đã biết."),
 ("The next step is testing.","Bước tiếp theo là test."),
 ("I'll transfer ownership to you.","Mình sẽ chuyển quyền phụ trách cho bạn."),
 ("You're the owner now.","Giờ bạn là người phụ trách."),
 ("Feel free to reach out anytime.","Cứ liên hệ mình bất cứ lúc nào."),
 ("I'll be on leave next week.","Tuần sau mình nghỉ phép."),
 ("Please cover this while I'm away.","Mình đi vắng bạn trông giúp nhé."),
 ("Everything is up to date.","Mọi thứ đã cập nhật."),
 ("Let me update the doc first.","Để mình cập nhật tài liệu trước."),
 ("The diagram explains the flow.","Sơ đồ giải thích luồng xử lý."),
 ("I added comments in the code.","Mình đã thêm chú thích trong code."),
 ("Read the comments for context.","Đọc chú thích để hiểu ngữ cảnh."),
 ("Let's do a handover call.","Mình gọi bàn giao nhé."),
 ("I'll record a short demo.","Mình sẽ quay một demo ngắn."),
 ("Here's a quick summary.","Đây là tóm tắt nhanh."),
 ("The main files are these.","Các file chính là những cái này."),
 ("Start from this file.","Bắt đầu từ file này."),
 ("The tests are in this folder.","Test nằm trong thư mục này."),
 ("Let me know once you're set up.","Cài xong thì báo mình nhé."),
 ("Take your time to read it.","Cứ từ từ đọc nhé."),
 ("I'll answer any questions later.","Có câu hỏi mình trả lời sau."),
 ("Good luck, you've got this.","Chúc may mắn, bạn làm được."),
])

G("Xã giao & kết thúc ngày", [
 ("How's your day going?","Hôm nay của bạn sao rồi?"),
 ("Busy day?","Ngày bận rộn hả?"),
 ("Did you have lunch?","Bạn ăn trưa chưa?"),
 ("Let's grab lunch.","Đi ăn trưa đi."),
 ("Coffee?","Cà phê không?"),
 ("How was the weekend?","Cuối tuần thế nào?"),
 ("Any plans for the weekend?","Cuối tuần có kế hoạch gì không?"),
 ("Take it easy.","Thư giãn nhé."),
 ("Don't work too hard.","Đừng làm quá sức."),
 ("Get some rest.","Nghỉ ngơi chút đi."),
 ("Almost the weekend!","Sắp cuối tuần rồi!"),
 ("Happy Friday!","Chúc thứ Sáu vui!"),
 ("Let's wrap up for today.","Hôm nay dừng ở đây nhé."),
 ("Calling it a day.","Nghỉ đây, hết ngày rồi."),
 ("I'm heading out.","Mình về đây."),
 ("See you tomorrow.","Hẹn gặp lại mai."),
 ("See you next week.","Hẹn gặp tuần sau."),
 ("Have a good evening.","Chúc buổi tối vui."),
 ("Have a nice weekend.","Chúc cuối tuần vui."),
 ("Get home safe.","Về nhà an toàn nhé."),
 ("Talk to you tomorrow.","Mai nói chuyện tiếp."),
 ("Let's continue tomorrow.","Mai mình làm tiếp."),
 ("Good work today.","Hôm nay làm tốt lắm."),
 ("Thanks for today.","Cảm ơn hôm nay nhé."),
 ("Enjoy your evening.","Tận hưởng buổi tối nhé."),
 ("Catch you later.","Gặp lại sau nhé."),
 ("Take care.","Giữ sức khỏe."),
 ("I'm off now.","Mình đi đây."),
 ("Logging off for the day.","Tắt máy, nghỉ đây."),
 ("Great teamwork today.","Hôm nay team phối hợp tốt lắm."),
 ("Let's celebrate this later.","Mình ăn mừng sau nhé."),
 ("You earned a break.","Bạn xứng đáng được nghỉ."),
 ("See you at standup.","Gặp ở standup nhé."),
 ("Ping me if anything comes up.","Có gì thì nhắn mình."),
 ("I'll be offline after six.","Sau 6 giờ mình offline."),
 ("Message me if it's urgent.","Gấp thì nhắn mình."),
 ("Enjoy the rest of your day.","Chúc phần còn lại của ngày vui vẻ."),
 ("Until tomorrow.","Hẹn mai nhé."),
 ("Bye for now.","Tạm biệt nhé."),
 ("Have a great one!","Chúc bạn một ngày tuyệt!"),
])

G("Công cụ & thiết lập máy", [
 ("My laptop is slow today.","Hôm nay laptop mình chậm."),
 ("Let me restart my computer.","Để mình khởi động lại máy."),
 ("I'll clear the cache.","Mình sẽ xóa cache."),
 ("Have you tried turning it off and on?","Bạn thử tắt bật lại chưa?"),
 ("My internet is unstable.","Mạng mình chập chờn."),
 ("The VPN is down.","VPN đang hỏng."),
 ("I can't connect to the server.","Mình không kết nối được server."),
 ("Let me check my connection.","Để mình kiểm tra kết nối."),
 ("The tool keeps crashing.","Công cụ cứ sập liên tục."),
 ("I need to update the software.","Mình cần cập nhật phần mềm."),
 ("What version are you using?","Bạn dùng phiên bản nào?"),
 ("Let me install the dependencies.","Để mình cài các thư viện."),
 ("The build takes forever.","Bản build lâu kinh khủng."),
 ("My environment is broken.","Môi trường của mình bị hỏng."),
 ("Let me reset my setup.","Để mình cài lại từ đầu."),
 ("Do you have the right permissions?","Bạn có đủ quyền chưa?"),
 ("I need admin access.","Mình cần quyền admin."),
 ("Please reset my password.","Đặt lại mật khẩu cho mình nhé."),
 ("I'm locked out of my account.","Mình bị khóa tài khoản."),
 ("Let me log in again.","Để mình đăng nhập lại."),
 ("The screen is frozen.","Màn hình bị đứng."),
 ("Let me share my screen instead.","Để mình chia sẻ màn hình cho tiện."),
 ("Can you see it now?","Giờ bạn thấy chưa?"),
 ("My mic isn't working.","Mic mình không chạy."),
 ("Let me switch to headphones.","Để mình đổi sang tai nghe."),
 ("The app needs a restart.","App cần khởi động lại."),
 ("I'll open a ticket with IT.","Mình sẽ tạo ticket cho IT."),
 ("IT is looking into it.","Bên IT đang xem xét."),
 ("It's a network issue.","Đây là vấn đề mạng."),
 ("Try a different browser.","Thử trình duyệt khác xem."),
 ("Clear your cookies.","Xóa cookie đi."),
 ("It works in incognito mode.","Ở chế độ ẩn danh thì chạy được."),
 ("Let me update my tools.","Để mình cập nhật công cụ."),
 ("My disk is full.","Ổ đĩa mình đầy rồi."),
 ("Let me free up some space.","Để mình dọn bớt chỗ trống."),
 ("The database connection failed.","Kết nối database bị lỗi."),
 ("Check your credentials.","Kiểm tra thông tin đăng nhập đi."),
 ("It's working again now.","Giờ chạy lại được rồi."),
 ("Sorry for the tech issues.","Xin lỗi vì trục trặc kỹ thuật."),
 ("All good on my end now.","Phía mình ổn cả rồi."),
])

G("Học hỏi & phản hồi cá nhân", [
 ("I'm still learning this.","Mình vẫn đang học cái này."),
 ("I'm new to this.","Mình mới với cái này."),
 ("Could you show me how?","Bạn chỉ mình cách với?"),
 ("I want to improve on this.","Mình muốn khá hơn ở cái này."),
 ("Do you have any tips?","Bạn có mẹo gì không?"),
 ("What should I learn next?","Tiếp theo mình nên học gì?"),
 ("Can you recommend a resource?","Bạn giới thiệu tài liệu nào không?"),
 ("I'll read up on it.","Mình sẽ tìm hiểu thêm."),
 ("Let me practice more.","Để mình luyện thêm."),
 ("I made the same mistake before.","Mình từng mắc lỗi này rồi."),
 ("I'll try not to repeat it.","Mình sẽ cố không lặp lại."),
 ("Thanks for teaching me.","Cảm ơn đã chỉ mình."),
 ("I learned something new today.","Hôm nay mình học được điều mới."),
 ("That's a good habit.","Đó là thói quen tốt."),
 ("Can I get some feedback?","Cho mình xin ít góp ý được không?"),
 ("How am I doing?","Mình làm thế nào?"),
 ("What can I improve?","Mình có thể cải thiện gì?"),
 ("I appreciate honest feedback.","Mình cảm kích góp ý thẳng thắn."),
 ("I'll work on that.","Mình sẽ cải thiện chỗ đó."),
 ("Point taken.","Mình tiếp thu."),
 ("That's fair.","Cũng đúng."),
 ("I see where I went wrong.","Mình thấy mình sai ở đâu rồi."),
 ("I'll be more careful.","Mình sẽ cẩn thận hơn."),
 ("Could you review my progress?","Bạn xem tiến bộ của mình nhé?"),
 ("I want to grow in this role.","Mình muốn phát triển ở vị trí này."),
 ("Let's set some goals.","Đặt vài mục tiêu đi."),
 ("I'll take on more responsibility.","Mình sẽ nhận thêm trách nhiệm."),
 ("I'm out of my comfort zone.","Mình đang ra khỏi vùng an toàn."),
 ("It's challenging but fun.","Khó nhưng vui."),
 ("I'll ask if I get stuck.","Bí thì mình sẽ hỏi."),
 ("Practice makes perfect.","Có công mài sắt có ngày nên kim."),
 ("One step at a time.","Từ từ từng bước."),
 ("I'm getting better at this.","Mình đang khá dần lên."),
 ("Thanks for your patience with me.","Cảm ơn đã kiên nhẫn với mình."),
 ("I really value your mentorship.","Mình quý sự dìu dắt của bạn."),
 ("Let's do a retro on this.","Mình cùng nhìn lại việc này nhé."),
 ("What went well?","Cái gì làm tốt?"),
 ("What could we do better?","Mình có thể làm tốt hơn ở đâu?"),
 ("Let's keep improving.","Cứ tiếp tục cải thiện nào."),
 ("Feedback is a gift.","Góp ý là món quà."),
])


G(u"Đọc ký hiệu & code", [
 (u"Underscore: user_name is 'user underscore name'.", u"Gạch dưới: user_name đọc 'user underscore name'."),
 (u"Dash: my-app is 'my dash app'.", u"Gạch nối: my-app đọc 'my dash app'."),
 (u"Dot: index.js is 'index dot js'.", u"Dấu chấm: index.js đọc 'index dot js'."),
 (u"Slash: src/app is 'src slash app'.", u"Gạch chéo: src/app đọc 'src slash app'."),
 (u"Backslash is read 'backslash' in Windows paths.", u"Gạch chéo ngược đọc 'backslash'."),
 (u"Colon: key: value is 'key colon value'.", u"Hai chấm: key: value."),
 (u"Semicolon ends a statement, read 'semicolon'.", u"Chấm phẩy kết thúc câu lệnh."),
 (u"Double colon: std::cout is 'std colon colon cout'.", u"Hai dấu hai chấm ::."),
 (u"Parentheses: run() is 'run open paren close paren'.", u"Ngoặc tròn ()."),
 (u"Square brackets: arr[0] is 'arr bracket zero'.", u"Ngoặc vuông []."),
 (u"Curly braces: {} are 'open brace, close brace'.", u"Ngoặc nhọn {}."),
 (u"Angle brackets: <div> is 'less-than div greater-than'.", u"Ngoặc nhọn <>."),
 (u"Arrow: a -> b is 'a arrow b'.", u"Mũi tên -> đọc 'arrow'."),
 (u"Fat arrow: () => {} is 'fat arrow'.", u"Mũi tên => đọc 'fat arrow'."),
 (u"At sign: @user is 'at user'.", u"Dấu @ đọc 'at'."),
 (u"Hash: #tag is 'hash tag' or 'pound'.", u"Dấu # đọc 'hash'."),
 (u"Dollar sign: $var is 'dollar var'.", u"Dấu $ đọc 'dollar'."),
 (u"Double ampersand: a && b is 'a and and b'.", u"&& đọc 'and and'."),
 (u"Double pipe: a || b is 'a or or b'.", u"|| đọc 'or or'."),
 (u"Asterisk: * is 'star' or 'asterisk'.", u"Dấu * đọc 'star'."),
 (u"Tilde: ~ is read 'tilde'.", u"Dấu ~ đọc 'tilde'."),
 (u"Caret: ^ is read 'caret'.", u"Dấu ^ đọc 'caret'."),
 (u"Percent: % is 'percent' or 'modulo'.", u"Dấu % đọc 'percent'."),
 (u"Optional chaining: a?.b is 'a optional chaining b'.", u"a?.b đọc 'optional chaining'."),
 (u"Triple equals: === is 'triple equals'.", u"=== đọc 'triple equals'."),
 (u"Not equal: != is read 'not equal'.", u"!= đọc 'not equal'."),
 (u"The path is src/utils/date.js.", u"Đường dẫn: src/utils/date.js."),
 (u"Go up one level: ../shared/config.", u"Lên một cấp: ../shared/config."),
 (u"We are on version 2.1.0, say 'two point one point zero'.", u"Bản 2.1.0."),
 (u"Upgrade to v3, say 'version three'.", u"Nâng lên v3."),
 (u"Node 18.16.0 is 'node eighteen point sixteen point zero'.", u"Node 18.16.0."),
 (u"Read the commit hash a1b2c3 character by character.", u"Đọc mã commit theo từng ký tự."),
])

# ---- build ----
import json
data=[{"name":n,"items":[{"en":e,"vi":v} for e,v in ps]} for n,ps in GROUPS]
total=sum(len(g["items"]) for g in data)
open("phrases.gen.js","w",encoding="utf-8").write("window.PHRASES="+json.dumps(data,ensure_ascii=False,separators=(",",":"))+";\n")
print("groups",len(data),"total",total)
