import {launch,page,BASE,baseStore,shot,report} from './lib.mjs';
const d=new Date(),dow=(d.getDay()+6)%7,mon=new Date(d);mon.setDate(d.getDate()-dow);const wk=mon.toISOString().slice(0,10);
const b=await launch();const p=await page(b,{store:baseStore({stats:{placed:true,sundayShown:wk}}),aiJson:`return new Promise(r=>setTimeout(()=>r({score:7,polished:'Yesterday I fixed a bug.',fixes:[],tip:''}),800));`});
await p.goto(BASE+'index.html');await p.waitForTimeout(500);
console.log('FAB gone:',await p.evaluate(()=>!document.querySelector('.fab')));
await p.context().setOffline(true);await p.evaluate(()=>window.dispatchEvent(new Event('offline')));await p.waitForTimeout(100);
console.log('offline bar:',await p.evaluate(()=>document.getElementById('offbar')?.textContent.slice(0,30)));await shot(p,'e_off');
await p.context().setOffline(false);await p.evaluate(()=>window.dispatchEvent(new Event('online')));await p.waitForTimeout(100);
console.log('offline bar gone:',await p.evaluate(()=>!document.getElementById('offbar')));
await p.evaluate(()=>standupStart());await p.waitForTimeout(200);await p.fill('#suText','yesterday I fix the bug today tests');
p.evaluate(()=>suGrade());await p.waitForTimeout(300);
console.log('AI wait skeleton:',await p.evaluate(()=>!!document.querySelector('.aiwait')));await shot(p,'e_wait');
await p.waitForTimeout(900);console.log('result shown:',await p.evaluate(()=>!document.querySelector('.aiwait')&&!!su.res));
await p.evaluate(()=>{vMode='list';vTopic='all';go('vocab');});await p.waitForTimeout(300);
const n1=await p.evaluate(()=>document.querySelectorAll('#vlList .phrase').length);
await p.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await p.waitForTimeout(400);
console.log('vocab list lazy:',n1,'->',await p.evaluate(()=>document.querySelectorAll('#vlList .phrase').length));
await p.evaluate(()=>{openPhase=7;go('roadmap');});await p.waitForTimeout(300);await shot(p,'e_road');
console.log('roadmap tiles',await p.evaluate(()=>document.querySelectorAll('.phtile').length),'open grid',!!(await p.evaluate(()=>document.getElementById('phOpen'))));
report(p,'E');await b.close();
