/* Nói Nghề — Song ngữ Anh–Nhật cho IT/BrSE (v4.3).
 * window.JA_BRSE: nhóm → items {en, vi, ja, ruby (furigana chỉ trên kanji), kana, romaji (Hepburn, ā/ī/ū/ē/ō), when, level (尊敬語/謙譲語/丁寧語 — mức keigo chủ đạo)}.
 * window.JA_BRSE_TIPS: mẹo làm việc với khách Nhật (tiếng Anh/tiếng Nhật). File dữ liệu thuần, không build. */
window.JA_BRSE = [
  { id: "hou", title: "報告 · Báo cáo tiến độ", items: [
    { en: "Let me start with the conclusion: we are on schedule.", vi: "Nói kết luận trước: dự án không bị chậm so với kế hoạch.", ja: "結論から申し上げますと、予定に遅れはございません。", ruby: "<ruby>結論<rt>けつろん</rt></ruby>から<ruby>申<rt>もう</rt></ruby>し<ruby>上<rt>あ</rt></ruby>げますと、<ruby>予定<rt>よてい</rt></ruby>に<ruby>遅<rt>おく</rt></ruby>れはございません。", kana: "けつろんからもうしあげますと、よていにおくれはございません。", romaji: "ketsuron kara mōshiagemasu to, yotei ni okure wa gozaimasen.", when: "Mở đầu báo cáo tiến độ với khách hoặc PM phía Nhật. Luôn nói kết luận trước, lý do sau; nội bộ có thể nói gọn 結論から言うと、予定どおりです", level: "謙譲語" },
    { en: "The login screen implementation is almost complete.", vi: "Phần làm màn hình đăng nhập gần như đã xong.", ja: "ログイン画面の実装は、ほぼ完了しております。", ruby: "ログイン<ruby>画面<rt>がめん</rt></ruby>の<ruby>実装<rt>じっそう</rt></ruby>は、ほぼ<ruby>完了<rt>かんりょう</rt></ruby>しております。", kana: "ログインがめんのじっそうは、ほぼかんりょうしております。", romaji: "roguin gamen no jissō wa, hobo kanryō shite orimasu.", when: "Báo tình trạng một chức năng cụ thể. Nếu khách hỏi \"ほぼ là bao nhiêu\" hãy chuẩn bị sẵn con số (%, số task còn lại)", level: "謙譲語" },
    { en: "We plan to start the testing phase next Monday.", vi: "Dự kiến từ thứ Hai tuần sau sẽ bước vào giai đoạn kiểm thử.", ja: "来週の月曜日から、テスト工程に入る予定です。", ruby: "<ruby>来週<rt>らいしゅう</rt></ruby>の<ruby>月曜日<rt>げつようび</rt></ruby>から、テスト<ruby>工程<rt>こうてい</rt></ruby>に<ruby>入<rt>はい</rt></ruby>る<ruby>予定<rt>よてい</rt></ruby>です。", kana: "らいしゅうのげつようびから、テストこうていにはいるよていです。", romaji: "raishū no getsuyōbi kara, tesuto kōtei ni hairu yotei desu.", when: "Thông báo mốc chuyển giai đoạn (実装 → テスト). Với khách nên kèm ngày cụ thể, tránh chỉ nói \"sắp\"", level: "丁寧語" },
    { en: "Currently, there is one issue that may affect the schedule.", vi: "Hiện có một vấn đề có thể ảnh hưởng đến lịch.", ja: "現在、スケジュールに影響しそうな課題が一件ございます。", ruby: "<ruby>現在<rt>げんざい</rt></ruby>、スケジュールに<ruby>影響<rt>えいきょう</rt></ruby>しそうな<ruby>課題<rt>かだい</rt></ruby>が<ruby>一件<rt>いっけん</rt></ruby>ございます。", kana: "げんざい、スケジュールにえいきょうしそうなかだいがいっけんございます。", romaji: "genzai, sukejūru ni eikyō shisō na kadai ga ikken gozaimasu.", when: "Báo rủi ro SỚM, ngay khi mới thấy dấu hiệu — khách Nhật rất ghét bị bất ngờ vào phút cuối. Nói tiếp ngay: nội dung + hướng xử lý", level: "丁寧語" },
    { en: "I'll report the details in today's daily report.", vi: "Chi tiết tôi sẽ báo cáo trong báo cáo ngày hôm nay.", ja: "詳細は本日の日報にてご報告いたします。", ruby: "<ruby>詳細<rt>しょうさい</rt></ruby>は<ruby>本日<rt>ほんじつ</rt></ruby>の<ruby>日報<rt>にっぽう</rt></ruby>にてご<ruby>報告<rt>ほうこく</rt></ruby>いたします。", kana: "しょうさいはほんじつのにっぽうにてごほうこくいたします。", romaji: "shōsai wa honjitsu no nippō nite gohōkoku itashimasu.", when: "Khi họp ngắn không đủ thời gian trình bày hết. にて là dạng trang trọng của で, hay dùng trong văn viết/khi nói với khách", level: "謙譲語" },
    { en: "All the tasks planned for this week have been completed.", vi: "Các task dự kiến trong tuần này đều đã hoàn thành.", ja: "今週予定していたタスクは、すべて完了いたしました。", ruby: "<ruby>今週<rt>こんしゅう</rt></ruby><ruby>予定<rt>よてい</rt></ruby>していたタスクは、すべて<ruby>完了<rt>かんりょう</rt></ruby>いたしました。", kana: "こんしゅうよていしていたタスクは、すべてかんりょういたしました。", romaji: "konshū yotei shite ita tasuku wa, subete kanryō itashimashita.", when: "Báo cáo cuối tuần (週次報告). Nếu còn task dở thì nói rõ task nào và khi nào xong, đừng chỉ báo phần tốt", level: "謙譲語" },
    { en: "We're about two days behind, but expect to catch up this week.", vi: "Đang chậm khoảng hai ngày, nhưng dự kiến bắt kịp trong tuần này.", ja: "二日ほど遅れておりますが、今週中に挽回できる見込みです。", ruby: "<ruby>二日<rt>ふつか</rt></ruby>ほど<ruby>遅<rt>おく</rt></ruby>れておりますが、<ruby>今週中<rt>こんしゅうちゅう</rt></ruby>に<ruby>挽回<rt>ばんかい</rt></ruby>できる<ruby>見込<rt>みこ</rt></ruby>みです。", kana: "ふつかほどおくれておりますが、こんしゅうちゅうにばんかいできるみこみです。", romaji: "futsuka hodo okurete orimasu ga, konshūchū ni bankai dekiru mikomi desu.", when: "Báo chậm kèm kế hoạch lấy lại. Chỉ nói 挽回できる khi có cơ sở (thêm người, tăng giờ…); nếu chưa chắc dùng 挽回に努めます", level: "謙譲語" },
    { en: "I've summarized this week's progress below. Please take a look.", vi: "Tôi đã tóm tắt tiến độ tuần này ở dưới, anh/chị xem giúp.", ja: "今週の進捗を以下にまとめましたので、ご確認ください。", ruby: "<ruby>今週<rt>こんしゅう</rt></ruby>の<ruby>進捗<rt>しんちょく</rt></ruby>を<ruby>以下<rt>いか</rt></ruby>にまとめましたので、ご<ruby>確認<rt>かくにん</rt></ruby>ください。", kana: "こんしゅうのしんちょくをいかにまとめましたので、ごかくにんください。", romaji: "konshū no shinchoku o ika ni matomemashita node, gokakunin kudasai.", when: "Câu dẫn trong email/chat báo cáo tuần, sau đó liệt kê gạch đầu dòng: 完了 / 進行中 / 課題. Với khách lịch sự hơn: ご確認いただけますと幸いです", level: "丁寧語" }
  ]},
  { id: "ren", title: "連絡 · Liên lạc & thông báo", items: [
    { en: "I'm writing to inform you about the release date.", vi: "Tôi xin liên lạc về ngày release.", ja: "リリース日についてご連絡いたします。", ruby: "リリース<ruby>日<rt>び</rt></ruby>についてご<ruby>連絡<rt>れんらく</rt></ruby>いたします。", kana: "リリースびについてごれんらくいたします。", romaji: "rirīsu bi ni tsuite gorenraku itashimasu.", when: "Câu mở đầu email/chat thông báo, nêu ngay chủ đề. Tiêu đề email nên ghi rõ: 【ご連絡】リリース日について", level: "謙譲語" },
    { en: "We will stop the server tonight for maintenance.", vi: "Tối nay chúng tôi sẽ tạm dừng server để bảo trì.", ja: "本日の夜間、メンテナンスのためサーバーを停止いたします。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby>の<ruby>夜間<rt>やかん</rt></ruby>、メンテナンスのためサーバーを<ruby>停止<rt>ていし</rt></ruby>いたします。", kana: "ほんじつのやかん、メンテナンスのためサーバーをていしいたします。", romaji: "honjitsu no yakan, mentenansu no tame sābā o teishi itashimasu.", when: "Thông báo bảo trì/downtime. Với khách phải ghi rõ giờ bắt đầu – kết thúc và phạm vi ảnh hưởng, gửi trước ít nhất vài ngày", level: "謙譲語" },
    { en: "Tanaka is off today.", vi: "Hôm nay anh Tanaka (bên tôi) nghỉ.", ja: "本日、田中は休みをいただいております。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby>、<ruby>田中<rt>たなか</rt></ruby>は<ruby>休<rt>やす</rt></ruby>みをいただいております。", kana: "ほんじつ、たなかはやすみをいただいております。", romaji: "honjitsu, tanaka wa yasumi o itadaite orimasu.", when: "Nói với KHÁCH về người trong công ty mình: bỏ さん, dùng 謙譲語. Nên nói thêm ai sẽ hỗ trợ thay và khi nào người đó quay lại", level: "謙譲語" },
    { en: "From today, I will be your contact person for this project.", vi: "Từ hôm nay tôi sẽ là đầu mối liên lạc của dự án này.", ja: "本日より、本プロジェクトの窓口を担当いたします。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby>より、<ruby>本<rt>ほん</rt></ruby>プロジェクトの<ruby>窓口<rt>まどぐち</rt></ruby>を<ruby>担当<rt>たんとう</rt></ruby>いたします。", kana: "ほんじつより、ほんプロジェクトのまどぐちをたんとういたします。", romaji: "honjitsu yori, hon purojekuto no madoguchi o tantō itashimasu.", when: "Khi nhận vai BrSE/đầu mối. Nói xong nên kèm どうぞよろしくお願いいたします. 本プロジェクト = \"dự án này\" (văn trang trọng)", level: "謙譲語" },
    { en: "The meeting has been moved to Thursday afternoon.", vi: "Buổi họp đã được đổi sang chiều thứ Năm.", ja: "打ち合わせは木曜日の午後に変更となりました。", ruby: "<ruby>打<rt>う</rt></ruby>ち<ruby>合<rt>あ</rt></ruby>わせは<ruby>木曜日<rt>もくようび</rt></ruby>の<ruby>午後<rt>ごご</rt></ruby>に<ruby>変更<rt>へんこう</rt></ruby>となりました。", kana: "うちあわせはもくようびのごごにへんこうとなりました。", romaji: "uchiawase wa mokuyōbi no gogo ni henkō to narimashita.", when: "Báo đổi lịch họp. Nếu việc đổi là do phía mình thì thêm lời xin lỗi: こちらの都合で申し訳ございません", level: "丁寧語" },
    { en: "Just to let you know, the spec document has been updated.", vi: "Xin báo là tài liệu đặc tả đã được cập nhật.", ja: "仕様書を更新しましたので、お知らせいたします。", ruby: "<ruby>仕様書<rt>しようしょ</rt></ruby>を<ruby>更新<rt>こうしん</rt></ruby>しましたので、お<ruby>知<rt>し</rt></ruby>らせいたします。", kana: "しようしょをこうしんしましたので、おしらせいたします。", romaji: "shiyōsho o kōshin shimashita node, oshirase itashimasu.", when: "Thông báo có bản spec mới. Nên kèm link + tóm tắt chỗ thay đổi (変更箇所) để khách không phải tự dò", level: "謙譲語" },
    { en: "I'll be on leave next week. Sato will handle things while I'm away.", vi: "Tuần sau tôi nghỉ phép. Trong thời gian vắng mặt, Sato sẽ phụ trách.", ja: "来週は休暇をいただきます。不在中は佐藤が対応いたします。", ruby: "<ruby>来週<rt>らいしゅう</rt></ruby>は<ruby>休暇<rt>きゅうか</rt></ruby>をいただきます。<ruby>不在中<rt>ふざいちゅう</rt></ruby>は<ruby>佐藤<rt>さとう</rt></ruby>が<ruby>対応<rt>たいおう</rt></ruby>いたします。", kana: "らいしゅうはきゅうかをいただきます。ふざいちゅうはさとうがたいおういたします。", romaji: "raishū wa kyūka o itadakimasu. fuzaichū wa satō ga taiō itashimasu.", when: "Báo nghỉ phép với khách càng sớm càng tốt và luôn nêu người thay. Người thay là người công ty mình nên không kèm さん", level: "謙譲語" },
    { en: "I've read your email. I'll check and get back to you.", vi: "Tôi đã đọc email. Tôi sẽ kiểm tra rồi liên lạc lại.", ja: "メールを拝見しました。確認のうえ、改めてご連絡いたします。", ruby: "メールを<ruby>拝見<rt>はいけん</rt></ruby>しました。<ruby>確認<rt>かくにん</rt></ruby>のうえ、<ruby>改<rt>あらた</rt></ruby>めてご<ruby>連絡<rt>れんらく</rt></ruby>いたします。", kana: "メールをはいけんしました。かくにんのうえ、あらためてごれんらくいたします。", romaji: "mēru o haiken shimashita. kakunin no ue, aratamete gorenraku itashimasu.", when: "Trả lời nhanh khi chưa có câu trả lời ngay — khách Nhật đánh giá cao việc phản hồi \"đã nhận\" sớm. Nếu được, hẹn luôn mốc thời gian", level: "謙譲語" }
  ]},
  { id: "sou", title: "相談 · Xin ý kiến", items: [
    { en: "There's one thing I'd like to consult you on. Is now a good time?", vi: "Tôi có một điểm muốn xin ý kiến, bây giờ có tiện không ạ?", ja: "一点ご相談させていただきたいのですが、今よろしいでしょうか。", ruby: "<ruby>一点<rt>いってん</rt></ruby>ご<ruby>相談<rt>そうだん</rt></ruby>させていただきたいのですが、<ruby>今<rt>いま</rt></ruby>よろしいでしょうか。", kana: "いってんごそうだんさせていただきたいのですが、いまよろしいでしょうか。", romaji: "itten gosōdan sasete itadakitai no desu ga, ima yoroshii deshō ka.", when: "Mở lời xin ý kiến trong họp hoặc gọi riêng. 一点 báo trước là chỉ một việc, giúp người nghe yên tâm về thời gian", level: "謙譲語" },
    { en: "We have two options. Which one would you prefer?", vi: "Có hai phương án xử lý. Anh/chị thấy phương án nào tốt hơn?", ja: "対応案が二つございます。どちらがよろしいでしょうか。", ruby: "<ruby>対応案<rt>たいおうあん</rt></ruby>が<ruby>二<rt>ふた</rt></ruby>つございます。どちらがよろしいでしょうか。", kana: "たいおうあんがふたつございます。どちらがよろしいでしょうか。", romaji: "taiōan ga futatsu gozaimasu. dochira ga yoroshii deshō ka.", when: "Khi xin ý kiến nên mang sẵn phương án, đừng chỉ hỏi \"làm sao bây giờ\". Kèm ưu/nhược điểm và khuyến nghị của mình", level: "丁寧語" },
    { en: "We recommend option A because it has less risk.", vi: "Vì ít rủi ro hơn nên phía chúng tôi khuyến nghị phương án A.", ja: "リスクが少ないため、弊社としてはA案をおすすめいたします。", ruby: "リスクが<ruby>少<rt>すく</rt></ruby>ないため、<ruby>弊社<rt>へいしゃ</rt></ruby>としてはA<ruby>案<rt>あん</rt></ruby>をおすすめいたします。", kana: "リスクがすくないため、へいしゃとしてはエーあんをおすすめいたします。", romaji: "risuku ga sukunai tame, heisha to shite wa ē an o osusume itashimasu.", when: "Nêu khuyến nghị kèm lý do. 弊社 = công ty tôi (khiêm nhường, dùng với khách); công ty khách gọi là 御社 khi nói, 貴社 khi viết", level: "謙譲語" },
    { en: "Could we discuss the priority of these tasks?", vi: "Cho tôi xin bàn về mức ưu tiên của các task.", ja: "タスクの優先度について、ご相談させてください。", ruby: "タスクの<ruby>優先度<rt>ゆうせんど</rt></ruby>について、ご<ruby>相談<rt>そうだん</rt></ruby>させてください。", kana: "タスクのゆうせんどについて、ごそうだんさせてください。", romaji: "tasuku no yūsendo ni tsuite, gosōdan sasete kudasai.", when: "Khi việc quá nhiều mà người/thời gian có hạn — để khách tự chọn cái quan trọng, tránh tự ý bỏ bớt", level: "謙譲語" },
    { en: "Would it be possible to extend the deadline by a few days?", vi: "Có thể lùi hạn bàn giao (納期) vài ngày được không ạ?", ja: "納期を数日延ばしていただくことは可能でしょうか。", ruby: "<ruby>納期<rt>のうき</rt></ruby>を<ruby>数日<rt>すうじつ</rt></ruby><ruby>延<rt>の</rt></ruby>ばしていただくことは<ruby>可能<rt>かのう</rt></ruby>でしょうか。", kana: "のうきをすうじつのばしていただくことはかのうでしょうか。", romaji: "nōki o sūjitsu nobashite itadaku koto wa kanō deshō ka.", when: "Xin gia hạn — nên hỏi SỚM, trước hạn chót đủ lâu, và nêu lý do + ngày mới cụ thể. Hỏi sát hạn sẽ mất uy tín", level: "謙譲語" },
    { en: "What approach would work best on your side?", vi: "Theo quý công ty, nên tiến hành theo cách nào thì tốt ạ?", ja: "御社としては、どのような進め方がよろしいでしょうか。", ruby: "<ruby>御社<rt>おんしゃ</rt></ruby>としては、どのような<ruby>進<rt>すす</rt></ruby>め<ruby>方<rt>かた</rt></ruby>がよろしいでしょうか。", kana: "おんしゃとしては、どのようなすすめかたがよろしいでしょうか。", romaji: "onsha to shite wa, dono yō na susumekata ga yoroshii deshō ka.", when: "Hỏi mong muốn của khách về cách làm (quy trình, công cụ, tần suất báo cáo). Trong email viết 貴社 thay cho 御社", level: "尊敬語" },
    { en: "Could we have a short meeting about this?", vi: "Về việc này, có thể cho chúng tôi một buổi họp ngắn không ạ?", ja: "この件について、短時間でもお打ち合わせの機会をいただけないでしょうか。", ruby: "この<ruby>件<rt>けん</rt></ruby>について、<ruby>短時間<rt>たんじかん</rt></ruby>でもお<ruby>打<rt>う</rt></ruby>ち<ruby>合<rt>あ</rt></ruby>わせの<ruby>機会<rt>きかい</rt></ruby>をいただけないでしょうか。", kana: "このけんについて、たんじかんでもおうちあわせのきかいをいただけないでしょうか。", romaji: "kono ken ni tsuite, tanjikan demo ouchiawase no kikai o itadakenai deshō ka.", when: "Khi trao đổi qua chat/email mãi không ra kết luận. ～いただけないでしょうか mềm hơn ～いただけますか", level: "謙譲語" },
    { en: "We'd appreciate your decision by Wednesday.", vi: "Nếu anh/chị quyết định được trước thứ Tư thì thật tốt quá.", ja: "水曜日までにご判断いただけますと幸いです。", ruby: "<ruby>水曜日<rt>すいようび</rt></ruby>までにご<ruby>判断<rt>はんだん</rt></ruby>いただけますと<ruby>幸<rt>さいわ</rt></ruby>いです。", kana: "すいようびまでにごはんだんいただけますとさいわいです。", romaji: "suiyōbi made ni gohandan itadakemasu to saiwai desu.", when: "Luôn kèm hạn trả lời khi xin quyết định, nếu không việc sẽ treo. ～と幸いです là cách nhờ vả nhẹ nhàng, rất hay dùng trong email", level: "謙譲語" }
  ]},
  { id: "spec", title: "仕様確認 · Xác nhận spec & Q&A", items: [
    { en: "Let me check that my understanding of this requirement is correct.", vi: "Cho tôi xác nhận xem mình hiểu yêu cầu này có đúng không.", ja: "この要件の認識が合っているか、確認させてください。", ruby: "この<ruby>要件<rt>ようけん</rt></ruby>の<ruby>認識<rt>にんしき</rt></ruby>が<ruby>合<rt>あ</rt></ruby>っているか、<ruby>確認<rt>かくにん</rt></ruby>させてください。", kana: "このようけんのにんしきがあっているか、かくにんさせてください。", romaji: "kono yōken no ninshiki ga atte iru ka, kakunin sasete kudasai.", when: "Trước khi bắt tay làm, diễn đạt lại yêu cầu bằng lời của mình rồi hỏi câu này. Nội bộ hay gọi là 認識合わせ", level: "謙譲語" },
    { en: "Is the above understanding correct?", vi: "Cách hiểu như trên có sai lệch gì không ạ?", ja: "以上の理解で相違ないでしょうか。", ruby: "<ruby>以上<rt>いじょう</rt></ruby>の<ruby>理解<rt>りかい</rt></ruby>で<ruby>相違<rt>そうい</rt></ruby>ないでしょうか。", kana: "いじょうのりかいでそういないでしょうか。", romaji: "ijō no rikai de sōi nai deshō ka.", when: "Chốt cuối email/Q&A sau khi đã tóm tắt cách hiểu. Trang trọng hơn 合っていますか; khách chỉ cần trả lời 相違ありません", level: "丁寧語" },
    { en: "We've added questions to the Q&A sheet. Please answer them.", vi: "Chúng tôi đã thêm câu hỏi vào bảng Q&A, mong anh/chị trả lời.", ja: "QA表に質問を追記しましたので、ご回答をお願いいたします。", ruby: "QA<ruby>表<rt>ひょう</rt></ruby>に<ruby>質問<rt>しつもん</rt></ruby>を<ruby>追記<rt>ついき</rt></ruby>しましたので、ご<ruby>回答<rt>かいとう</rt></ruby>をお<ruby>願<rt>ねが</rt></ruby>いいたします。", kana: "キューエーひょうにしつもんをついきしましたので、ごかいとうをおねがいいたします。", romaji: "kyū ē hyō ni shitsumon o tsuiki shimashita node, gokaitō o onegai itashimasu.", when: "QA表 (bảng hỏi đáp) là công cụ chuẩn trong dự án offshore. Nên đánh số câu hỏi, ghi mức ưu tiên và hạn trả lời mong muốn", level: "謙譲語" },
    { en: "What should happen when a user enters an invalid value?", vi: "Khi người dùng nhập giá trị không hợp lệ thì hệ thống cần xử lý thế nào ạ?", ja: "不正な値が入力された場合の期待動作を、ご教示いただけますか。", ruby: "<ruby>不正<rt>ふせい</rt></ruby>な<ruby>値<rt>あたい</rt></ruby>が<ruby>入力<rt>にゅうりょく</rt></ruby>された<ruby>場合<rt>ばあい</rt></ruby>の<ruby>期待動作<rt>きたいどうさ</rt></ruby>を、ご<ruby>教示<rt>きょうじ</rt></ruby>いただけますか。", kana: "ふせいなあたいがにゅうりょくされたばあいのきたいどうさを、ごきょうじいただけますか。", romaji: "fusei na atai ga nyūryoku sareta baai no kitai dōsa o, gokyōji itadakemasu ka.", when: "Hỏi về trường hợp ngoại lệ (異常系) mà spec hay bỏ sót. ご教示 = chỉ bảo (trang trọng), hợp để viết trong QA表 hoặc email", level: "謙譲語" },
    { en: "This point doesn't seem to be written in the spec.", vi: "Điểm này có vẻ không được ghi trong tài liệu đặc tả.", ja: "こちらの点は仕様書に記載がないようです。", ruby: "こちらの<ruby>点<rt>てん</rt></ruby>は<ruby>仕様書<rt>しようしょ</rt></ruby>に<ruby>記載<rt>きさい</rt></ruby>がないようです。", kana: "こちらのてんはしようしょにきさいがないようです。", romaji: "kochira no ten wa shiyōsho ni kisai ga nai yō desu.", when: "Chỉ ra chỗ spec thiếu một cách nhẹ nhàng (ようです), không đổ lỗi. Nói tiếp: どのように対応すればよろしいでしょうか", level: "丁寧語" },
    { en: "Is this change included in the current contract?", vi: "Thay đổi này có nằm trong phạm vi hợp đồng lần này không ạ?", ja: "この変更は、今回の契約の対象に含まれるという認識でよろしいでしょうか。", ruby: "この<ruby>変更<rt>へんこう</rt></ruby>は、<ruby>今回<rt>こんかい</rt></ruby>の<ruby>契約<rt>けいやく</rt></ruby>の<ruby>対象<rt>たいしょう</rt></ruby>に<ruby>含<rt>ふく</rt></ruby>まれるという<ruby>認識<rt>にんしき</rt></ruby>でよろしいでしょうか。", kana: "このへんこうは、こんかいのけいやくのたいしょうにふくまれるというにんしきでよろしいでしょうか。", romaji: "kono henkō wa, konkai no keiyaku no taishō ni fukumareru to iu ninshiki de yoroshii deshō ka.", when: "Hỏi ngay khi khách đưa yêu cầu mới giữa chừng, để tránh làm thêm không được tính phí. BrSE nên hỏi trước khi team bắt tay làm", level: "丁寧語" },
    { en: "Could you share a sample of the expected output?", vi: "Anh/chị có thể cung cấp mẫu kết quả đầu ra mong muốn không?", ja: "想定される出力のサンプルをご提供いただけますか。", ruby: "<ruby>想定<rt>そうてい</rt></ruby>される<ruby>出力<rt>しゅつりょく</rt></ruby>のサンプルをご<ruby>提供<rt>ていきょう</rt></ruby>いただけますか。", kana: "そうていされるしゅつりょくのサンプルをごていきょういただけますか。", romaji: "sōtei sareru shutsuryoku no sanpuru o goteikyō itadakemasu ka.", when: "Khi spec mô tả bằng lời khó hiểu (file CSV, báo cáo, email tự động…). Có mẫu thật sẽ tránh hiểu sai hơn mọi giải thích", level: "謙譲語" },
    { en: "I'll add today's decisions to the spec and share it.", vi: "Tôi sẽ bổ sung những điều đã chốt hôm nay vào spec và chia sẻ.", ja: "本日決まった内容を仕様書に追記し、共有いたします。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby><ruby>決<rt>き</rt></ruby>まった<ruby>内容<rt>ないよう</rt></ruby>を<ruby>仕様書<rt>しようしょ</rt></ruby>に<ruby>追記<rt>ついき</rt></ruby>し、<ruby>共有<rt>きょうゆう</rt></ruby>いたします。", kana: "ほんじつきまったないようをしようしょについきし、きょうゆういたします。", romaji: "honjitsu kimatta naiyō o shiyōsho ni tsuiki shi, kyōyū itashimasu.", when: "Cuối buổi họp spec: điều đã chốt bằng lời phải được ghi thành văn bản, nếu không dễ \"nói rồi mà không có\"", level: "謙譲語" }
  ]},
  { id: "plan", title: "見積・スケジュール · Ước lượng, lịch & phạm vi", items: [
    { en: "We estimate this feature will take about five person-days.", vi: "Chúng tôi ước tính chức năng này mất khoảng năm ngày công.", ja: "この機能の工数は、五人日ほどと見込んでおります。", ruby: "この<ruby>機能<rt>きのう</rt></ruby>の<ruby>工数<rt>こうすう</rt></ruby>は、<ruby>五人日<rt>ごにんにち</rt></ruby>ほどと<ruby>見込<rt>みこ</rt></ruby>んでおります。", kana: "このきのうのこうすうは、ごにんにちほどとみこんでおります。", romaji: "kono kinō no kōsū wa, goninnichi hodo to mikonde orimasu.", when: "Báo ước lượng. 人日 = man-day, 人月 (にんげつ) = man-month. Với khách nên nói kèm giả định (前提) của con số", level: "謙譲語" },
    { en: "I'll send you the estimate by tomorrow.", vi: "Chậm nhất trong ngày mai tôi sẽ gửi bảng báo giá/ước lượng.", ja: "明日までにお見積もりをお送りいたします。", ruby: "<ruby>明日<rt>あした</rt></ruby>までにお<ruby>見積<rt>みつ</rt></ruby>もりをお<ruby>送<rt>おく</rt></ruby>りいたします。", kana: "あしたまでにおみつもりをおおくりいたします。", romaji: "ashita made ni omitsumori o ookuri itashimasu.", when: "Hẹn thời điểm gửi báo giá. Văn viết trang trọng hơn có thể dùng 明日 (あす). Đã hẹn thì phải gửi đúng hạn", level: "謙譲語" },
    { en: "If we add this feature, the release may be delayed.", vi: "Nếu thêm chức năng này, release có thể bị chậm.", ja: "この機能を追加する場合、リリースが遅れる可能性がございます。", ruby: "この<ruby>機能<rt>きのう</rt></ruby>を<ruby>追加<rt>ついか</rt></ruby>する<ruby>場合<rt>ばあい</rt></ruby>、リリースが<ruby>遅<rt>おく</rt></ruby>れる<ruby>可能性<rt>かのうせい</rt></ruby>がございます。", kana: "このきのうをついかするばあい、リリースがおくれるかのうせいがございます。", romaji: "kono kinō o tsuika suru baai, rirīsu ga okureru kanōsei ga gozaimasu.", when: "Nói rõ tác động khi khách muốn thêm việc. Đừng im lặng nhận rồi trễ — nói ảnh hưởng ngay lúc đó để khách quyết định", level: "丁寧語" },
    { en: "This request is outside the scope of this phase.", vi: "Yêu cầu này nằm ngoài phạm vi (scope) của đợt này.", ja: "こちらのご要望は、今回のスコープ外となります。", ruby: "こちらのご<ruby>要望<rt>ようぼう</rt></ruby>は、<ruby>今回<rt>こんかい</rt></ruby>のスコープ<ruby>外<rt>がい</rt></ruby>となります。", kana: "こちらのごようぼうは、こんかいのスコープがいとなります。", romaji: "kochira no goyōbō wa, konkai no sukōpu gai to narimasu.", when: "Từ chối lịch sự bằng sự thật khách quan (スコープ外), không nói できません trống không. Nên đề xuất tiếp phương án (câu sau)", level: "丁寧語" },
    { en: "Could we treat it as a change request and quote it separately?", vi: "Chúng tôi xin báo giá riêng việc này như một yêu cầu thay đổi được không?", ja: "変更要望として、別途お見積もりをさせていただいてもよろしいでしょうか。", ruby: "<ruby>変更要望<rt>へんこうようぼう</rt></ruby>として、<ruby>別途<rt>べっと</rt></ruby>お<ruby>見積<rt>みつ</rt></ruby>もりをさせていただいてもよろしいでしょうか。", kana: "へんこうようぼうとして、べっとおみつもりをさせていただいてもよろしいでしょうか。", romaji: "henkō yōbō to shite, betto omitsumori o sasete itadaite mo yoroshii deshō ka.", when: "Đi liền sau khi nói スコープ外: chuyển thành change request (変更要望/CR) để có thêm thời gian và chi phí hợp lý", level: "謙譲語" },
    { en: "To meet the deadline, we propose releasing in two phases.", vi: "Để kịp hạn, chúng tôi đề xuất chia release làm hai đợt.", ja: "納期に間に合わせるため、リリースを二回に分けることをご提案いたします。", ruby: "<ruby>納期<rt>のうき</rt></ruby>に<ruby>間<rt>ま</rt></ruby>に<ruby>合<rt>あ</rt></ruby>わせるため、リリースを<ruby>二回<rt>にかい</rt></ruby>に<ruby>分<rt>わ</rt></ruby>けることをご<ruby>提案<rt>ていあん</rt></ruby>いたします。", kana: "のうきにまにあわせるため、リリースをにかいにわけることをごていあんいたします。", romaji: "nōki ni maniawaseru tame, rirīsu o nikai ni wakeru koto o goteian itashimasu.", when: "Đưa phương án thay vì chỉ báo \"không kịp\". Kèm danh sách chức năng của từng đợt để khách dễ quyết", level: "謙譲語" },
    { en: "Do you have a preferred delivery date?", vi: "Anh/chị có mong muốn về thời hạn bàn giao không ạ?", ja: "ご希望の納期はございますか。", ruby: "ご<ruby>希望<rt>きぼう</rt></ruby>の<ruby>納期<rt>のうき</rt></ruby>はございますか。", kana: "ごきぼうののうきはございますか。", romaji: "gokibō no nōki wa gozaimasu ka.", when: "Hỏi khi nhận yêu cầu mới để ước lượng. ご希望 là kính ngữ cho mong muốn của khách; nội bộ chỉ cần hỏi いつまでに必要ですか", level: "尊敬語" },
    { en: "This estimate is based on the current requirements.", vi: "Bảng ước lượng này được tính dựa trên yêu cầu ở thời điểm hiện tại.", ja: "本見積もりは、現時点の要件をもとに算出しております。", ruby: "<ruby>本<rt>ほん</rt></ruby><ruby>見積<rt>みつ</rt></ruby>もりは、<ruby>現時点<rt>げんじてん</rt></ruby>の<ruby>要件<rt>ようけん</rt></ruby>をもとに<ruby>算出<rt>さんしゅつ</rt></ruby>しております。", kana: "ほんみつもりは、げんじてんのようけんをもとにさんしゅつしております。", romaji: "hon mitsumori wa, genjiten no yōken o moto ni sanshutsu shite orimasu.", when: "Ghi vào đầu/cuối file báo giá để bảo vệ team: yêu cầu thay đổi thì ước lượng cũng thay đổi", level: "謙譲語" }
  ]},
  { id: "bug", title: "不具合・障害 · Bug & sự cố", items: [
    { en: "We found a bug on the payment screen.", vi: "Chúng tôi phát hiện một lỗi ở màn hình thanh toán.", ja: "決済画面で不具合が見つかりました。", ruby: "<ruby>決済<rt>けっさい</rt></ruby><ruby>画面<rt>がめん</rt></ruby>で<ruby>不具合<rt>ふぐあい</rt></ruby>が<ruby>見<rt>み</rt></ruby>つかりました。", kana: "けっさいがめんでふぐあいがみつかりました。", romaji: "kessai gamen de fuguai ga mitsukarimashita.", when: "Báo bug với khách dùng 不具合 (nhẹ nhàng, chuẩn), không dùng バグ trong văn bản chính thức. Sự cố lớn trên production gọi là 障害", level: "丁寧語" },
    { en: "We are now looking into the details.", vi: "Hiện chúng tôi đang điều tra tình hình chi tiết.", ja: "現在、詳しい状況を調査しております。", ruby: "<ruby>現在<rt>げんざい</rt></ruby>、<ruby>詳<rt>くわ</rt></ruby>しい<ruby>状況<rt>じょうきょう</rt></ruby>を<ruby>調査<rt>ちょうさ</rt></ruby>しております。", kana: "げんざい、くわしいじょうきょうをちょうさしております。", romaji: "genzai, kuwashii jōkyō o chōsa shite orimasu.", when: "Báo ngay khi mới biết sự cố, chưa cần có nguyên nhân (第一報). Nên hẹn giờ báo tiếp theo, vd 一時間後に改めてご報告いたします", level: "謙譲語" },
    { en: "Sorry to trouble you, but could you share the steps to reproduce it?", vi: "Phiền anh/chị chia sẻ giúp các bước tái hiện lỗi được không?", ja: "お手数ですが、再現手順を共有いただけますか。", ruby: "お<ruby>手数<rt>てすう</rt></ruby>ですが、<ruby>再現手順<rt>さいげんてじゅん</rt></ruby>を<ruby>共有<rt>きょうゆう</rt></ruby>いただけますか。", kana: "おてすうですが、さいげんてじゅんをきょうゆういただけますか。", romaji: "otesū desu ga, saigen tejun o kyōyū itadakemasu ka.", when: "Khi khách báo lỗi mà thông tin chưa đủ. Mở đầu bằng お手数ですが để nhờ vả không bị như đòi hỏi", level: "謙譲語" },
    { en: "Could you tell me the environment and the time it happened?", vi: "Anh/chị cho biết môi trường và thời điểm xảy ra lỗi được không?", ja: "発生した環境と日時を教えていただけますか。", ruby: "<ruby>発生<rt>はっせい</rt></ruby>した<ruby>環境<rt>かんきょう</rt></ruby>と<ruby>日時<rt>にちじ</rt></ruby>を<ruby>教<rt>おし</rt></ruby>えていただけますか。", kana: "はっせいしたかんきょうとにちじをおしえていただけますか。", romaji: "hassei shita kankyō to nichiji o oshiete itadakemasu ka.", when: "Thu thập thông tin để tra log. Có thể hỏi thêm ブラウザ, 端末 (thiết bị), ユーザーID", level: "謙譲語" },
    { en: "This issue only occurs in the production environment.", vi: "Hiện tượng này chỉ xảy ra trên môi trường production.", ja: "この事象は本番環境でのみ発生しております。", ruby: "この<ruby>事象<rt>じしょう</rt></ruby>は<ruby>本番環境<rt>ほんばんかんきょう</rt></ruby>でのみ<ruby>発生<rt>はっせい</rt></ruby>しております。", kana: "このじしょうはほんばんかんきょうでのみはっせいしております。", romaji: "kono jishō wa honban kankyō de nomi hassei shite orimasu.", when: "事象 = hiện tượng quan sát được, dùng khi chưa rõ nguyên nhân. 本番環境 = production, 検証環境/ステージング環境 = staging", level: "丁寧語" },
    { en: "We applied a temporary fix, and the system is running normally now.", vi: "Chúng tôi đã xử lý tạm thời, hiện hệ thống đang chạy bình thường.", ja: "暫定対応を実施し、現在は正常に稼働しております。", ruby: "<ruby>暫定対応<rt>ざんていたいおう</rt></ruby>を<ruby>実施<rt>じっし</rt></ruby>し、<ruby>現在<rt>げんざい</rt></ruby>は<ruby>正常<rt>せいじょう</rt></ruby>に<ruby>稼働<rt>かどう</rt></ruby>しております。", kana: "ざんていたいおうをじっしし、げんざいはせいじょうにかどうしております。", romaji: "zantei taiō o jisshi shi, genzai wa seijō ni kadō shite orimasu.", when: "Báo đã khắc phục tạm. Phân biệt rõ 暫定対応 (tạm thời) với 恒久対応 (triệt để) — khách Nhật sẽ hỏi tiếp về cái sau", level: "丁寧語" },
    { en: "We'll release the permanent fix by next Tuesday.", vi: "Bản sửa triệt để sẽ được release trước thứ Ba tuần sau.", ja: "恒久対応は、来週の火曜日までにリリースいたします。", ruby: "<ruby>恒久対応<rt>こうきゅうたいおう</rt></ruby>は、<ruby>来週<rt>らいしゅう</rt></ruby>の<ruby>火曜日<rt>かようび</rt></ruby>までにリリースいたします。", kana: "こうきゅうたいおうは、らいしゅうのかようびまでにリリースいたします。", romaji: "kōkyū taiō wa, raishū no kayōbi made ni rirīsu itashimasu.", when: "Hẹn mốc sửa triệt để. Chỉ hứa ngày khi team đã ước lượng; nếu chưa chắc nói 日程が決まり次第ご連絡いたします", level: "謙譲語" },
    { en: "We'll report the cause and prevention measures in writing.", vi: "Chúng tôi sẽ báo cáo bằng văn bản nguyên nhân và biện pháp phòng tái phát.", ja: "発生要因と再発防止策を、書面にてご報告いたします。", ruby: "<ruby>発生要因<rt>はっせいよういん</rt></ruby>と<ruby>再発防止策<rt>さいはつぼうしさく</rt></ruby>を、<ruby>書面<rt>しょめん</rt></ruby>にてご<ruby>報告<rt>ほうこく</rt></ruby>いたします。", kana: "はっせいよういんとさいはつぼうしさくを、しょめんにてごほうこくいたします。", romaji: "hassei yōin to saihatsu bōshisaku o, shomen nite gohōkoku itashimasu.", when: "Sau sự cố, khách Nhật gần như luôn yêu cầu 障害報告書: diễn biến, nguyên nhân, xử lý, biện pháp chống tái diễn", level: "謙譲語" }
  ]},
  { id: "wabi", title: "お詫び・遅延 · Xin lỗi & trễ hạn", items: [
    { en: "We sincerely apologize for the delay in delivery.", vi: "Chúng tôi thành thật xin lỗi vì việc bàn giao bị chậm.", ja: "納品が遅れておりますこと、深くお詫び申し上げます。", ruby: "<ruby>納品<rt>のうひん</rt></ruby>が<ruby>遅<rt>おく</rt></ruby>れておりますこと、<ruby>深<rt>ふか</rt></ruby>くお<ruby>詫<rt>わ</rt></ruby>び<ruby>申<rt>もう</rt></ruby>し<ruby>上<rt>あ</rt></ruby>げます。", kana: "のうひんがおくれておりますこと、ふかくおわびもうしあげます。", romaji: "nōhin ga okurete orimasu koto, fukaku owabi mōshiagemasu.", when: "Xin lỗi trang trọng với khách về trễ hạn (email, họp chính thức). Nói xong phải nêu ngay ngày giao mới", level: "謙譲語" },
    { en: "This was due to insufficient checking on our side. We're truly sorry.", vi: "Việc này là do phía chúng tôi kiểm tra chưa kỹ. Thành thật xin lỗi.", ja: "今回の件は弊社の確認不足によるものです。誠に申し訳ございません。", ruby: "<ruby>今回<rt>こんかい</rt></ruby>の<ruby>件<rt>けん</rt></ruby>は<ruby>弊社<rt>へいしゃ</rt></ruby>の<ruby>確認不足<rt>かくにんぶそく</rt></ruby>によるものです。<ruby>誠<rt>まこと</rt></ruby>に<ruby>申<rt>もう</rt></ruby>し<ruby>訳<rt>わけ</rt></ruby>ございません。", kana: "こんかいのけんはへいしゃのかくにんぶそくによるものです。まことにもうしわけございません。", romaji: "konkai no ken wa heisha no kakunin busoku ni yoru mono desu. makoto ni mōshiwake gozaimasen.", when: "Nhận lỗi rõ ràng, không đổ cho cá nhân (\"dev A làm sai\"). Với khách, lỗi của thành viên là lỗi của 弊社", level: "謙譲語" },
    { en: "We will deliver it by Wednesday at the latest.", vi: "Chậm nhất là thứ Tư chúng tôi sẽ bàn giao.", ja: "遅くとも水曜日までには納品いたします。", ruby: "<ruby>遅<rt>おそ</rt></ruby>くとも<ruby>水曜日<rt>すいようび</rt></ruby>までには<ruby>納品<rt>のうひん</rt></ruby>いたします。", kana: "おそくともすいようびまでにはのうひんいたします。", romaji: "osoku tomo suiyōbi made ni wa nōhin itashimasu.", when: "Cam kết ngày mới sau khi xin lỗi. Chọn ngày có dư địa — trễ lần hai còn tệ hơn nhiều lần đầu", level: "謙譲語" },
    { en: "I'm afraid we won't be able to meet the deadline.", vi: "Rất khó mở lời, nhưng e là chúng tôi sẽ không kịp hạn.", ja: "大変申し上げにくいのですが、納期に間に合わない見込みです。", ruby: "<ruby>大変<rt>たいへん</rt></ruby><ruby>申<rt>もう</rt></ruby>し<ruby>上<rt>あ</rt></ruby>げにくいのですが、<ruby>納期<rt>のうき</rt></ruby>に<ruby>間<rt>ま</rt></ruby>に<ruby>合<rt>あ</rt></ruby>わない<ruby>見込<rt>みこ</rt></ruby>みです。", kana: "たいへんもうしあげにくいのですが、のうきにまにあわないみこみです。", romaji: "taihen mōshiagenikui no desu ga, nōki ni maniawanai mikomi desu.", when: "Báo tin xấu. 申し上げにくいのですが làm mềm câu mở đầu. Báo càng sớm càng tốt, kèm lý do và phương án", level: "謙譲語" },
    { en: "We will review our process so this never happens again.", vi: "Chúng tôi sẽ rà soát lại cách làm để việc này không lặp lại.", ja: "二度とこのようなことがないよう、体制を見直してまいります。", ruby: "<ruby>二度<rt>にど</rt></ruby>とこのようなことがないよう、<ruby>体制<rt>たいせい</rt></ruby>を<ruby>見直<rt>みなお</rt></ruby>してまいります。", kana: "にどとこのようなことがないよう、たいせいをみなおしてまいります。", romaji: "nido to kono yō na koto ga nai yō, taisei o minaoshite mairimasu.", when: "Kết thúc lời xin lỗi về sự cố/chậm trễ. Tốt nhất kèm biện pháp cụ thể (thêm bước review, checklist…), không chỉ hứa suông", level: "謙譲語" },
    { en: "I'm sorry for the short notice.", vi: "Xin lỗi vì báo sát giờ.", ja: "直前のご連絡となり、申し訳ございません。", ruby: "<ruby>直前<rt>ちょくぜん</rt></ruby>のご<ruby>連絡<rt>れんらく</rt></ruby>となり、<ruby>申<rt>もう</rt></ruby>し<ruby>訳<rt>わけ</rt></ruby>ございません。", kana: "ちょくぜんのごれんらくとなり、もうしわけございません。", romaji: "chokuzen no gorenraku to nari, mōshiwake gozaimasen.", when: "Khi báo đổi lịch, nghỉ đột xuất, gửi tài liệu muộn ngay trước buổi họp", level: "謙譲語" },
    { en: "Thank you for waiting.", vi: "Cảm ơn anh/chị đã chờ.", ja: "お待ちいただき、ありがとうございます。", ruby: "お<ruby>待<rt>ま</rt></ruby>ちいただき、ありがとうございます。", kana: "おまちいただき、ありがとうございます。", romaji: "omachi itadaki, arigatō gozaimasu.", when: "Khi trả lời sau khi khách phải chờ (trong họp, trên chat). Chờ lâu thì dùng mạnh hơn: 大変お待たせいたしました", level: "謙譲語" },
    { en: "I misunderstood the requirement. I'll fix it right away.", vi: "Tôi đã hiểu sai yêu cầu. Tôi sẽ sửa gấp.", ja: "要件を誤って理解しておりました。至急修正いたします。", ruby: "<ruby>要件<rt>ようけん</rt></ruby>を<ruby>誤<rt>あやま</rt></ruby>って<ruby>理解<rt>りかい</rt></ruby>しておりました。<ruby>至急<rt>しきゅう</rt></ruby><ruby>修正<rt>しゅうせい</rt></ruby>いたします。", kana: "ようけんをあやまってりかいしておりました。しきゅうしゅうせいいたします。", romaji: "yōken o ayamatte rikai shite orimashita. shikyū shūsei itashimasu.", when: "Nhận lỗi hiểu sai spec. Với khách nên thêm lời xin lỗi ở đầu (申し訳ございません) và hẹn thời điểm sửa xong", level: "謙譲語" }
  ]},
  { id: "mtg", title: "会議 · Họp với khách", items: [
    { en: "Thank you all for joining today's meeting.", vi: "Cảm ơn mọi người hôm nay dù bận vẫn tham gia buổi họp.", ja: "本日はお忙しいところ、お集まりいただきありがとうございます。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby>はお<ruby>忙<rt>いそが</rt></ruby>しいところ、お<ruby>集<rt>あつ</rt></ruby>まりいただきありがとうございます。", kana: "ほんじつはおいそがしいところ、おあつまりいただきありがとうございます。", romaji: "honjitsu wa oisogashii tokoro, oatsumari itadaki arigatō gozaimasu.", when: "Câu mở đầu họp khi mình là người chủ trì. Họp online có thể nói お集まりいただき hoặc ご参加いただき", level: "謙譲語" },
    { en: "Can you hear me clearly?", vi: "Anh/chị có nghe rõ tiếng không ạ?", ja: "こちらの音声は問題なく届いておりますでしょうか。", ruby: "こちらの<ruby>音声<rt>おんせい</rt></ruby>は<ruby>問題<rt>もんだい</rt></ruby>なく<ruby>届<rt>とど</rt></ruby>いておりますでしょうか。", kana: "こちらのおんせいはもんだいなくとどいておりますでしょうか。", romaji: "kochira no onsei wa mondai naku todoite orimasu deshō ka.", when: "Kiểm tra âm thanh đầu buổi họp online. Nếu khách nghe không rõ thì bật camera/chat để hỗ trợ", level: "丁寧語" },
    { en: "Let me share my screen.", vi: "Tôi xin chia sẻ màn hình.", ja: "画面を共有させていただきます。", ruby: "<ruby>画面<rt>がめん</rt></ruby>を<ruby>共有<rt>きょうゆう</rt></ruby>させていただきます。", kana: "がめんをきょうゆうさせていただきます。", romaji: "gamen o kyōyū sasete itadakimasu.", when: "Trước khi share màn hình. Nhớ đóng chat/tab riêng tư trước khi share. Hỏi thêm: 画面は見えていますでしょうか", level: "謙譲語" },
    { en: "There are three items on today's agenda.", vi: "Chương trình họp hôm nay có ba nội dung.", ja: "本日のアジェンダは三点です。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby>のアジェンダは<ruby>三点<rt>さんてん</rt></ruby>です。", kana: "ほんじつのアジェンダはさんてんです。", romaji: "honjitsu no ajenda wa santen desu.", when: "Nói số mục trước giúp khách Nhật nắm cấu trúc buổi họp. Nên gửi アジェンダ trước ít nhất một ngày", level: "丁寧語" },
    { en: "Let's move on to the next topic.", vi: "Vậy chúng ta chuyển sang nội dung tiếp theo.", ja: "それでは、次の議題に移らせていただきます。", ruby: "それでは、<ruby>次<rt>つぎ</rt></ruby>の<ruby>議題<rt>ぎだい</rt></ruby>に<ruby>移<rt>うつ</rt></ruby>らせていただきます。", kana: "それでは、つぎのぎだいにうつらせていただきます。", romaji: "sore dewa, tsugi no gidai ni utsurasete itadakimasu.", when: "Điều phối họp khi mục hiện tại đã xong hoặc đã quá giờ. Nếu còn vấn đề chưa chốt, ghi lại thành 宿題 (việc cần làm tiếp)", level: "謙譲語" },
    { en: "Sorry, could you speak a little more slowly?", vi: "Xin lỗi, anh/chị có thể nói chậm hơn một chút được không?", ja: "恐れ入りますが、もう少しゆっくりお話しいただけますか。", ruby: "<ruby>恐<rt>おそ</rt></ruby>れ<ruby>入<rt>い</rt></ruby>りますが、もう<ruby>少<rt>すこ</rt></ruby>しゆっくりお<ruby>話<rt>はな</rt></ruby>しいただけますか。", kana: "おそれいりますが、もうすこしゆっくりおはなしいただけますか。", romaji: "osoreirimasu ga, mō sukoshi yukkuri ohanashi itadakemasu ka.", when: "Không nghe kịp thì hỏi ngay, đừng gật đầu cho qua. Người Nhật thường vui lòng nói chậm lại khi được nhờ lịch sự", level: "謙譲語" },
    { en: "Finally, let me go over today's decisions.", vi: "Cuối cùng, tôi xin xác nhận lại những điều đã quyết hôm nay.", ja: "最後に、本日の決定事項を確認させていただきます。", ruby: "<ruby>最後<rt>さいご</rt></ruby>に、<ruby>本日<rt>ほんじつ</rt></ruby>の<ruby>決定事項<rt>けっていじこう</rt></ruby>を<ruby>確認<rt>かくにん</rt></ruby>させていただきます。", kana: "さいごに、ほんじつのけっていじこうをかくにんさせていただきます。", romaji: "saigo ni, honjitsu no kettei jikō o kakunin sasete itadakimasu.", when: "Chốt họp: đọc lại 決定事項 và 宿題 (ai – làm gì – hạn nào). Bước này giúp tránh hiểu lệch sau buổi họp", level: "謙譲語" },
    { en: "I'll send the minutes by the end of today.", vi: "Biên bản họp tôi sẽ gửi trong hôm nay.", ja: "議事録は本日中にお送りいたします。", ruby: "<ruby>議事録<rt>ぎじろく</rt></ruby>は<ruby>本日中<rt>ほんじつちゅう</rt></ruby>にお<ruby>送<rt>おく</rt></ruby>りいたします。", kana: "ぎじろくはほんじつちゅうにおおくりいたします。", romaji: "gijiroku wa honjitsuchū ni ookuri itashimasu.", when: "Kết thúc buổi họp. Gửi 議事録 trong ngày là thói quen được khách Nhật đánh giá cao; nhờ khách chỉnh nếu có chỗ sai", level: "謙譲語" }
  ]},
  { id: "uat", title: "レビュー・検収 · Review, nghiệm thu & bàn giao", items: [
    { en: "The environment for your acceptance testing is ready.", vi: "Chúng tôi đã chuẩn bị xong môi trường cho kiểm thử nghiệm thu.", ja: "受け入れテスト用の環境をご用意いたしました。", ruby: "<ruby>受<rt>う</rt></ruby>け<ruby>入<rt>い</rt></ruby>れテスト<ruby>用<rt>よう</rt></ruby>の<ruby>環境<rt>かんきょう</rt></ruby>をご<ruby>用意<rt>ようい</rt></ruby>いたしました。", kana: "うけいれテストようのかんきょうをごよういいたしました。", romaji: "ukeire tesuto yō no kankyō o goyōi itashimashita.", when: "Thông báo khách có thể bắt đầu UAT (受け入れテスト). Gửi kèm URL, tài khoản test và phạm vi cần kiểm tra", level: "謙譲語" },
    { en: "If you find any issues, please let us know.", vi: "Nếu có lỗi gì, mong anh/chị chỉ ra giúp.", ja: "不具合などございましたら、ご指摘いただけますと幸いです。", ruby: "<ruby>不具合<rt>ふぐあい</rt></ruby>などございましたら、ご<ruby>指摘<rt>してき</rt></ruby>いただけますと<ruby>幸<rt>さいわ</rt></ruby>いです。", kana: "ふぐあいなどございましたら、ごしてきいただけますとさいわいです。", romaji: "fuguai nado gozaimashitara, goshiteki itadakemasu to saiwai desu.", when: "Câu kết khi giao bản test/bản review. Nên nói rõ kênh báo lỗi (Backlog, Redmine, QA表…) để phản hồi không bị thất lạc", level: "謙譲語" },
    { en: "I've summarized how we handled your review comments.", vi: "Tôi đã tổng hợp tình trạng xử lý các góp ý khi review.", ja: "レビューでいただいたコメントについて、対応状況をまとめました。", ruby: "レビューでいただいたコメントについて、<ruby>対応状況<rt>たいおうじょうきょう</rt></ruby>をまとめました。", kana: "レビューでいただいたコメントについて、たいおうじょうきょうをまとめました。", romaji: "rebyū de itadaita komento ni tsuite, taiō jōkyō o matomemashita.", when: "Gửi sau vòng review: liệt kê từng comment → 対応済み (đã sửa) / 対応予定 / 対応不要 + lý do", level: "謙譲語" },
    { en: "We have fixed all the points you raised.", vi: "Tất cả các điểm anh/chị chỉ ra, chúng tôi đã sửa xong.", ja: "ご指摘いただいた点は、すべて修正いたしました。", ruby: "ご<ruby>指摘<rt>してき</rt></ruby>いただいた<ruby>点<rt>てん</rt></ruby>は、すべて<ruby>修正<rt>しゅうせい</rt></ruby>いたしました。", kana: "ごしてきいただいたてんは、すべてしゅうせいいたしました。", romaji: "goshiteki itadaita ten wa, subete shūsei itashimashita.", when: "Báo đã sửa xong các điểm review. Chỉ nói すべて khi đã thật sự sửa hết; còn sót thì ghi rõ điểm nào và khi nào xong", level: "謙譲語" },
    { en: "Could you complete the acceptance by the end of this month?", vi: "Anh/chị có thể hoàn tất nghiệm thu trước cuối tháng này được không ạ?", ja: "今月末までに検収のご対応をお願いできますでしょうか。", ruby: "<ruby>今月末<rt>こんげつまつ</rt></ruby>までに<ruby>検収<rt>けんしゅう</rt></ruby>のご<ruby>対応<rt>たいおう</rt></ruby>をお<ruby>願<rt>ねが</rt></ruby>いできますでしょうか。", kana: "こんげつまつまでにけんしゅうのごたいおうをおねがいできますでしょうか。", romaji: "kongetsumatsu made ni kenshū no gotaiō o onegai dekimasu deshō ka.", when: "Nhờ khách nghiệm thu (検収) — mốc quan trọng vì liên quan thanh toán. Hỏi nhẹ nhàng nhưng phải có ngày cụ thể", level: "謙譲語" },
    { en: "I'm sending you the full set of deliverables for this release.", vi: "Tôi xin gửi toàn bộ sản phẩm bàn giao của đợt này.", ja: "今回の納品物一式をお送りいたします。", ruby: "<ruby>今回<rt>こんかい</rt></ruby>の<ruby>納品物一式<rt>のうひんぶついっしき</rt></ruby>をお<ruby>送<rt>おく</rt></ruby>りいたします。", kana: "こんかいののうひんぶついっしきをおおくりいたします。", romaji: "konkai no nōhinbutsu isshiki o ookuri itashimasu.", when: "Email bàn giao. Kèm danh sách 納品物 (source, tài liệu, kết quả test) để khách đối chiếu", level: "謙譲語" },
    { en: "The source code and manuals are in the shared folder.", vi: "Source code và tài liệu hướng dẫn đã được để trong thư mục chung.", ja: "ソースコードとマニュアルは、共有フォルダに格納しております。", ruby: "ソースコードとマニュアルは、<ruby>共有<rt>きょうゆう</rt></ruby>フォルダに<ruby>格納<rt>かくのう</rt></ruby>しております。", kana: "ソースコードとマニュアルは、きょうゆうフォルダにかくのうしております。", romaji: "sōsu kōdo to manyuaru wa, kyōyū foruda ni kakunō shite orimasu.", when: "Chỉ chỗ để tài liệu bàn giao. 格納 (lưu, cất vào) là từ rất hay dùng trong IT Nhật; nên dán đường dẫn cụ thể", level: "謙譲語" },
    { en: "We will provide maintenance support for one month after release.", vi: "Trong một tháng sau release, công ty chúng tôi sẽ hỗ trợ bảo trì.", ja: "リリース後一か月間は、弊社にて保守対応いたします。", ruby: "リリース<ruby>後<rt>ご</rt></ruby><ruby>一<rt>いっ</rt></ruby>か<ruby>月間<rt>げつかん</rt></ruby>は、<ruby>弊社<rt>へいしゃ</rt></ruby>にて<ruby>保守対応<rt>ほしゅたいおう</rt></ruby>いたします。", kana: "リリースごいっかげつかんは、へいしゃにてほしゅたいおういたします。", romaji: "rirīsu go ikkagetsukan wa, heisha nite hoshu taiō itashimasu.", when: "Nói về bảo hành/hỗ trợ sau bàn giao. Phạm vi và thời hạn phải khớp với hợp đồng — không hứa hơn hợp đồng", level: "謙譲語" }
  ]},
  { id: "mail", title: "メール・チャット · Email/chat mở & kết", items: [
    { en: "Thank you for your quick reply.", vi: "Cảm ơn anh/chị đã trả lời nhanh.", ja: "早速のご返信、ありがとうございます。", ruby: "<ruby>早速<rt>さっそく</rt></ruby>のご<ruby>返信<rt>へんしん</rt></ruby>、ありがとうございます。", kana: "さっそくのごへんしん、ありがとうございます。", romaji: "sassoku no gohenshin, arigatō gozaimasu.", when: "Câu mở đầu khi khách trả lời nhanh, đặt ngay sau いつもお世話になっております", level: "尊敬語" },
    { en: "This is Nguyen, in charge of development.", vi: "Tôi là Nguyễn, phụ trách phát triển.", ja: "開発担当のグエンです。", ruby: "<ruby>開発担当<rt>かいはつたんとう</rt></ruby>のグエンです。", kana: "かいはつたんとうのグエンです。", romaji: "kaihatsu tantō no guen desu.", when: "Xưng danh đầu email/chat (thay グエン bằng tên bạn). Email trang trọng: 株式会社〇〇のグエンでございます", level: "丁寧語" },
    { en: "Thank you for the meeting earlier.", vi: "Cảm ơn anh/chị về buổi họp lúc nãy.", ja: "先ほどはお打ち合わせありがとうございました。", ruby: "<ruby>先<rt>さき</rt></ruby>ほどはお<ruby>打<rt>う</rt></ruby>ち<ruby>合<rt>あ</rt></ruby>わせありがとうございました。", kana: "さきほどはおうちあわせありがとうございました。", romaji: "sakihodo wa ouchiawase arigatō gozaimashita.", when: "Mở đầu email gửi ngay sau buổi họp (kèm 議事録, tài liệu). Họp từ hôm trước thì dùng 昨日は／先日は", level: "丁寧語" },
    { en: "Sorry to contact you again.", vi: "Xin lỗi vì liên lạc nhiều lần.", ja: "度々のご連絡、失礼いたします。", ruby: "<ruby>度々<rt>たびたび</rt></ruby>のご<ruby>連絡<rt>れんらく</rt></ruby>、<ruby>失礼<rt>しつれい</rt></ruby>いたします。", kana: "たびたびのごれんらく、しつれいいたします。", romaji: "tabitabi no gorenraku, shitsurei itashimasu.", when: "Khi gửi email/chat thứ hai, thứ ba trong ngày (bổ sung, đính chính). Nên gom việc để không phải gửi nhiều lần", level: "謙譲語" },
    { en: "Could you reply by the end of tomorrow?", vi: "Anh/chị có thể trả lời trong ngày mai được không ạ?", ja: "明日中にご回答いただけますでしょうか。", ruby: "<ruby>明日中<rt>あしたじゅう</rt></ruby>にご<ruby>回答<rt>かいとう</rt></ruby>いただけますでしょうか。", kana: "あしたじゅうにごかいとういただけますでしょうか。", romaji: "ashitajū ni gokaitō itadakemasu deshō ka.", when: "Nhờ trả lời có hạn. Nếu gấp, nói lý do (vd để kịp release) — khách Nhật dễ hợp tác hơn khi hiểu vì sao", level: "謙譲語" },
    { en: "I'll send the files in a separate email.", vi: "File tôi sẽ gửi trong một email riêng.", ja: "ファイルは別途メールにてお送りいたします。", ruby: "ファイルは<ruby>別途<rt>べっと</rt></ruby>メールにてお<ruby>送<rt>おく</rt></ruby>りいたします。", kana: "ファイルはべっとメールにておおくりいたします。", romaji: "fairu wa betto mēru nite ookuri itashimasu.", when: "Khi file lớn hoặc gửi mật khẩu file nén riêng. Nhiều khách Nhật có quy định bảo mật riêng về gửi file — hỏi trước nếu chưa rõ", level: "謙譲語" },
    { en: "Please feel free to message me on chat too.", vi: "Anh/chị cứ thoải mái liên lạc qua chat nhé.", ja: "チャットでもお気軽にご連絡ください。", ruby: "チャットでもお<ruby>気軽<rt>きがる</rt></ruby>にご<ruby>連絡<rt>れんらく</rt></ruby>ください。", kana: "チャットでもおきがるにごれんらくください。", romaji: "chatto demo okigaru ni gorenraku kudasai.", when: "Cuối email, mời khách dùng kênh nhanh hơn (Slack, Teams, Chatwork). Chat với khách vẫn giữ です/ます, không viết trống không", level: "尊敬語" },
    { en: "Thank you in advance for your cooperation.", vi: "Rất mong nhận được sự hợp tác của anh/chị.", ja: "ご協力のほど、何卒よろしくお願い申し上げます。", ruby: "ご<ruby>協力<rt>きょうりょく</rt></ruby>のほど、<ruby>何卒<rt>なにとぞ</rt></ruby>よろしくお<ruby>願<rt>ねが</rt></ruby>い<ruby>申<rt>もう</rt></ruby>し<ruby>上<rt>あ</rt></ruby>げます。", kana: "ごきょうりょくのほど、なにとぞよろしくおねがいもうしあげます。", romaji: "gokyōryoku no hodo, nanitozo yoroshiku onegai mōshiagemasu.", when: "Câu kết trang trọng khi nhờ khách làm gì đó (nghiệm thu, cung cấp dữ liệu). Nội bộ chỉ cần よろしくお願いします", level: "謙譲語" }
  ]}
];
window.JA_BRSE_TIPS = [
  "Nói KẾT LUẬN TRƯỚC, lý do sau — cả khi họp bằng tiếng Anh (\"The conclusion first: …\") lẫn tiếng Nhật (結論から申し上げますと…). Khách Nhật muốn biết ngay: kịp hay không kịp, được hay không được.",
  "Đừng nói \"No problem\" / 大丈夫です khi chưa chắc. Nói \"Let me check and get back to you by …\" / 確認して、〇時までにご連絡いたします — hứa rồi làm không được còn tệ hơn hỏi lại.",
  "Mọi thứ đã chốt bằng lời (trong họp, trên call) phải XÁC NHẬN LẠI BẰNG VĂN BẢN: 議事録, QA表, email tóm tắt. Khách Nhật tin văn bản hơn trí nhớ.",
  "Tin xấu báo SỚM: chậm tiến độ, bug lớn, hiểu sai spec. Báo khi mới có dấu hiệu, kèm phương án — đừng đợi đến sát deadline mới nói.",
  "Người Nhật hiếm khi nói \"No\" thẳng. Câu như 検討します, 難しいですね, \"We'll consider it\" thường nghĩa là \"không\" hoặc \"chưa\". Hỏi lại nhẹ nhàng để biết kết luận thật.",
  "Với khách: công ty mình là 弊社, công ty khách là 御社 (nói) / 貴社 (viết). Người trong công ty mình không kèm さん, kể cả sếp.",
  "Họp bằng tiếng Anh với khách Nhật: nói chậm, câu ngắn, tránh thành ngữ và tiếng lóng; chia sẻ màn hình/viết lên chat các con số và ngày tháng để tránh nghe nhầm.",
  "Yêu cầu mới giữa chừng: đừng nhận ngay rồi làm thêm. Hỏi rõ có nằm trong phạm vi hợp đồng không, nêu ảnh hưởng đến lịch/chi phí, rồi để khách quyết định."
];
