/* Nói Nghề — Tiếng Nhật công sở: câu cố định & keigo nơi làm việc.
 * window.JA_KEIGO: nhóm → items {ja, ruby (furigana chỉ trên kanji), kana, romaji (Hepburn, ā/ō/ū), vi, en, when, level (尊敬語/謙譲語/丁寧語 — mức keigo chủ đạo của câu)}.
 * window.JA_KEIGO_TIPS: mẹo văn hoá keigo / 報連相. File dữ liệu thuần, không build. */
window.JA_KEIGO = [
  { id: "greet", title: "Chào hỏi hằng ngày", items: [
    { ja: "お疲れ様です。", ruby: "お<ruby>疲<rt>つか</rt></ruby>れ<ruby>様<rt>さま</rt></ruby>です。", kana: "おつかれさまです。", romaji: "otsukaresama desu.", vi: "Chào anh/chị (anh/chị vất vả rồi) — câu chào đa năng giữa đồng nghiệp trong ngày", en: "Hello. / Thanks for your hard work.", when: "Gặp đồng nghiệp, cấp trên trong công ty; mở đầu chat/email nội bộ. KHÔNG dùng với khách hàng/đối tác bên ngoài (dùng いつもお世話になっております)", level: "丁寧語" },
    { ja: "おはようございます。", ruby: "おはようございます。", kana: "おはようございます。", romaji: "ohayō gozaimasu.", vi: "Chào buổi sáng (lễ phép)", en: "Good morning.", when: "Lần gặp đầu tiên trong ngày, kể cả với cấp trên. Với đồng nghiệp thân có thể nói おはよう, nhưng với cấp trên phải đủ ございます", level: "丁寧語" },
    { ja: "本日もよろしくお願いいたします。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby>もよろしくお<ruby>願<rt>ねが</rt></ruby>いいたします。", kana: "ほんじつもよろしくおねがいいたします。", romaji: "honjitsu mo yoroshiku onegai itashimasu.", vi: "Hôm nay cũng mong được anh/chị giúp đỡ — lời chào mở đầu ngày làm việc/buổi họp", en: "I look forward to working with you today.", when: "Đầu giờ với cấp trên, đầu buổi họp, đầu cuộc gọi với khách. Với đồng nghiệp ngang hàng có thể rút gọn: 今日もよろしくお願いします", level: "謙譲語" },
    { ja: "行ってまいります。", ruby: "<ruby>行<rt>い</rt></ruby>ってまいります。", kana: "いってまいります。", romaji: "itte mairimasu.", vi: "Tôi đi đây ạ — báo khi rời văn phòng đi công việc (gặp khách, đi công tác)", en: "I'm heading out now.", when: "Nói với mọi người trong phòng khi ra ngoài vì công việc. Không dùng khi tan làm về nhà (dùng お先に失礼します)", level: "謙譲語" },
    { ja: "ただいま戻りました。", ruby: "ただいま<ruby>戻<rt>もど</rt></ruby>りました。", kana: "ただいまもどりました。", romaji: "tadaima modorimashita.", vi: "Tôi đã về rồi ạ — báo khi quay lại văn phòng sau khi ra ngoài", en: "I'm back.", when: "Khi trở về công ty sau khi đi gặp khách/đi công việc. Đồng nghiệp thường đáp: お疲れ様です / お帰りなさい", level: "丁寧語" },
    { ja: "はじめまして、グエンと申します。", ruby: "はじめまして、グエンと<ruby>申<rt>もう</rt></ruby>します。", kana: "はじめまして、グエンともうします。", romaji: "hajimemashite, guen to mōshimasu.", vi: "Rất hân hạnh được gặp, tôi tên là Nguyễn — tự giới thiệu lần đầu (thay グエン bằng họ/tên của bạn)", en: "Nice to meet you. My name is Nguyen.", when: "Lần đầu gặp đồng nghiệp mới, khách hàng, đối tác. Dùng と申します thay vì です để khiêm nhường; không tự thêm さん vào tên mình", level: "謙譲語" },
    { ja: "どうぞよろしくお願いいたします。", ruby: "どうぞよろしくお<ruby>願<rt>ねが</rt></ruby>いいたします。", kana: "どうぞよろしくおねがいいたします。", romaji: "dōzo yoroshiku onegai itashimasu.", vi: "Rất mong được anh/chị giúp đỡ — câu kết sau khi tự giới thiệu", en: "I look forward to working with you.", when: "Sau khi tự giới thiệu, khi nhận dự án mới, khi làm việc lần đầu với ai đó. Mức lịch sự cao, dùng được với mọi đối tượng", level: "謙譲語" },
    { ja: "ご無沙汰しております。", ruby: "ご<ruby>無沙汰<rt>ぶさた</rt></ruby>しております。", kana: "ごぶさたしております。", romaji: "gobusata shite orimasu.", vi: "Đã lâu không liên lạc với anh/chị — lời chào khi gặp lại sau thời gian dài", en: "It's been a long time. / Sorry for not being in touch.", when: "Gặp lại khách hàng, cấp trên cũ sau vài tháng trở lên. Không dùng với người vừa gặp tuần trước", level: "謙譲語" }
  ]},
  { id: "leave", title: "Xin phép & ra về", items: [
    { ja: "失礼します。", ruby: "<ruby>失礼<rt>しつれい</rt></ruby>します。", kana: "しつれいします。", romaji: "shitsurei shimasu.", vi: "Xin phép ạ — nói khi vào/ra phòng, khi làm phiền ai đó", en: "Excuse me.", when: "Gõ cửa vào phòng họp/phòng sếp, khi rời phòng, khi đi ngang trước mặt người khác. Với khách hàng nên dùng 失礼いたします", level: "丁寧語" },
    { ja: "お先に失礼します。", ruby: "お<ruby>先<rt>さき</rt></ruby>に<ruby>失礼<rt>しつれい</rt></ruby>します。", kana: "おさきにしつれいします。", romaji: "osaki ni shitsurei shimasu.", vi: "Tôi xin phép về trước ạ — nói khi tan làm mà người khác vẫn còn làm", en: "I'm leaving for the day. (lit. Excuse me for leaving before you.)", when: "Khi ra về trước đồng nghiệp/cấp trên. Nên hỏi 何かお手伝いできることはありますか trước nếu mọi người đang bận. Không dùng khi ra ngoài vì công việc", level: "丁寧語" },
    { ja: "お疲れ様でした。", ruby: "お<ruby>疲<rt>つか</rt></ruby>れ<ruby>様<rt>さま</rt></ruby>でした。", kana: "おつかれさまでした。", romaji: "otsukaresama deshita.", vi: "Anh/chị vất vả rồi — đáp lại khi người khác ra về, hoặc khi kết thúc buổi họp/công việc", en: "Good work today. / See you.", when: "Đáp lại お先に失礼します, cuối buổi họp. Tránh ご苦労様でした với cấp trên — câu đó chỉ người trên nói với người dưới", level: "丁寧語" },
    { ja: "今、お時間よろしいでしょうか。", ruby: "<ruby>今<rt>いま</rt></ruby>、お<ruby>時間<rt>じかん</rt></ruby>よろしいでしょうか。", kana: "いま、おじかんよろしいでしょうか。", romaji: "ima, ojikan yoroshii deshō ka.", vi: "Bây giờ anh/chị có chút thời gian không ạ? — hỏi trước khi bắt chuyện, báo cáo", en: "Do you have a moment now?", when: "Trước khi hỏi/báo cáo cấp trên đang làm việc. Nhìn tình hình trước: nếu sếp đang gọi điện/đang gấp thì chờ", level: "丁寧語" },
    { ja: "少し席を外します。", ruby: "<ruby>少<rt>すこ</rt></ruby>し<ruby>席<rt>せき</rt></ruby>を<ruby>外<rt>はず</rt></ruby>します。", kana: "すこしせきをはずします。", romaji: "sukoshi seki o hazushimasu.", vi: "Tôi rời chỗ một lát — báo khi đi khỏi bàn làm việc", en: "I'll be away from my desk for a bit.", when: "Báo nhóm khi đi họp ngắn, đi ra ngoài một chút; có thể nhắn trong chat nhóm. Nếu vắng lâu nên nói rõ giờ quay lại", level: "丁寧語" },
    { ja: "お休みをいただきたいのですが。", ruby: "お<ruby>休<rt>やす</rt></ruby>みをいただきたいのですが。", kana: "おやすみをいただきたいのですが。", romaji: "oyasumi o itadakitai no desu ga.", vi: "Tôi muốn xin nghỉ phép ạ — mở lời xin nghỉ với cấp trên", en: "I'd like to request a day off.", when: "Xin nghỉ với cấp trên, nên nói sớm và kèm ngày cụ thể (ví dụ: 来週の金曜日に…). Không chỉ nhắn chat rồi tự nghỉ", level: "謙譲語" }
  ]},
  { id: "confirm", title: "Nhận việc & xác nhận", items: [
    { ja: "承知しました。", ruby: "<ruby>承知<rt>しょうち</rt></ruby>しました。", kana: "しょうちしました。", romaji: "shōchi shimashita.", vi: "Tôi đã rõ ạ / Vâng, tôi hiểu rồi — nhận chỉ thị", en: "Understood. / Certainly.", when: "Nhận việc từ cấp trên, trả lời email/chat. Trang trọng hơn nữa (với khách hàng): 承知いたしました. An toàn hơn 了解しました (了解 bị nhiều người coi là thiếu lễ với cấp trên)", level: "謙譲語" },
    { ja: "かしこまりました。", ruby: "かしこまりました。", kana: "かしこまりました。", romaji: "kashikomarimashita.", vi: "Vâng, tôi đã rõ ạ — nhận yêu cầu một cách rất lễ phép (lễ phép hơn 承知しました)", en: "Certainly. / Of course.", when: "Hay dùng khi nói với khách hàng, qua điện thoại, trong dịch vụ. Với đồng nghiệp ngang hàng nghe hơi quá trang trọng", level: "謙譲語" },
    { ja: "確認いたします。", ruby: "<ruby>確認<rt>かくにん</rt></ruby>いたします。", kana: "かくにんいたします。", romaji: "kakunin itashimasu.", vi: "Tôi sẽ kiểm tra ạ — khi chưa trả lời được ngay", en: "I'll check on that.", when: "Khi được hỏi điều chưa chắc chắn: đừng đoán, hãy nói câu này rồi báo lại. Nên kèm thời hạn: 本日中に確認いたします", level: "謙譲語" },
    { ja: "念のため確認させていただけますか。", ruby: "<ruby>念<rt>ねん</rt></ruby>のため<ruby>確認<rt>かくにん</rt></ruby>させていただけますか。", kana: "ねんのためかくにんさせていただけますか。", romaji: "nen no tame kakunin sasete itadakemasu ka.", vi: "Cho phép tôi xác nhận lại cho chắc ạ — nhắc lại nội dung để tránh hiểu sai", en: "Just to be sure, may I confirm?", when: "Sau khi nhận chỉ thị: nhắc lại hạn chót, số lượng, người phụ trách. Người Nhật đánh giá cao việc xác nhận lại, không coi là phiền", level: "謙譲語" },
    { ja: "もう一度おっしゃっていただけますか。", ruby: "もう<ruby>一度<rt>いちど</rt></ruby>おっしゃっていただけますか。", kana: "もういちどおっしゃっていただけますか。", romaji: "mō ichido osshatte itadakemasu ka.", vi: "Anh/chị có thể nói lại một lần nữa được không ạ?", en: "Could you say that again, please?", when: "Khi nghe không rõ, kể cả qua điện thoại. Tốt hơn nhiều so với gật đầu mà không hiểu. Không dùng もう一回言って với cấp trên", level: "尊敬語" },
    { ja: "いつまでに仕上げればよろしいでしょうか。", ruby: "いつまでに<ruby>仕上<rt>しあ</rt></ruby>げればよろしいでしょうか。", kana: "いつまでにしあげればよろしいでしょうか。", romaji: "itsu made ni shiagereba yoroshii deshō ka.", vi: "Tôi cần hoàn thành trước khi nào ạ? — hỏi hạn chót", en: "By when should I have this done?", when: "Ngay khi nhận việc mà chưa có deadline. Hỏi rõ từ đầu tốt hơn là trễ hạn", level: "丁寧語" }
  ]},
  { id: "horenso", title: "Báo cáo – liên lạc – bàn bạc (報連相)", items: [
    { ja: "ご報告があります。", ruby: "ご<ruby>報告<rt>ほうこく</rt></ruby>があります。", kana: "ごほうこくがあります。", romaji: "gohōkoku ga arimasu.", vi: "Tôi có việc cần báo cáo ạ — câu mở đầu 報告 (báo cáo)", en: "I have something to report.", when: "Mở lời báo cáo với cấp trên (sau 今、お時間よろしいでしょうか). Nói kết luận trước, chi tiết sau", level: "謙譲語" },
    { ja: "ご相談したいことがあります。", ruby: "ご<ruby>相談<rt>そうだん</rt></ruby>したいことがあります。", kana: "ごそうだんしたいことがあります。", romaji: "gosōdan shitai koto ga arimasu.", vi: "Tôi có việc muốn xin ý kiến anh/chị ạ — mở đầu 相談 (bàn bạc)", en: "There's something I'd like to discuss with you.", when: "Khi gặp vấn đề chưa tự quyết được. Nên bàn sớm khi vấn đề còn nhỏ; tốt nhất chuẩn bị sẵn phương án của mình", level: "謙譲語" },
    { ja: "進捗をご報告いたします。", ruby: "<ruby>進捗<rt>しんちょく</rt></ruby>をご<ruby>報告<rt>ほうこく</rt></ruby>いたします。", kana: "しんちょくをごほうこくいたします。", romaji: "shinchoku o gohōkoku itashimasu.", vi: "Tôi xin báo cáo tiến độ ạ", en: "Here's a progress update.", when: "Báo cáo định kỳ trong họp, email, chat. Người Nhật thích được báo cáo giữa chừng (中間報告), không chỉ khi xong việc", level: "謙譲語" },
    { ja: "少し遅れが出ております。", ruby: "<ruby>少<rt>すこ</rt></ruby>し<ruby>遅<rt>おく</rt></ruby>れが<ruby>出<rt>で</rt></ruby>ております。", kana: "すこしおくれがでております。", romaji: "sukoshi okure ga dete orimasu.", vi: "Công việc đang bị chậm một chút ạ — báo tin xấu sớm", en: "We're running a little behind schedule.", when: "Báo ngay khi thấy nguy cơ trễ, kèm lý do và ngày hoàn thành dự kiến. Giấu tin xấu đến phút chót là điều tối kỵ", level: "謙譲語" },
    { ja: "この件について、ご意見を伺えますか。", ruby: "この<ruby>件<rt>けん</rt></ruby>について、ご<ruby>意見<rt>いけん</rt></ruby>を<ruby>伺<rt>うかが</rt></ruby>えますか。", kana: "このけんについて、ごいけんをうかがえますか。", romaji: "kono ken ni tsuite, goiken o ukagaemasu ka.", vi: "Về việc này, tôi có thể xin ý kiến của anh/chị được không ạ?", en: "Could I get your opinion on this matter?", when: "Xin ý kiến cấp trên, khách hàng trước khi quyết định. Với đồng nghiệp ngang hàng có thể nói この件、どう思いますか", level: "謙譲語" },
    { ja: "念のため共有いたします。", ruby: "<ruby>念<rt>ねん</rt></ruby>のため<ruby>共有<rt>きょうゆう</rt></ruby>いたします。", kana: "ねんのためきょうゆういたします。", romaji: "nen no tame kyōyū itashimasu.", vi: "Tôi xin chia sẻ để mọi người nắm thông tin ạ — 連絡 (liên lạc, chia sẻ thông tin)", en: "Sharing this just for your information. (FYI)", when: "Chuyển tiếp email/tài liệu cho nhóm, báo thay đổi lịch. Dùng được trong chat và email nội bộ", level: "謙譲語" },
    { ja: "ご指示をいただけますか。", ruby: "ご<ruby>指示<rt>しじ</rt></ruby>をいただけますか。", kana: "ごしじをいただけますか。", romaji: "goshiji o itadakemasu ka.", vi: "Anh/chị có thể cho tôi chỉ thị được không ạ? — xin hướng xử lý", en: "Could you give me instructions on this?", when: "Khi cần cấp trên quyết định cách làm. Nên trình bày tình hình và phương án trước rồi mới xin chỉ thị", level: "謙譲語" }
  ]},
  { id: "apology", title: "Xin lỗi & nhờ vả", items: [
    { ja: "申し訳ございません。", ruby: "<ruby>申<rt>もう</rt></ruby>し<ruby>訳<rt>わけ</rt></ruby>ございません。", kana: "もうしわけございません。", romaji: "mōshiwake gozaimasen.", vi: "Tôi thành thật xin lỗi — lời xin lỗi trang trọng nhất thường dùng", en: "I sincerely apologize.", when: "Mắc lỗi với cấp trên, khách hàng. すみません quá nhẹ khi lỗi nghiêm trọng; ごめんなさい không dùng ở công việc", level: "丁寧語" },
    { ja: "ご迷惑をおかけして申し訳ございません。", ruby: "ご<ruby>迷惑<rt>めいわく</rt></ruby>をおかけして<ruby>申<rt>もう</rt></ruby>し<ruby>訳<rt>わけ</rt></ruby>ございません。", kana: "ごめいわくをおかけしてもうしわけございません。", romaji: "gomeiwaku o okake shite mōshiwake gozaimasen.", vi: "Tôi xin lỗi vì đã gây phiền phức cho anh/chị", en: "I'm very sorry for the trouble I've caused.", when: "Khi lỗi của mình làm ảnh hưởng người khác (trễ hạn, sai sót, sự cố). Xin lỗi trước, giải thích lý do sau", level: "謙譲語" },
    { ja: "大変失礼いたしました。", ruby: "<ruby>大変<rt>たいへん</rt></ruby><ruby>失礼<rt>しつれい</rt></ruby>いたしました。", kana: "たいへんしつれいいたしました。", romaji: "taihen shitsurei itashimashita.", vi: "Tôi thật thất lễ quá / Xin lỗi vì sơ suất — lỗi nhỏ về phép tắc", en: "I'm terribly sorry. / Please excuse my mistake.", when: "Gửi nhầm email, gọi sai tên, quên chào. Với lỗi gây thiệt hại thực sự nên dùng 申し訳ございません", level: "謙譲語" },
    { ja: "今後気をつけます。", ruby: "<ruby>今後<rt>こんご</rt></ruby><ruby>気<rt>き</rt></ruby>をつけます。", kana: "こんごきをつけます。", romaji: "kongo ki o tsukemasu.", vi: "Từ nay tôi sẽ chú ý hơn ạ — hứa không lặp lại", en: "I'll be more careful from now on.", when: "Sau lời xin lỗi với cấp trên. Với khách hàng nên trang trọng hơn: 今後このようなことがないよう、十分注意いたします", level: "丁寧語" },
    { ja: "お手数ですが、よろしくお願いいたします。", ruby: "お<ruby>手数<rt>てすう</rt></ruby>ですが、よろしくお<ruby>願<rt>ねが</rt></ruby>いいたします。", kana: "おてすうですが、よろしくおねがいいたします。", romaji: "otesū desu ga, yoroshiku onegai itashimasu.", vi: "Làm phiền anh/chị, mong anh/chị giúp cho ạ — nhờ ai làm việc tốn công", en: "Sorry for the trouble, but I'd appreciate your help.", when: "Nhờ người khác kiểm tra, gửi tài liệu, điền form. Rất hay dùng trong email, kể cả khi việc đó thuộc nhiệm vụ của người kia. Trang trọng hơn: お手数をおかけしますが、よろしくお願いいたします", level: "謙譲語" },
    { ja: "恐れ入りますが、もう一度ご確認いただけますか。", ruby: "<ruby>恐<rt>おそ</rt></ruby>れ<ruby>入<rt>い</rt></ruby>りますが、もう<ruby>一度<rt>いちど</rt></ruby>ご<ruby>確認<rt>かくにん</rt></ruby>いただけますか。", kana: "おそれいりますが、もういちどごかくにんいただけますか。", romaji: "osoreirimasu ga, mō ichido gokakunin itadakemasu ka.", vi: "Xin lỗi đã làm phiền, anh/chị có thể kiểm tra lại một lần nữa được không ạ?", en: "I'm sorry to trouble you, but could you check it once more?", when: "恐れ入りますが là \"đệm\" lịch sự trước lời nhờ với khách hàng, cấp trên. Với đồng nghiệp thân thì すみませんが là đủ", level: "謙譲語" },
    { ja: "お忙しいところ恐縮ですが、ご対応いただけますと幸いです。", ruby: "お<ruby>忙<rt>いそが</rt></ruby>しいところ<ruby>恐縮<rt>きょうしゅく</rt></ruby>ですが、ご<ruby>対応<rt>たいおう</rt></ruby>いただけますと<ruby>幸<rt>さいわ</rt></ruby>いです。", kana: "おいそがしいところきょうしゅくですが、ごたいおういただけますとさいわいです。", romaji: "oisogashii tokoro kyōshuku desu ga, gotaiō itadakemasu to saiwai desu.", vi: "Xin lỗi làm phiền lúc anh/chị đang bận, nếu anh/chị xử lý giúp thì tôi rất biết ơn", en: "Sorry to bother you when you're busy, but I'd be grateful if you could handle this.", when: "Nhờ vả trang trọng trong email với khách hàng/cấp trên. Nói miệng với đồng nghiệp thì quá cứng", level: "謙譲語" },
    { ja: "お願いしてもよろしいでしょうか。", ruby: "お<ruby>願<rt>ねが</rt></ruby>いしてもよろしいでしょうか。", kana: "おねがいしてもよろしいでしょうか。", romaji: "onegai shite mo yoroshii deshō ka.", vi: "Tôi có thể nhờ anh/chị việc này được không ạ?", en: "Would it be all right if I asked you to do this?", when: "Nhờ việc cấp trên, bộ phận khác. Mềm mỏng hơn 〜してください (câu đó mang tính yêu cầu, không nên nói với cấp trên)", level: "謙譲語" }
  ]},
  { id: "phone", title: "Họp & điện thoại", items: [
    { ja: "お電話ありがとうございます。", ruby: "お<ruby>電話<rt>でんわ</rt></ruby>ありがとうございます。", kana: "おでんわありがとうございます。", romaji: "odenwa arigatō gozaimasu.", vi: "Cảm ơn quý khách đã gọi điện — câu mở đầu khi nhấc máy", en: "Thank you for calling.", when: "Nghe máy điện thoại công ty, sau đó nói tên công ty (〜でございます). Nếu để chuông reo lâu (quá 3 hồi) thì nói お待たせいたしました", level: "丁寧語" },
    { ja: "少々お待ちください。", ruby: "<ruby>少々<rt>しょうしょう</rt></ruby>お<ruby>待<rt>ま</rt></ruby>ちください。", kana: "しょうしょうおまちください。", romaji: "shōshō omachi kudasai.", vi: "Xin vui lòng đợi một chút ạ", en: "Just a moment, please.", when: "Khi chuyển máy, tra thông tin. Với khách hàng có thể nói mềm hơn: 少々お待ちいただけますでしょうか. Đừng để khách chờ quá lâu", level: "尊敬語" },
    { ja: "折り返しお電話いたします。", ruby: "<ruby>折<rt>お</rt></ruby>り<ruby>返<rt>かえ</rt></ruby>しお<ruby>電話<rt>でんわ</rt></ruby>いたします。", kana: "おりかえしおでんわいたします。", romaji: "orikaeshi odenwa itashimasu.", vi: "Tôi sẽ gọi lại cho anh/chị sau ạ", en: "I'll call you back.", when: "Khi đang bận hoặc người được tìm vắng mặt; hỏi số điện thoại và thời gian tiện gọi lại. Nói xong nhớ gọi lại thật", level: "謙譲語" },
    { ja: "恐れ入りますが、お名前を伺ってもよろしいでしょうか。", ruby: "<ruby>恐<rt>おそ</rt></ruby>れ<ruby>入<rt>い</rt></ruby>りますが、お<ruby>名前<rt>なまえ</rt></ruby>を<ruby>伺<rt>うかが</rt></ruby>ってもよろしいでしょうか。", kana: "おそれいりますが、おなまえをうかがってもよろしいでしょうか。", romaji: "osoreirimasu ga, onamae o ukagatte mo yoroshii deshō ka.", vi: "Xin lỗi, cho tôi hỏi quý danh của anh/chị ạ", en: "May I ask who's calling, please?", when: "Khi người gọi chưa xưng tên. Tránh お名前をいただけますか hay 誰ですか", level: "謙譲語" },
    { ja: "ただいま席を外しております。", ruby: "ただいま<ruby>席<rt>せき</rt></ruby>を<ruby>外<rt>はず</rt></ruby>しております。", kana: "ただいませきをはずしております。", romaji: "tadaima seki o hazushite orimasu.", vi: "Hiện anh ấy/chị ấy không có ở chỗ ạ", en: "He/She is away from his/her desk at the moment.", when: "Trả lời người ngoài công ty khi đồng nghiệp vắng. Khi nói với khách về người công ty mình, gọi họ không có さん (ví dụ: 田中はただいま…)", level: "謙譲語" },
    { ja: "お電話が遠いようなのですが。", ruby: "お<ruby>電話<rt>でんわ</rt></ruby>が<ruby>遠<rt>とお</rt></ruby>いようなのですが。", kana: "おでんわがとおいようなのですが。", romaji: "odenwa ga tōi yō na no desu ga.", vi: "Hình như tín hiệu điện thoại không rõ ạ — cách tế nhị để nói \"tôi nghe không rõ\"", en: "Sorry, I'm having trouble hearing you.", when: "Khi nghe không rõ qua điện thoại/họp online. Không nói 声が小さいです (đổ lỗi cho người nói)", level: "丁寧語" },
    { ja: "それでは、会議を始めさせていただきます。", ruby: "それでは、<ruby>会議<rt>かいぎ</rt></ruby>を<ruby>始<rt>はじ</rt></ruby>めさせていただきます。", kana: "それでは、かいぎをはじめさせていただきます。", romaji: "sore dewa, kaigi o hajimesasete itadakimasu.", vi: "Vậy, tôi xin phép bắt đầu cuộc họp ạ", en: "Well then, let's get the meeting started.", when: "Người chủ trì mở đầu cuộc họp. Họp nội bộ nhỏ có thể nói ngắn: では、始めましょう", level: "謙譲語" },
    { ja: "本日はお時間をいただき、ありがとうございました。", ruby: "<ruby>本日<rt>ほんじつ</rt></ruby>はお<ruby>時間<rt>じかん</rt></ruby>をいただき、ありがとうございました。", kana: "ほんじつはおじかんをいただき、ありがとうございました。", romaji: "honjitsu wa ojikan o itadaki, arigatō gozaimashita.", vi: "Cảm ơn anh/chị đã dành thời gian hôm nay", en: "Thank you for your time today.", when: "Cuối buổi họp/gặp mặt với khách hàng, đối tác, cấp trên. Cũng dùng làm câu mở đầu email cảm ơn sau buổi họp", level: "謙譲語" }
  ]},
  { id: "email", title: "Email công việc", items: [
    { ja: "いつもお世話になっております。", ruby: "いつもお<ruby>世話<rt>せわ</rt></ruby>になっております。", kana: "いつもおせわになっております。", romaji: "itsumo osewa ni natte orimasu.", vi: "Cảm ơn anh/chị luôn giúp đỡ — câu chào mở đầu email gửi bên ngoài", en: "Thank you for your continued support. (standard email opener)", when: "Đầu email/cuộc gọi với khách hàng, đối tác. Email nội bộ thì dùng お疲れ様です thay vì câu này", level: "謙譲語" },
    { ja: "先日の件について、ご連絡いたします。", ruby: "<ruby>先日<rt>せんじつ</rt></ruby>の<ruby>件<rt>けん</rt></ruby>について、ご<ruby>連絡<rt>れんらく</rt></ruby>いたします。", kana: "せんじつのけんについて、ごれんらくいたします。", romaji: "senjitsu no ken ni tsuite, gorenraku itashimasu.", vi: "Tôi xin liên lạc về việc hôm trước ạ — nêu mục đích email", en: "I'm writing regarding the matter we discussed the other day.", when: "Câu thứ hai của email, ngay sau lời chào: nói luôn mục đích. Thay 先日の件 bằng chủ đề cụ thể nếu có", level: "謙譲語" },
    { ja: "資料を添付いたしますので、ご確認ください。", ruby: "<ruby>資料<rt>しりょう</rt></ruby>を<ruby>添付<rt>てんぷ</rt></ruby>いたしますので、ご<ruby>確認<rt>かくにん</rt></ruby>ください。", kana: "しりょうをてんぷいたしますので、ごかくにんください。", romaji: "shiryō o tenpu itashimasu node, gokakunin kudasai.", vi: "Tôi xin gửi kèm tài liệu, anh/chị vui lòng kiểm tra", en: "Please find the attached document.", when: "Gửi file đính kèm. Với khách hàng, nên mềm hơn: ご確認いただけますと幸いです. Nhớ kiểm tra đã đính kèm file chưa", level: "謙譲語" },
    { ja: "ご確認のほど、よろしくお願いいたします。", ruby: "ご<ruby>確認<rt>かくにん</rt></ruby>のほど、よろしくお<ruby>願<rt>ねが</rt></ruby>いいたします。", kana: "ごかくにんのほど、よろしくおねがいいたします。", romaji: "gokakunin no hodo, yoroshiku onegai itashimasu.", vi: "Rất mong anh/chị kiểm tra giúp ạ — câu kết khi nhờ xem/duyệt", en: "I'd appreciate it if you could review this.", when: "Cuối email gửi tài liệu, báo giá, bản thảo. Dùng được với cả cấp trên và khách hàng", level: "謙譲語" },
    { ja: "ご返信が遅くなり、申し訳ございません。", ruby: "ご<ruby>返信<rt>へんしん</rt></ruby>が<ruby>遅<rt>おそ</rt></ruby>くなり、<ruby>申<rt>もう</rt></ruby>し<ruby>訳<rt>わけ</rt></ruby>ございません。", kana: "ごへんしんがおそくなり、もうしわけございません。", romaji: "gohenshin ga osoku nari, mōshiwake gozaimasen.", vi: "Xin lỗi vì đã trả lời muộn", en: "I apologize for the delayed reply.", when: "Đầu email khi trả lời chậm (khoảng từ 1–2 ngày làm việc trở lên). Trả lời chậm vài tiếng thì không cần", level: "謙譲語" },
    { ja: "ご不明な点がございましたら、お気軽にお問い合わせください。", ruby: "ご<ruby>不明<rt>ふめい</rt></ruby>な<ruby>点<rt>てん</rt></ruby>がございましたら、お<ruby>気軽<rt>きがる</rt></ruby>にお<ruby>問<rt>と</rt></ruby>い<ruby>合<rt>あ</rt></ruby>わせください。", kana: "ごふめいなてんがございましたら、おきがるにおといあわせください。", romaji: "gofumei na ten ga gozaimashitara, okigaru ni otoiawase kudasai.", vi: "Nếu có điểm nào chưa rõ, xin anh/chị cứ thoải mái liên hệ", en: "If you have any questions, please feel free to contact us.", when: "Cuối email gửi khách hàng, bên ngoài. Với cấp trên trong công ty thì 何かございましたらお知らせください tự nhiên hơn", level: "尊敬語" },
    { ja: "引き続きよろしくお願いいたします。", ruby: "<ruby>引<rt>ひ</rt></ruby>き<ruby>続<rt>つづ</rt></ruby>きよろしくお<ruby>願<rt>ねが</rt></ruby>いいたします。", kana: "ひきつづきよろしくおねがいいたします。", romaji: "hikitsuzuki yoroshiku onegai itashimasu.", vi: "Rất mong tiếp tục được anh/chị giúp đỡ — câu kết email đang trao đổi dở", en: "I look forward to continuing to work with you.", when: "Kết email trong chuỗi trao đổi đang diễn ra, dự án đang chạy. Email đầu tiên gửi ai đó thì dùng どうぞよろしくお願いいたします", level: "謙譲語" },
    { ja: "取り急ぎご連絡まで。", ruby: "<ruby>取<rt>と</rt></ruby>り<ruby>急<rt>いそ</rt></ruby>ぎご<ruby>連絡<rt>れんらく</rt></ruby>まで。", kana: "とりいそぎごれんらくまで。", romaji: "toriisogi gorenraku made.", vi: "Tôi xin báo nhanh trước như vậy — câu kết email báo tin gấp, ngắn", en: "Just a quick note for now.", when: "Email ngắn báo tin gấp, sẽ gửi chi tiết sau; hay dùng với đồng nghiệp/đối tác quen. Với khách hàng quan trọng/cấp trên cao nên viết 取り急ぎご連絡申し上げます hoặc tránh dùng", level: "謙譲語" }
  ]}
];

window.JA_KEIGO_TIPS = [
  "報連相 (ほうれんそう) = 報告 (báo cáo) · 連絡 (liên lạc) · 相談 (bàn bạc): nền tảng làm việc ở công ty Nhật. Báo sớm, báo cả khi chưa xong, đặc biệt là tin xấu.",
  "Khi báo cáo, nói KẾT LUẬN TRƯỚC (結論から申し上げますと…), sau đó mới đến lý do và chi tiết.",
  "尊敬語 nâng hành động của NGƯỜI KHÁC (おっしゃる, いらっしゃる); 謙譲語 hạ hành động của MÌNH (申す, 伺う, いたす); 丁寧語 là lịch sự chung (です/ます/ございます). Đừng dùng 尊敬語 cho chính mình.",
  "Nói với khách hàng về người trong công ty mình (kể cả sếp): bỏ さん và dùng 謙譲語 — ví dụ 田中は席を外しております, không nói 田中さんはいらっしゃいません.",
  "ご苦労様です là câu người trên nói với người dưới — với cấp trên và đồng nghiệp hãy dùng お疲れ様です.",
  "Chưa chắc thì đừng trả lời \"はい\" cho qua: hãy nói 確認いたします hoặc xác nhận lại (念のため確認させていただけますか). Hiểu sai rồi làm sai còn mất lòng hơn hỏi lại."
];
